### ISSUE TITLE
Changelog & update for firestore emulator

### ISSUE THREAD

**Issue by SamyPesse** [firebase/firebase-tools#1039]
This issue is about documentation, I'm opening in this repository since `firebase-tools` is the interface between the user and the Firestore emulator.

I couldn't find a changelog for the emulator, it'd be great to have one to stay up to date with the improvements you are making on it.

Also it'd be useful to have a notification when a new version of the emulator is released, with a prompt of the command to run to update (like the one when a new version of `firebase-tools` has been released).

**Comment by bkendall** [comment]
AFAIK, the emulator will be tied with the version of `firebase-tools`, so there won't be additional update checking outside of the current logic for `firebase-tools`.

I do not believe the folks working on the emulator have a plan for a separate changelog (since it's tied with `firebase-tools`), so the best bet for getting updates is to (either/or):
- check the release notes on the [Firebase website](https://firebase.google.com/support/release-notes/js)
- watch the [releases page on this repository](https://github.com/firebase/firebase-tools/releases)
- keep an eye on [Twitter for the releases](https://twitter.com/FirebaseRelease)

**Comment by ryanpbrewster** [comment]
Yep. When we release updates to the emulator, they'll go out with a new release of `firebase-tools`. You can find update notes in that changelog.
