### ISSUE TITLE
Block until cloud function has fully deployed?

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/firebase-tools#1139]
Currently, `firebase deploy` waits until GCP does its server side validation, but doesn't wait until the new function has been completely deployed and has overwritten the old one. It'd be nice to have a flag to wait until the function has been fully deployed for CD.

Currently, I have a hardcoded 1 minute wait to send a pubsub event to trigger the function. Without that hardcoded wait, it would trigger the old function instead of the freshly deployed one.

**Comment by thechenky** [comment]
Hi @SUPERCILEX thank you for your feedback. I agree with you and can tell you we have had discussions about this internally. Unfortunately this is more complicated to implement, but I'll pass on this info to our internal teams. Since we do not track feature requests on github, I'm going to close this out. If anyone else wants to +1 this issue, however, feel free to post more comments here.
