### ISSUE TITLE
Is it possible to define retry when deploying functions?

### ISSUE THREAD

**Issue by fvcaputo** [firebase/firebase-tools#1141]
This is more of a question really, I was going through the documentation but couldn't find anything specific.

My question is if it's possible to state that a function (or a group of functions) should be retry in the case of failures? Seems like there is an option like that on the [gcloud cli](https://cloud.google.com/sdk/gcloud/reference/functions/deploy#--retry) so I thought maybe there was something similar when using firebase deploy?

Or maybe is that already the default behavior when deploying through firebase cli?

**Comment by kevinajian** [comment]
Thanks for the feedback.

We've previously explored this but currently decided not to expose this in our sdk because the option will [retry your function for 7 days](https://cloud.google.com/functions/docs/reference/rpc/google.cloud.functions.v1#google.cloud.functions.v1.FailurePolicy), which can lead to unexpectedly large bills if there is an error. For now you can set the option in the [Cloud Console](https://cloud.google.com/functions/docs/bestpractices/retries#using_the) after you've deployed through the Firebase CLI.

**Comment by dinvlad** [comment]
Are there any updates on when this feature will be available in the Firebase SDK?

**Comment by dinvlad** [comment]
A Google contact recently recommended to us another solution - there’s Cloud Tasks API that allows rerunning background tasks with exponential retry etc. It’s a much more flexible serverless solution for this. We haven’t tried it yet, but it looks very promising.
