### ISSUE TITLE
SHA256 auth:import rounds > 8192

### ISSUE THREAD

**Issue by Dag0n** [firebase/firebase-tools#1146]
### Description
It appears that you cannot use rounds higher than 8192 when trying to import users using SHA256

### Sample Commands
`firebase auth:import users.json --hash-algo=SHA256 --hash-input-order=SALT_FIRST --rounds=36637` 

### Error
`Error: HTTP Error: 400, INVALID_HASH_ROUNDS`

**Comment by Memeriaj** [comment]
Interesting, because it seems that we do [validate the number of rounds prior to making the request](https://github.com/firebase/firebase-tools/blob/master/src/accountImporter.js#L177-L190).  I'll look into whether we should be adjusting the validation in the CLI or on the server side.

**Comment by Memeriaj** [comment]
You are correct, the server limits `MD5`, `SHA1`, `SHA256`, and `SHA512` all to 8192 rounds but the CLI was validating them as if they were `PBKDF_SHA1` or `PBKDF2_SHA256`.  Updating the CLI validation to reflect that so that the feedback is immediate and the error will be much more straightforward.

**Comment by bkendall** [comment]
Closing as the fix has been merged (and will be shipped Soon(tm))
