### ISSUE TITLE
Documentation for database:get as module?

### ISSUE THREAD

**Issue by remisture** [firebase/firebase-tools#1157]
Where can I find documentation on how to use `database:get` as a module with Node?

Something like this is not working:

```javascript
const client = require('firebase-tools');

client.database.get('/path').then(function (data) {
	console.dir(data);
}).catch(function (err) {
	// handle error
});
```

**Comment by laurenzlong** [comment]
@remisture You can find instructions in the readme: https://github.com/firebase/firebase-tools#using-as-a-module. I suspect your error is from the fact that you didn't supply the correct credentials and project ID in order to access your database. See the second code sample for how to do that. See the section on [Using CI Systems](https://github.com/firebase/firebase-tools#using-with-ci-systems) to learn how to get a token. 

I've filed an internal feature request for getting this added to the official docs as well (bug reference 126927314)
