### ISSUE TITLE
Cannot deploy functions using firebase-admin and ADC via firebase-tools

### ISSUE THREAD

**Issue by iwata** [firebase/firebase-tools#1319]
### [REQUIRED] Environment info

**firebase-tools:**
6.10.0

**Platform:**
macOS
### [REQUIRED] Test case
deploy functions using firebase-admin and ADC about Node 1

### [REQUIRED] Steps to reproduce

```
firebase deploy --only functions
```

### [REQUIRED] Expected behavior

Deploy successfully.

### [REQUIRED] Actual behavior
It occurred these errors.

```
⚠  functions[onCreate(us-central1)]: Deployment error.
Function failed on loading user code. Error message: Warning, FIREBASE_CONFIG environment variable is missing. Initializing firebase-admin will fail
Provided module can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: TypeError: Cannot read property 'days' of undefined
    at Object.<anonymous> (/srv/functions/lib/index.js:32:65)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.getUserFunction (/srv/node_modules/@google-cloud/functions-framework/build/src/invoker.js:57:32)
    at Object.<anonymous> (/srv/node_modules/@google-cloud/functions-framework/build/src/index.js:49:33)
Could not load the function, shutting down.
```

I re-tried with setting `FIREBASE_CONFIG`, but the result did not change, and the same error was output.
Here is my initialization code.

```
import * as admin from 'firebase-admin'
admin.initializeApp()
```

related with this issue
https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/25

**Comment by bkendall** [comment]
In your `/srv/functions/lib/index.js:32` (I _think_ that's in the code you're trying to deploy), is there an error trying to access `days`?

`"Provided module can't be loaded. Is there a syntax error in your code?"` leads me to believe that there's a different issue in the code rather than just the variable not existing.

Can you provide a little more about your source? If you're doing something with `admin` in the top level scope (outside a function that would be deployed) it may cause similar issues.

**Comment by iwata** [comment]
First of all, as a matter of fact, Node 8 with exactly the same source code does not cause this error and can be deployed successfully. If it is Node 10, an error will occur.

So it is assumed that `/srv/functions/lib/index.js: 32` is not a problem.
By the way the source of the line is something like.

```javascript
const TRANSITION_MILLIS = parseInt(functions.config().transition.days, 10) * 86400000;
```

**Comment by thechenky** [comment]
@iwata thanks for refiling your issue here - I'm confirming that this is a known Node 10 bug that does not properly populate `functions.config()` as per my original comment in https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/25#issuecomment-491006528. The fix should be rolling out to production this week, I will update this thread when that goes out. Thanks!

**Comment by iwata** [comment]
@thechenky 
Any progress?

**Comment by thechenky** [comment]
Hi @iwata the fix is out, please redeploy your function.

**Comment by thechenky** [comment]
Note that there are some other kinks that we are still ironing out with Node 10 - follow the firebase-functions repo for those, but this particular issue should be fixed.
