### ISSUE TITLE
"Uncaught SyntaxError: Unexpected token <" after firebase deploy

### ISSUE THREAD

**Issue by grrrian** [firebase/firebase-tools#1324]
### [REQUIRED] Environment info

**firebase-tools:* 6.10.0

**Platform:** Ubuntu (Bitbucket Pipelines running Node 9.5.0)

### [REQUIRED] Test case

When visiting a deployed website, I get a blank page with the console error: `Uncaught SyntaxError: Unexpected token <`. Refreshing the webpage fixes it!

### [REQUIRED] Steps to reproduce

1. Deploy you website
2. Visit it on Chrome
3. Close you browser tab
4. Deploy a new version
5. Visit it on Chrome
6. See a blank page with the above error :(

### [REQUIRED] Expected behavior

See your website!

### [REQUIRED] Actual behavior

See a blank page with the above error :(

Note: Refreshing the page fixes the issue!

**Comment by abeisgoat** [comment]
Please fill out the template when opening a bug.

**Comment by abeisgoat** [comment]
Thanks for filling out the template.

**Comment by abeisgoat** [comment]
This is likely an issue in your code, Firebase Hosting ships your code verbatim to our CDN, so it's very unlikely that this is an issue on our end. Can you provide a link to a page where you're seeing this so I can take a look?

**Comment by grrrian** [comment]
https://sonoma-staging-qa.firebaseapp.com/

**Comment by grrrian** [comment]
I'm wondering if it has something to do with the way Chrome caches websites, because it only happens after i visit a website that i re-deployed. And refreshing fixes the issue :(

**Comment by grrrian** [comment]
I could re-deploy it to allow you to test it.

**Comment by abeisgoat** [comment]
Yeah so it's a cache behavior, not a bug with hosting.

The build chain for your app (Webpack, Parcel, whatever) uses whats called "cache-breaking filenames". These are randomly generated look a bit crazy and they are *different* on each build. For example, the current build references `https://sonoma-staging-qa.firebaseapp.com/static/js/main.d8ee1b86.js` when you rebuild and redeploy you'll now have `https://sonoma-staging-qa.firebaseapp.com/static/js/main.XXXXXXX.js`. 

Normally you want this because it keeps you from mixing assets from multiple releases in the client's cache. You'll never have old JS on a new page. When you load your site you hit the main HTML page which then pulls in all the CSS, JS, etc. The browser will often cache this homepage and depending on how your caching headers are set up (or aren't set up) it may or may not cache the underlying CSS / JS assets.

So imagine we reploy, we make a new homepage which is now looking for new randomly-generated cache-breaking filenames. If you go to your site and refresh, your browser may be caching the homepage. If it serves up the cached homepage from the previous release then none of the assets it wants will exist anymore because the randomly generated filenames no longer exist because your latest deploy removed them.

So how does this surface to you? Well, we get this crazy error because `<script src="./non-existant-script.js"></script>` will resolve to a 404 page, specifically a 404 page written in HTML where the first character is `<`. If you try to evaluate HTML as JS, you get an unexpected token error.

To work around this you can work on the cache headers for your homepage and ensure that the browser aggressively refreshes it, you can disable the cache-breaking filenames (which is easy but might result in mixing versions), or you can ignore it because it only happens if you've recently cached the old homepage and most users wont hit that.

**Comment by grrrian** [comment]
Thanks a lot! How would you recommend creating cache headers to force refreshes?

**Comment by grrrian** [comment]
Perhaps i'll try this:
```
<meta http-equiv=“Pragma” content=”no-cache”>
<meta http-equiv=“Expires” content=”-1″>
<meta http-equiv=“CACHE-CONTROL” content=”NO-CACHE”>
```

**Comment by abeisgoat** [comment]
Personally, if I don't want any error, then I'd disable all caching on the homepage. You can specify the headers in `firebase.json` ([docs](https://firebase.google.com/docs/hosting/full-config#headers)) and here's a [Stackoverflow post about disabling caching with HTTP headers](https://stackoverflow.com/a/2068407/1570248).

If you do this, it will be more expensive and slower because the client will fetch the page on each release, however the actual HTML page is very small, so it probably wont make a big difference. The assets, which are the big part, will still cache normally.

Freshness vs. speed is always a trade-off and it depends on your use-case, release cycle, and tolerance for different issues.

**Comment by grrrian** [comment]
Sweet, thanks a bunch @abeisgoat !

**Comment by rahulbansal16** [comment]
@abeisgoat 
> So how does this surface to you? Well, we get this crazy error because <script src="./non-existant-script.js"></script> will resolve to a 404 page, specifically a 404 page written in HTML where the first character is <. If you try to evaluate HTML as JS, you get an unexpected token error.

My browser is returning the non-existant-script.js from the disk cache, but the content of the file is latest index.html deployed?

How is it possible?

**Comment by sanjay51** [comment]
This is a pain, but I understand the reasoning based on responses.

Is it possible to force a cache + page refresh, when this issue occurs?

Perhaps some javascript snippet I can paste somewhere on my website, although I'm not sure how.

**Comment by neekey** [comment]
hi guys, i'm facing the same issue, and it's actually common if you front end is a single page application with lazy resource load when open a new route.
Ths issue is caused when a new version of firebase hosting is deployed, it might have wiped out all the resources serving from the previous version (even if they have different names).

so when a user who has their front end page open before the deployment, when they continue their browsing after the deployment without a page refresh, when they navigate to a different route with resource that has not been loaded before, their existing page resource loader will try to load the assets from the previous version, which cause firebase return a 404 html page for the resources, and therefore causing the error.

@abeisgoat is there anyway we can keep like just the previous release version on the hosting?

**Comment by danias** [comment]
> > make a new homepage which is now looking for new randomly-generated cache-breaking filenames. If you go to your site and refresh, your browser may be caching the homepage. If it serves up the cached homepage from the previous release then none of the assets it wants will exist anymore because the randomly generated filenames no longer exist because your latest deploy removed them.
> > So how does this surface to you? Well, we get this crazy error because `<script src="./non-existant-script.js"></script>` will resolve to a 404 page, specifically a 404 page written in HTML where the first character is `<`. If you try to evaluate HTML as JS, you get an unexpected
> 
> This is not really an answer to the problem, i'm quite shocked that u guys knew about this issue, and that was the proposed solution!

There can't really be an elegant solution. If a file is not found a 404 is returned. If a js file is not found then there is an error with something on your code. Another reason this could happen is that you are doing rewrites and you have relative imports of js files. For example, if you have a page that imports ./scripts/myscript.js and now you rewrite /hello/world to index.html then ./scripts/myscript.js would mean /hello/scripts/myscript.js which would return a 404.

**Comment by flymauntains** [comment]
I delete browser cache, problem is not solved.
how solve it?

**Comment by flymauntains** [comment]
I solve problem by downgrading firebase-tools from 13.11.4 to 13.11.2.
`npm uninstall -g firebase-tools@13.11.4`
`npm install -g firebase-tools@13.11.2 `

**Comment by ondrejpolach** [comment]
> I solve problem by downgrading firebase-tools from 13.11.4 to 13.11.2. `npm uninstall -g firebase-tools@13.11.4` `npm install -g firebase-tools@13.11.2 `

I solved problem also downgrading cli to 13.11.2. Something wrong with latest CLI or something temporary in firebase hosting?

**Comment by thamiemohlabi** [comment]
> I solve problem by downgrading firebase-tools from 13.11.4 to 13.11.2. `npm uninstall -g firebase-tools@13.11.4` `npm install -g firebase-tools@13.11.2 `

This worked for me the is definately something wrong with the firebase-tool update

**Comment by Ramyarajmohan** [comment]
I am also facing the same issue. Even tried to uninstall latest firbase tools version to install -g firebase-tools@13.11.2. Cleared browser cache as well, but still facing main.6f51c9f9.js:1 Uncaught SyntaxError: Unexpected token '<' issue.

**Comment by RanderThe** [comment]
When i try to do this from my MAC it works, from my windows doesnt work... i cant understand yet

**Comment by PramodaNF** [comment]
> I solve problem by downgrading firebase-tools from 13.11.4 to 13.11.2. `npm uninstall -g firebase-tools@13.11.4` `npm install -g firebase-tools@13.11.2 `

downgrading firebase-tools worked for me
after deploy do empty cache and hard reload :-)
thank you

**Comment by TsuriH** [comment]
> I solve problem by downgrading firebase-tools from 13.11.4 to 13.11.2. `npm uninstall -g firebase-tools@13.11.4` `npm install -g firebase-tools@13.11.2 `

WORKED LIKE A CHARME, notice that after doing that nothing changed only when I also delete the cache it worked, that's so wierd that I should downgrade version in order to make it works, anyway, thanks

**Comment by leofinzelik** [comment]
I successfully resolved the issue by downgrading firebase-tools from version 13.11.4 to 13.11.2 using the following commands:. `npm uninstall -g firebase-tools@13.11.4  `

`npm install -g firebase-tools@13.11.2`
Thank you so much for your guidance! It worked perfectly.

**Comment by andrewstancinu** [comment]
I solve by downgrading firebase-tools from 13.11.4 to 13.11.2.
Wonderful. Thank you

**Comment by tomasjeperson094** [comment]
I solved by downgrading firebase-tools from 13.11.4 to 13.11.2.
Wonderful. Thank you.flymauntains

**Comment by Anddy-pug** [comment]
Thank for article. When I deploy my app with firebase same error is appeared.
Your solution is very impact.

**Comment by davidshaffer0310** [comment]
Thanks for article. Your article is good.

**Comment by Angular-ssr-accessible** [comment]
> I could re-deploy it to allow you to test it.





https://nodejser.space/questions/setting-up-firebase-hosting-to-support-pug-files-instead-of-html-files
