### ISSUE TITLE
Deploy Firestore rules with a file size above 65.511 bytes fails

### ISSUE THREAD

**Issue by basvandenheuvel** [firebase/firebase-tools#1339]
### [REQUIRED] Environment info

**firebase-tools:** 6.10.0 (Also tested with 6.7.1)
**Platform:** Windows 10

### [REQUIRED] Test case

Working test file (remove .txt): [firestore.rules.txt](https://github.com/firebase/firebase-tools/files/3223846/firestore.rules.txt)
Not working test file (remove .txt): [firestore.rules.txt](https://github.com/firebase/firebase-tools/files/3223849/firestore.rules.txt)

### [REQUIRED] Steps to reproduce
- Create a Firestore rules file with a file size of 65.512 bytes.
- Deploy the firestore rules using the following command `firebase deploy --only firestore:rules`.

- Remove one character so the file size is 65.511 bytes.
- Deploy the firestore rules using the following command `firebase deploy --only firestore:rules`.

### [REQUIRED] Expected behavior
That the rules would also deploy if the file size is equal to or above 65.512 bytes

### [REQUIRED] Actual behavior
If the file size is 65.512 bytes or above the following error is returned:
`Error: HTTP Error: 400, Request contains an invalid argument`.

**Comment by samtstern** [comment]
@basvandenheuvel thanks for the bug report!  Sounds like an obvious bug, and we'll look into it.  Also sorry about @google-oss-bot not sure what went wrong but you definitely provided enough info (it [thinks](https://ossbot.computer/audit.html?org=firebase&repo=firebase-tools&key=-LftMmPBrY8VqCdhnIJO) you missed the test case section).

Also ... wow 65kB is a lot of rules!  Are you writing all these by hand or generating them?

**Comment by samtstern** [comment]
Re the google-oss-bot: nevermind, I can see now that you edited the issue body and the original post was missing that section but then you filled it in.  Thanks for all the info!

**Comment by basvandenheuvel** [comment]
@samtstern thanks for the quick response.

The file does contain some comments and empty lines. By uglifying it ourself, we could decrease the size a bit.

Yes, we did create them all by hand. Any tips to make this easier?

**Comment by samtstern** [comment]
@basvandenheuvel I am very curious about your rules, would you email them to me personally so I can take a look?  Email address is on my GitHub profile.  I think your rules are the largest hand-written ruleset I have ever heard of!

**Comment by ryanpbrewster** [comment]
There is a limit of 64 KiB on the size of the ruleset source. We're looking at raising this limit.

This limit is on the raw source, so minifying it yourself is one workaround.

**Comment by mbleigh** [comment]
Since this is a limitation of the backend and not the CLI, I'm closing this issue. Please [file a feature request](https://firebase.google.com/support) for higher limit rules sources so we can track internally :smile_cat:

**Comment by samtstern** [comment]
@basvandenheuvel I'd still love to talk about how you're using Rules if you're open to it!

**Comment by brianneisler** [comment]
@samtstern @mbleigh I recently reached this limit as well. The error that the cli gives is very unobvious simply stating `Request contains an invalid argument` and it took me quite a while to realize I had reached the maximum limit of 64KB. Would be great if that error was a bit more obvious as it would have saved me a bunch of time.

After doing a bunch of searching around solutions to the 64KB limit and not finding anything I contacted support. Their guidance was somewhat helpful but in other cases a bit shocking. 

I'm adding these details here for anyone else that is struggling with this issue as not much else comes up when searching on Google.

Here was their response
```
The given limit on the ruleset size is fixed, and it cannot be increased. However, we do offer ways to reduce the size of your ruleset, or 'lines of code' in particular. 

Here are some suggestions:
1) You can define your custom functions, which can be reusable throughout the ruleset
- This will definitely save you a lot of data space, and makes it look organized, as overused conditions can be called in one place

2) If possible, reconsider the database structure by making it efficient
- This means the less the number of collections and subcollections, the less rules are written, which makes the ruleset smaller in size
- Refactor your database structure and security rules as much as possible by removing unnecessary or redundant parts

3) Minimize the use of data validation rules, and put it on application-level instead
- Not only it can reduce lines of code, but it can reduce the number of expressions evaluated to avoid reaching the given limit of 1000 expressions per request
- As much as possible, use your app logic to ensure your data is on the right character length, correct data type, meets the patter criteria, etc. You may also use your app's advanced UI elements like a password textbox, a textbox that you can limit the character length, among others
```

Some of these suggestions such as using functions are definitely helpful. However, i'm a bit surprised by the suggestions to restructure my database and to put validation on the application level.

- In my case i've already used functions quite a lot in my database rules and have removed most of the redundancy.
- Asking me to reconsider the database structure and having to overhaul my application for the sake of reducing my rules file size is a huge ask for little gain.
- Minimize the use of data validation rules seems completely against the design of the Firestore database. The database is designed in such a way that you can directly connect your client to your database which removes the middle application logic. Suggesting to do this seems to go directly against the architectural nature of Firebase. I would prefer to keep building my application in this way (and want to maintain my security), so this seems like a non-option.

Technically, this problem is not too dissimilar from trying to keep javascript file size down on the web. A lot of the same approaches taken by javascript minifiers can be used to reduce the size of the firebase rules file. It would be great if Firebase provided a tool like this for us. 

Out of desperation I made a simple minifier that removes whitespace and comments. In case anyone else finds themselves in a similar situation and needs a quick fix. https://github.com/brianneisler/firemin

**Comment by samtstern** [comment]
@brianneisler thank you for sharing.  I agree that options (2) and (3) from support are technically correct but very extreme ways to get around a backend limitation.  I'll mention this to them and see if they want to change the recommendations.

Also thanks for sharing your minifier!  I'd love to list that on firebaseopensource.com if you're cool with that.

**Comment by brianneisler** [comment]
@samtstern thanks for getting back to me! Appreciate the response and the attention to the issue.

Totally fine by me if you'd like to add firemin to firebaseopensource.com
