### ISSUE TITLE
firebase targets

### ISSUE THREAD

**Issue by wilbrone** [firebase/firebase-tools#1388]
my page is blank even though my fav icon is loaded.
here is my firebase.json...

{
	"hosting": {
		"public": "src",
		"rewrites": [
			{
				"source": "",
				"destination": "/index.html"
			}
		]
	}
}

Anyone help please

**Comment by bkendall** [comment]
I'm not sure what `source: ""` would do, but since it's nothing, it probably won't match much. Maybe remove that (or if it's a single page application, `source: "**"` is probably appropriate...)

A lot more information is necessary, most of which is specified by the template for bug reports. Please open a new issue and follow the appropriate template.
