### ISSUE TITLE
Flutter Web prod build doesn't work on firebase hosting

### ISSUE THREAD

**Issue by AlexVegner** [firebase/firebase-tools#1394]
### [REQUIRED] Environment info

**firebase-tools:**
v7.0.0

**Platform:**
macOS 10.14.4

### [REQUIRED] Test case
Flutter Web prod build doesn't work on firebase hosting

### [REQUIRED] Steps to reproduce
1. clone Flutter Web hello_world https://github.com/flutter/flutter_web/tree/master/examples/hello_world
2. build prow with `webdev build`
3. init firebase project with hosting only
4. Copy hello_world/build/* to fitebase/public/
5. Deploy hosting to firebase
6. Open https://<app>.firebaseapp.com/#/

### [REQUIRED] Expected behavior
Browser should show Hello world page 

### [REQUIRED] Actual behavior
Browser show blank page

**Comment by bkendall** [comment]
I went through these processes and was able to successfully deploy the `hello_world` example to my project (after installing flutter, dart, etc).

Can you provide your `firebase.json` file (to check any settings there) and maybe run the deploy again with the `--debug` flag and provide that output?

**Comment by AlexVegner** [comment]
Hi @bkendall,
I have prepared test project for you. 
https://github.com/AlexVegner/firebaseTest

**Prerequisites**

Make sure that you work with flutter beta chanel: 
`bash setup.bash`
https://github.com/AlexVegner/firebaseTest/blob/master/setup.bash

Init firebase with your project
`cd firebase && firebase init`

*Deploy script*
`bash deploy.bash`

My results: 
Firebase doesn't work: 
https://test-alex-cb960.firebaseapp.com/#/

Github pages works fine: 
https://alexvegner.github.io/firebaseTestWeb/#/

See firebase tool log: 
https://github.com/AlexVegner/firebaseTest/blob/master/firebase/firebase-debug.log

**Comment by bkendall** [comment]
Flutter isn't the issue here. In `firebase.json` it's set up to [redirect everything to `/index.html`](https://github.com/AlexVegner/firebaseTest/blob/master/firebase/firebase.json#L9-L14). When I just run `firebase emulators:start --only hosting`, I get an empty page because (as is clear in the browser developer tools), the `.json` asset that it tries to load is actually html:

![image](https://user-images.githubusercontent.com/160236/59521280-cb57d580-8e80-11e9-89f0-50a2c2f3bd4a.png)

Which causes a javascript error:

![image](https://user-images.githubusercontent.com/160236/59521307-dad71e80-8e80-11e9-8c4e-ddb98425e802.png)

Once I removed the `rewrites` block from `firebase.json`, everything worked as expected.

![image](https://user-images.githubusercontent.com/160236/59521383-ffcb9180-8e80-11e9-84f1-73692efe15ce.png)

Since this isn't a `firebase-tools` bug, I'm going to close this issue. But let us know if you have any questions! Hope this gets you unblocked!

**Comment by AlexVegner** [comment]
Hi @bkendall, 
It works for me.

**Comment by AbhijeetDash** [comment]
Hi @bkendall,
can you plz explain me what actually happens when we rewrite all the URLs to index.html

**Comment by bkendall** [comment]
@AbhijeetDash See https://stackoverflow.com/questions/37667626/firebase-cli-configure-as-a-single-page-app-rewrite-all-urls-to-index-html

**Comment by IngMarFlo** [comment]
@AlexVegner can u help me ?? i follow your instructions (using .bash files) with a new flutter web app and i obtain a blank page https://linajevanguardistas-2018.firebaseapp.com/#/

**Comment by AbhijeetDash** [comment]
@IngMarFlo you can read this article..  
[](https://medium.com/@abhijeetdash1999/flutter-web-with-firebase-hosting-82c341989b37)

**Comment by AbhijeetDash** [comment]
https://medium.com/@abhijeetdash1999/flutter-web-with-firebase-hosting-82c341989b37

**Comment by IngMarFlo** [comment]
@AbhijeetDash Thanks a lot, its work !!
