### ISSUE TITLE
firebase tools update does not correctly check installation version after the update has run

### ISSUE THREAD

**Issue by peterennis** [firebase/firebase-tools#1408]
### [REQUIRED] Environment info

**firebase-tools:**

![Capture575](https://user-images.githubusercontent.com/140737/59620930-ede92900-90e2-11e9-9a3d-cda9c5d04801.png)

The update has been successfully run but the prompt still appears after
showing the latest version.

Run a second time and it shows the newest version only.

**Platform:**

Windows 10 1809

### [REQUIRED] Test case

See above

### [REQUIRED] Steps to reproduce

See above

### [REQUIRED] Expected behavior

Prompt to install new version is not needed once the new version is installed

### [REQUIRED] Actual behavior

See above

**Comment by bkendall** [comment]
Did this come up immediately after you upgraded `firebase-tools`?

I think this is a side-effect of how `update-notifier` works: it does its check more-or-less in the background which means there's a chance that it did work on a previous run of `firebase` that it needed to print the message, and when `firebase` was run again, even after the upgrade, it printed the message (before making any more checks).

If there are other folks who see this happen more and it becomes wide-spread, I'll take a look into the logic a little more closely, but otherwise I think this is pretty much as-intended.

**Comment by peterennis** [comment]
@bkendall 
Yes, it came up immediately after upgrading.
I have seen it on other version upgrades also.

**Comment by bkendall** [comment]
Yeah, I figured.

I'll leave this open as a small-ish feature request. Basically, I think we could be _slightly_ smarter around the `update-notifier` logic. To replicate it reliably, the cache that `update-notifier` will have to be cleared/populated at the right time, something like:

1. Clear the `update-notifier` cache (I _think_ it lives in the home directory somewhere - would have to dig)
1. Start with a clean, global install of `firebase-tools@6.12.0`
1. Run `firebase --version` to trigger `update-notifier`'s logic once (should not see an "update" message)
1. Upgrade to `firebase-tools@7`
1. Run `firebase --version` to trigger `update-notifier` again ("update" message should appear saying `6 -> 7`)

**Comment by peterennis** [comment]
@bkendall 

Latest version:

![Capture626](https://user-images.githubusercontent.com/140737/61164356-3bca3480-a4c9-11e9-956f-5e03dd009e94.png)

Looks like it was fixed but where?

**Comment by bkendall** [comment]
I'm doing a bit of bug cleanup and am back to this...

I don't think this is worth fixing. If update-notifier had a clean fix for this, I'd say go for it, but otherwise I don't think this is something worth tackling. even `npm` has this "problem" (I just hit it the other week). If someone _really_ wants to try and figure it out, happy to review, but otherwise this isn't preventing the CLI from being used. Thanks for flagging though!
