### ISSUE TITLE
Firestore Emulator stops working after invalid request

### ISSUE THREAD

**Issue by sgammon** [firebase/firebase-tools#1441]
### [REQUIRED] Environment info

**firebase-tools:** `6.10.0`

**Platform:** `macOS 10.14.5`

### [REQUIRED] Test case
Working on this.

### [REQUIRED] Steps to reproduce
1) Start up a Firestore Emulator
2) Try to store a document under a collection via the Java adapter, with a missing collection ID

### [REQUIRED] Expected behavior
1) Firestore Emulator should reject the request
2) Firestore Emulator should continue executing

### [REQUIRED] Actual behavior
1) Firestore Emulator does correctly reject the request, even with a helpful error message pinpointing the issue
2) However, all subsequent requests to Firestore Emulator produce `operation failed: null`

This is a rather strange one, because it doesn't actually crash. Here's the log I get:
```
Starting Firestore emulator...
Firestore emulator started at PID 26723...
Executing: /Users/.../cloud-firestore-emulator/cloud_firestore_emulator start --host=127.0.0.1 --port=8800 --rules=./config/db/firestore.sandbox.rules
[firestore] API endpoint: http://127.0.0.1:8800
[firestore] If you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:
[firestore] 
[firestore]    export FIRESTORE_EMULATOR_HOST=127.0.0.1:8800
[firestore] 
[firestore] Dev App Server is now running.
[firestore] 
[firestore] Jun 25, 2019 9:37:46 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[firestore] INFO: Detected HTTP/2 connection.
[firestore] Jun 25, 2019 9:37:48 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
[firestore] INFO: operation failed: Resource name "projects/bloom-db/databases/(default)/documents//B5CE7C22A4212AC015F65AA3C219047F827EC006" lacks a collection id at index 48.
[firestore] Jun 25, 2019 9:37:48 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
[firestore] INFO: operation failed: null
[firestore] Jun 25, 2019 9:37:48 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
[firestore] INFO: operation failed: null
[firestore] Jun 25, 2019 9:37:48 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
[firestore] INFO: operation failed: null
[firestore] Jun 25, 2019 9:37:48 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
[firestore] INFO: operation failed: null
[firestore] Jun 25, 2019 9:37:48 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
[firestore] INFO: operation failed: null
[firestore] Jun 25, 2019 9:37:48 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
[firestore] INFO: operation failed: null

[... a lot more...]
```

**Comment by ryanpbrewster** [comment]
Does this happen with previous versions of the Firestore emulator?

I'm working on a repro of the other issue you filed. How are you connecting the Java SDK to the Firestore emulator?

**Comment by sgammon** [comment]
i tried to `gcloud components update`, which is how the Firestore Emulator is installed on my machine. honestly, this particular issue isn't a huge deal for us, because of course the original request was invalid and is now fixed.

the version of the Firestore client we're using is (via Gradle):
```groovy
  compile group: 'com.google.cloud', name: 'google-cloud-firestore', version: '1.6.0'
```

we specifically use this dependency instead of the packaged one in Firebase Admin, i think because of an incompatibility we encountered with Protobuf (in case this is relevant, likely not):
```
    compile(group: 'com.google.firebase', name: 'firebase-admin', version: '6.8.1') {
        exclude(module: 'gson')
        exclude(module: 'google-cloud-storage')
        exclude(module: 'google-cloud-firestore')
    }
```

here is the code we use to initialize Firestore:
```java
  /**
   * Retrieve options used to configure Firestore. These options specify things like the active host, which is
   * sometimes overridden during tests, to point at a local Firestore emulator.
   *
   * @return Firestore options.
   */
  public static @Provides FirestoreOptions getFirestoreOptions() {
    final FirestoreOptions.Builder opts = FirestoreOptions.newBuilder();
    opts.setDatabaseId(getFirestoreDatabase());
    opts.setProjectId(Firebase.Settings.dbProject);

    // handle emulator settings
    if (System.getenv() != null ||
        System.getProperty(EMULATOR_FLAG) != null) {

      // override target with emulator host
      final String envValue = System.getenv(EMULATOR_FLAG);
      final String propValue = System.getProperty(EMULATOR_FLAG);

      final String hostPortPair = envValue == null ? propValue : envValue;

      if (hostPortPair != null) {
        logging.info("!!! EMULATOR IS ACTIVE: Firestore !!!");
        final Iterator<String> splitHostPort = Splitter.on(":").split(hostPortPair).iterator();

        // extract the first portion to get the host
        final String hostString = splitHostPort.next();
        final String portString = splitHostPort.next();
        final int port = Integer.parseInt(portString, 10);
        if (port > 65535 || port < 1024) throw new IllegalStateException("Invalid emulator port: " + port);
        opts.setHost(hostString + ":" + port);

        @SuppressWarnings("Convert2MethodRef")
        final InstantiatingGrpcChannelProvider.Builder channelProviderBuilder = InstantiatingGrpcChannelProvider
          .newBuilder()
          .setEndpoint(hostPortPair)
          .setChannelConfigurator(managedChannelBuilder -> managedChannelBuilder.usePlaintext());

        final Map<String, List<String>> headerMap = new HashMap<>(1);
        headerMap.put(AUTHORIZATION_HEADER_NAME, Collections.singletonList("Bearer owner"));

        final Credentials fakeCreds = new Credentials() {
          @Override
          public String getAuthenticationType() {
            return null;
          }

          @Override
          public Map<String, List<String>> getRequestMetadata(URI uri) {
            return headerMap;
          }

          @Override
          public boolean hasRequestMetadata() {
            return true;
          }

          @Override
          public boolean hasRequestMetadataOnly() {
            return true;
          }

          @Override
          public void refresh() {
            // no-op
          }
        };

        final TransportChannelProvider channelProvider = channelProviderBuilder.build();
        final CredentialsProvider credentialsProvider = FixedCredentialsProvider.create(fakeCreds);

        opts.setChannelProvider(channelProvider);
        opts.setCredentials(fakeCreds);
        opts.setCredentialsProvider(credentialsProvider);
        return opts.build();
      }
    }

    // production service route
    final String prodFlagEnv = System.getenv(PRODUCTION_FLAG);
    final String prodFlagProp = System.getProperty(PRODUCTION_FLAG);

    if ("1".equals(prodFlagEnv) || "1".equals(prodFlagProp)) {
      logging.info("Using production Firestore...");
    } else {
      logging.error("Selected production for Firestore, but found no production gate access.");
      throw new IllegalStateException("UNGATED_PRODUCTION_ACCESS");
    }

    // TODO managed channel for production Firestore
    return opts.build();
  }
```

hope the above helps.

**Comment by ryanpbrewster** [comment]
I cannot reproduce this one either (even with `firebase-tools` v6.10.0 and `google-cloud-firestore` v1.6.0). Here's the code I'm running:
```
  def main(args: Array[String]): Unit = {
    val db = FirestoreOptions.newBuilder()
      .setProjectId("foo")
      .setChannelProvider(
        InstantiatingGrpcChannelProvider.newBuilder()
          .setEndpoint("localhost:8080")
          .setChannelConfigurator(input => input.usePlaintext())
          .build())
      .build()
      .getService

    def write(name: String): Unit = {
      try {
        println(db.document(name).set(ImmutableMap.of("foo", 42)).get().getUpdateTime);
      } catch {
        case e: Exception =>
          println(e.getMessage)
      }
    }

    write("/z")
    write("a/b")
    write("c/d")
  }
```

and it's printing

```
com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Document name "projects/foo/databases/(default)/documents//z" lacks a collection id at index 43.
2019-06-26T09:04:55.363000000Z
2019-06-26T09:04:55.422000000Z
```

Definitely seems like some kind of issue, based on the logs you've provided. Would you mind constructing a reproduction of the issue I could run?

**Comment by pschneider** [comment]
Hi, just found this via Google Search.

I'm not sure if this is related to even using the emulator in any way as this happens for us already on startup.

We've recently started setting up the CI environment to test our Rules in a docker environment and we've seen (more or less random) failures of the tests due to an issue which looks exactly like the same mentioned above.

The firebase-tools & emulator are setup on building of the Docker image. I've tried 6.12.0 and newer so far.

Dockerfile:
```
RUN npm i firebase-tools@7.0.2 -g
RUN firebase setup:emulators:firestore
```

Test process which is run inside the container:
```
firebase use default --token OUR_CI_AUTH_TOKEN


firebase emulators:exec --only firestore 'npm run test --prefix ../firestore/ && curl -o ../firestore/output/coverage.json http://localhost:8080/emulator/v1/projects/XXXXX:ruleCoverage && curl -o ../firestore/output/coverage.html http://localhost:1234/emulator/v1/projects/XXXXX:ruleCoverage.html' --token OUR_CI_AUTH_TOKEN
```


<details>
<summary>firestore-debug.log</summary>
API endpoint: http://localhost:1234
If you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:

   export FIRESTORE_EMULATOR_HOST=localhost:1234

Dev App Server is now running.

Jul 06, 2019 9:24:04 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected HTTP/2 connection.
Jul 06, 2019 9:24:08 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L12, false for 'update' @ L393
Jul 06, 2019 9:24:08 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L12, false for 'update' @ L393
Jul 06, 2019 9:24:08 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L12, false for 'create' @ L393
Jul 06, 2019 9:24:08 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L12, false for 'create' @ L393
Jul 06, 2019 9:24:08 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'delete' @ L62, false for 'delete' @ L393
Jul 06, 2019 9:24:08 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'delete' @ L62, false for 'delete' @ L393
Jul 06, 2019 9:24:09 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected HTTP/2 connection.
Jul 06, 2019 9:24:09 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L58, false for 'update' @ L393
Jul 06, 2019 9:24:09 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
Null value error. for 'update' @ L58, false for 'update' @ L393
Jul 06, 2019 9:24:10 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L57, false for 'create' @ L393
Jul 06, 2019 9:24:10 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
Null value error. for 'create' @ L57, false for 'create' @ L393
Jul 06, 2019 9:24:10 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'delete' @ L302, false for 'delete' @ L393
Jul 06, 2019 9:24:10 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'delete' @ L302, false for 'delete' @ L393
Jul 06, 2019 9:24:10 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'delete' @ L302, false for 'delete' @ L393
Jul 06, 2019 9:24:11 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L302, false for 'update' @ L393
Jul 06, 2019 9:24:11 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L302, false for 'update' @ L393
Jul 06, 2019 9:24:11 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L302, false for 'update' @ L393
Jul 06, 2019 9:24:12 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L302, false for 'create' @ L393
Jul 06, 2019 9:24:12 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L302, false for 'create' @ L393
Jul 06, 2019 9:24:12 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L302, false for 'create' @ L393
Jul 06, 2019 9:24:13 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'delete' @ L312, false for 'delete' @ L393
Jul 06, 2019 9:24:13 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
Null value error. for 'delete' @ L312, false for 'delete' @ L393
Jul 06, 2019 9:24:14 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L309, false for 'update' @ L393
Jul 06, 2019 9:24:14 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L309, false for 'update' @ L393
Jul 06, 2019 9:24:14 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L309, false for 'update' @ L393
Jul 06, 2019 9:24:14 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L309, false for 'update' @ L393
Jul 06, 2019 9:24:14 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
Null value error. for 'update' @ L309, false for 'update' @ L393
Jul 06, 2019 9:24:14 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L309, false for 'create' @ L393
Jul 06, 2019 9:24:15 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L309, false for 'create' @ L393
Jul 06, 2019 9:24:15 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L309, false for 'create' @ L393
Jul 06, 2019 9:24:15 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
Null value error. for 'create' @ L309, false for 'create' @ L393
Jul 06, 2019 9:24:15 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:15 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
Null value error. for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:15 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:15 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:16 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:16 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:16 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:16 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:16 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:16 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:16 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:17 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'delete' @ L75, false for 'delete' @ L393
Jul 06, 2019 9:24:17 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'delete' @ L75, false for 'delete' @ L393
Jul 06, 2019 9:24:17 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'delete' @ L75, false for 'delete' @ L393
Jul 06, 2019 9:24:17 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:17 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:17 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
Null value error. for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:18 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L72, false for 'update' @ L393
Jul 06, 2019 9:24:20 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L68, false for 'create' @ L393
Jul 06, 2019 9:24:20 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L68, false for 'create' @ L393
Jul 06, 2019 9:24:20 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L68, false for 'create' @ L393
Jul 06, 2019 9:24:20 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L68, false for 'create' @ L393
Jul 06, 2019 9:24:20 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L393
Jul 06, 2019 9:24:20 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L393
Jul 06, 2019 9:24:20 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L393
Jul 06, 2019 9:24:20 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L393
Jul 06, 2019 9:24:20 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'delete' @ L393
Jul 06, 2019 9:24:20 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'delete' @ L393
Jul 06, 2019 9:24:21 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
Null value error. for 'delete' @ L40, Null value error. for 'delete' @ L45, false for 'delete' @ L393
Jul 06, 2019 9:24:22 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L45, false for 'update' @ L393
Jul 06, 2019 9:24:22 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'update' @ L45, false for 'update' @ L393
Jul 06, 2019 9:24:23 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L45, false for 'create' @ L393
Jul 06, 2019 9:24:23 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'create' @ L45, false for 'create' @ L393
Jul 06, 2019 9:24:23 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
Null value error. for 'create' @ L45, false for 'create' @ L393
Jul 06, 2019 9:24:24 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
false for 'delete' @ L28, Null value error. for 'delete' @ L31, false for 'delete' @ L393
Jul 06, 2019 9:24:24 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError

[....]

Jul 06, 2019 9:24:28 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
Null value error. for 'create' @ L17, false for 'create' @ L393
*** shutting down gRPC server since JVM is shutting down
*** server shut down
</details>


But, as i've mentioned, this happens not every time.

I could not yet reproduce it by starting the emulator like `nohup java -jar ~/.cache/firebase/emulators/cloud-firestore-emulator-v1.5.0.jar > test.log 2>&1 &` (which is by the way anyway nicer as it does not require any auth / project selection hassle just for CI runs...)

**Comment by sgammon** [comment]
@google-oss-bot, @pschneider added some stuff

**Comment by ryanpbrewster** [comment]
Can you provide a way to reproduce this issue?

The snippet I provided in https://github.com/firebase/firebase-tools/issues/1441#issuecomment-505789999 seems like it works correctly. It is difficult for me to identify what's going wrong based on your logs (they look valid, like the emulator is rejecting requests because the rules are invalid).
