### ISSUE TITLE
Deploy a new version and don't promote it?

### ISSUE THREAD

**Issue by archelogos** [firebase/firebase-tools#151]
Hi there!

Is there any option to deploy a new version of an app but don't config it to receive all traffic once deployed?
Or in other words, are different versions of an app available like in GCP?

I've looking for this, but I haven't found anything in the docu

Thanks a lot!
S

**Comment by mbleigh** [comment]
This isn't something that's possible right now, but is an interesting idea. Because Firebase Hosting leverages a CDN to maximize performance, doing staged traffic rollouts is somewhat infeasible. However, we might consider making it possible to "stage" a release without actually making it go live for instances where you want to have a manual button to release a new version.
