### ISSUE TITLE
firebase serve question

### ISSUE THREAD

**Issue by lcarbonaro** [firebase/firebase-tools#1545]
This is more of a question than an issue. Is there a way to test functions locally, but still have them connect to the remote firestore database? Perhaps some option for `firebase serve` ?

**Comment by samtstern** [comment]
Do you want to receive events from production Firestore in your locally
served functions?  If so that's not possible.

If you want to write to production Firestore from locally triggered
functions (like an HTTP function) that's totally possible and is the
default if you run the functions emulator but not the firestore emulator.

**Comment by lcarbonaro** [comment]
Wow @samtstern , that was fast :-) Thank you. 
Yes. these are CRUD type functions that read/write records in my firestore database and which I would like to test before doing a `firebase deploy`.  So, if I may follow up, how does one run the functions emulator? Is it some option or parm I need to add to the `firebase serve` command? Thanks again.

**Comment by samtstern** [comment]
Just run "firebase emulators:start --only functions" and it should all work
as intended.

**Comment by lcarbonaro** [comment]
I will certainly try that. Thank you again.
