### ISSUE TITLE
If a file is imported from another directory the uploader gets confused

### ISSUE THREAD

**Issue by cryptobrains** [firebase/firebase-tools#1561]
How to reproduce:

Say that you have the following directory structure:

common-project/firebase-server-side
common-project/shared-libraries
common-project/client-side

index.ts in /firebase-server-side/functions/src imports a shared model definition:

import {definition} from '../../../shared-libraries/models.ts';

You initiate firebase deploy from /firebase-server-side/functions

The build process will not store index.js in lib/index.js as defined in package.json's `main` instead it will store it in

common-project/firebase-server-side/src/functions/lib/index.js

The uploader will then complain that index.js cannot be found with

**Error: functions/index.js does not exist, can't deploy Firebase Functions**

**Comment by kevinajian** [comment]
@cryptobrains, can you share a quick repro of your setup? What do your `firebase.json` and `package.json` files look like?

**Comment by cryptobrains** [comment]
I will only be able to follow up in about 2 weeks, off on vacations.

The compiler will draw the .ts from from the shared libraries and build it in the final project. The actual files themselves are not needed for upload purposes.

**Comment by joehan** [comment]
Hey all, this issue is quite old, so I'm going to close it.

To the actual issue: This is unfortunately something that we won't support due to the limitations of how functions are built. In short, when you deploy a function:
1 - firebase-tools zips up your functions directory and uploads it to Google Cloud Functions
2 - GCF uses Cloud Build to install your dependencies and build your functions code.

Because of this, you can't import things that don't live inside your functions directory, and we don't have plans to change that. If you need to maintain a directory structure like this, you'll need to treat code outside of your functions directory as a separate module, and either make it available through npm, or package it and copy it over to your functions folder.
