### ISSUE TITLE
Firestore Trigger - How to test properly on local ?

### ISSUE THREAD

**Issue by sdubrez** [firebase/firebase-tools#1585]
### [REQUIRED] Environment info

**firebase-tools:** 7.1.1

**Platform:** macOS

### [REQUIRED] Test case

```javascript
const functions = require("firebase-functions");
const admin = require("firebase-admin");
const serviceAccount = require("./serviceAccountKey.json");
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://projectId.firebaseio.com"
});
const firestore = admin.firestore();
firestore.settings({ timestampsInSnapshots: true });

exports.onCreateDocument = functions.firestore
  .document(`myCollection/{documentId}`)
  .onCreate(async (snap, context) => {
    console.log("BIP !");
  });
```

### [REQUIRED] Steps to reproduce

After launching `firebase functions:shell`, I can call the `onCreateDocument`.
Here is the result
```
⚠  Your requested "node" version "8" doesn't match your global version "10"
✔  functions: Emulator started at http://localhost:5000
i  functions: Loaded functions: onCreateDocument
firebase > onCreateDocument()
'Successfully invoked function.'
firebase > >  BIP !
```
### [REQUIRED] Expected behavior

I would like to test it the same way Firebase is going to execute it on production side.

### [REQUIRED] Actual behavior

Actually, I'm calling it without arguments which is not going to be the case on production.

I tried using a React app that add a document in Firestore but as expected, the local trigger is not fired. I'm pretty sure that if I deploy the trigger it will be fired but I would like to run the trigger on the local side using the emulator.

Unfortunately, documentation, stackoverflow or other issues of this repo didn't help...

Thanks in advance !

**Comment by samtstern** [comment]
@sdubrez great question!  You're actually just a little ahead of the game right now.  The `7.3.0` release of `firebase-tools` will include support for calling the Firestore Emulator from a web client (like your React app) which will allow you to test these trigger flows.

If you want to just test the cloud function part now (so that you can see real inputs), I would suggest making an HTTP function like this:

```js
// Your existing function
exports.onCreateDocument = functions.firestore
  .document(`myCollection/{documentId}`)
  .onCreate(async (snap, context) => {
    console.log("BIP !");
  });

// New function for testing
exports.testOnCreateDocument = functions.https.onRequest(async (req, res) => {
  await admin.firestore().collection('myCollection').add({
    hello: 'World!'
  });

  res.json({ status: 'ok' }):
});
```

Then if you run `firebase emulators:start` and send a request to the HTTP URL for `testOnCreateDocument` you will see that the HTTP function fires and then the Firestore function fires after.
