### ISSUE TITLE
Add warning to upgrade to `firebase-tools` in `firebase-cli`

### ISSUE THREAD

**Issue by davidcallanan** [firebase/firebase-tools#1607]
This is not really a feature request or a bug report.

I accidentally installed the old `firebase-cli` instead of `firebase-tools` from node package manager (npm).

When running `firebase` command I was asked to enter google login credentials into the terminal window (which seemed odd) and was then prompted that my version was outdated and that I need to upgrade to atleast v2 by running `npm i --upgrade firebase-cli`. This did not solve the problem.

The solution was to uninstall `firebase-cli` and instead install `firebase-tools`.

I suggest you add a warning to `firebase-cli` stating to install `firebase-tools` instead.

I was worried that this was a malicious package since I was prompted to enter login credentials in the terminal rather than from a browser. I believe this notice will prevent users from entering credentials in the terminal and therefore not be worried that their credentials were stolen.

**Comment by bkendall** [comment]
Pretty much the first thing I see when I do `npm i firebase-cli` is a warning that it's deprecated. It's unlikely that we'd do much more than that in the near future.

```
bkend-macbookpro2:~ » npm i firebase-cli
npm WARN deprecated firebase-cli@1.2.0: Deprecated. Please use firebase-tools instead.
```

**Comment by davidcallanan** [comment]
@bkendall Ah, I didn't realize that this warning appeared when installing. However running `npx firebase` a different warning is shown stating that I must upgrade to firebase-cli v2.0.0 or later. Maybe this warning can also be updated? Also, running `npx firebase` without installing firebase-tools will automatically install firebase-cli,,, maybe this can be changed too although I would guess this is a decision on npms part.

**Comment by bkendall** [comment]
Interesting - `npx firebase` does not work as expected, but `npx --package firebase-tools firebase` does. We recommend installing `firebase-tools` globally rather than using `npx`, which might explain why we really haven't seen this before. But, this sounds like some logic in `npx` would have to be dug into to figure out why it makes the choices it does, but that's not going to be straight forward.

I'll open a bug internally to take a look (b/139871655), but since we recommend using `npm i -g`, I'd stick to using that for now.
