### ISSUE TITLE
Deploy a symbolic link target

### ISSUE THREAD

**Issue by jokin** [firebase/firebase-tools#164]
currently, if I create a symbolic link to my build directory, "firebase deploy" does not found the directory. 
Error: Specified public directory does not exist, can't deploy hosting

But if I launch the site with "firebase serve" it actually works fine. 

Thanks

**Comment by drtriumph** [comment]
The error deploying was reported in #22 and is specifically an issue with our [fstream](https://github.com/npm/fstream/pull/16) dependency. Until that issue is resolved, there's not much we can do. I don't think it makes sense to prohibit `firebase serve` from working if you're using symbolic links, and that's the only thing I can think that would make the behavior consistent.

**Comment by gilbert** [comment]
The fix PR has been sitting for 6 years. Surely you can fork fstream to resolve the issue?

**Comment by bkendall** [comment]
We're not going to be forking `fstream`.

I was able to make a symlink to my `public` directory (`symlink -> public`) and change my `firebase.json` directory to be `symlink` and deploy successfully. If you're having trouble with this @gilbert , could you open a new issue with reproduction steps so we can take a closer look? Thanks.
