### ISSUE TITLE
Random build timeouts using `firebase deploy`

### ISSUE THREAD

**Issue by whaatt** [firebase/firebase-tools#1655]
I have a large project with many cloud functions, and lately an error has been popping up on random functions in my deploy: `Deployment error. Build failed: Build has timed out`.  Sometimes it says `Build error details not available` instead of the timeout.

This affects a small percentage of functions but is enough to be annoying (often requiring many redeploys).

### Triage

If I check Stackdriver logs for the build failure, I see an error message `INVALID_ARGUMENT` in all cases.

But I never used to get this before and the timeouts are not at all deterministic (when they occur OR for which functions they occur). If this is a GCP limit I'm running into, I'm not really sure which one it is.

Moreover, some days seem to have far fewer build timeouts than other days.

### Environment

The only things that have changed outside the code are package version bumps, including an upgrade from the Node 6 runtime to the Node 10 runtime, as well as a version bump to the latest `firebase` CLI (installed globally).

Also worth noting is that I do a large number of parallel deploys, but the errors occur even when only a handful of functions are being deployed concurrently.

Any ideas? Much appreciated!

**Comment by samtstern** [comment]
I've seen this before and I also believe it was correlated to Node
version.  Since it's an intermittent issue and it's definitely happening on
the back end I don't think there's anything we can do in the CLI to help.

Would you mind writing in to Firebase support about this issue?  Provide
the project ID and some timestamps of build failures.  You can link this
issue and tell them to cc me if you'd like.

**Comment by kledk** [comment]
Apparently the issue seems to be resolved today. My builds are passing again without timeouts.

**Comment by mattgstevens** [comment]
@whaatt agreed, this issue is about *(A)* cloud functions deployments (although I'm glad those experiencing hosting issues are happy again).

---

Small update from my side is that support received the ticket, I provided some additional information (timestamps of recent failed deploys, the logs from a failing `firebase deploy` with the `--debug` flag,  projectId's and region) and the ticket has been raised to the engineering team. 

Think its worth mentioning that the support rep said others have reported seeing "Deployment error. Build failed: Build has timed out"; if its a "big" enough / often breaking for other teams then hopefully it gets addressed sooner rather than later.

**Comment by whaatt** [comment]
Haven't gotten the original error in a while. If others are no longer experiencing the error, please feel free to close out this issue.

**Comment by mattgstevens** [comment]
back from vacation, apologies to post on this closed issue. 

want to confirm that our CI has not been failing for at least 2 weeks due to this deployment issue. onward!
