### ISSUE TITLE
Firestore delete should be implemented in TypeScript

### ISSUE THREAD

**Issue by DCtheTall** [firebase/firebase-tools#1754]
### [REQUIRED] Environment info

**firebase-tools:** 7.6.1

**Platform:** Any

### [REQUIRED] Test case

N/A

### [REQUIRED] Steps to reproduce

N/A

### [REQUIRED] Expected behavior

Firestore's delete script should be implemented in TypeScript like the rest of the scripts.

### [REQUIRED] Actual behavior

The script is implemented in ES5-style JavaScript.

**Comment by samtstern** [comment]
@DCtheTall we agree!  This feature (like many others) was implemented before we had support for TS in `firebase-tools` so we had to use JavaScript.  We decided not to proactively convert old scripts (because that's a good way to introduce unnecessary bugs) but we do plan to update them as needed over time.

If you're interested in sending a PR to convert this feature to TS we'd be happy to review it. For now I am going to close this issue as we have already decided not to do this work proactively.

**Comment by DCtheTall** [comment]
@samstern since the module is untested I would have reservations doing the conversion myself, would you be willing to accept a PR adding unit tests? That would probably be the best first step imho.

**Comment by samtstern** [comment]
@DCtheTall if you're interested in writing some tests, absolutely would accept that PR!

**Comment by bkendall** [comment]
Yes yes yes yes yes :)

If you write the PR, we will happily review. And do write new tests in TS - then there's only one thing to convert! 😄
