### ISSUE TITLE
Hosting proxy for Functions deployed outside of Firebase

### ISSUE THREAD

**Issue by dinvlad** [firebase/firebase-tools#1803]
### [REQUIRED] Environment info

**firebase-tools:** 1.17.3

**Platform:** macOS Mojave 10.14.6

### [REQUIRED] Test case

A minimal HTTP Cloud Function e.g.
```go
package p

import (
  "fmt"
  "net/http"
)

func HelloWorld(w http.ResponseWriter, r *http.Request) {
  fmt.Fprintf(w, "OK")
}
```
`firebase.json`:
```json
...
  "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      },
      {
        "source": "/HelloWorld",
        "function": "HelloWorld"
      }
    ],
```
### [REQUIRED] Steps to reproduce

1. Deploy the above Cloud Function with `go 1.11` runtime in `us-central1` region.
2. Deploy Hosting for Firebase in the same project:
```sh
firebase deploy --only hosting
```
3. Observe that `https://us-central1-<project-id>.cloudfunctions.net/HelloWorld` returns `OK` message.

### [REQUIRED] Expected behavior

When I visit `https://<project-id>.firebaseapp.com/HelloWorld`, I should see "OK" message.

### [REQUIRED] Actual behavior

I see a 404 page, which indicates that proxying isn't working as I'd expect.

Thanks!

**Comment by samtstern** [comment]
@Memeriaj should this work?  If not, is this something we could add or is it not feasible?

**Comment by Memeriaj** [comment]
So I think that this boils down to ordering.  Rewrites are tried in the order that they appear in the `firebase.json` file.  In this case we'll only ever use the first rewrite in your example because it will always match everything.  Which means that any request that comes into your Hosting Site should have the contents of your `/index.html` page displayed.  Because you are getting a 404 back I would expect that you haven't actually deployed an `index.html` file.  I believe that you just need to swap the order of your rewrites so that the more specific Function rewrite is checked before the general catchall.

If that doesn't work let me know back on here.

**Comment by dinvlad** [comment]
Perfect, that worked! Thanks a lot!
