### ISSUE TITLE
npm install error with node <8.13

### ISSUE THREAD

**Issue by Jony-Y** [firebase/firebase-tools#1821]
Issue with firebase install while working with node lower than 8.13

firebase-tools: 7.8.0
env: MacOs

Steps to reproduce:
1. install firebase-tools 7.8.0
2. set node version to 8.12
3. run npm install / yarn

expected: modules installed successfully
actual: 
![fire-base-error](https://user-images.githubusercontent.com/10330531/69221980-2e147200-0b81-11ea-9c29-099b0700c353.png)

The root cause is `firebase-tools > @google-cloud/pubsub > @google-gax > “@grpc/grpc-js” “0.6.9"`

there were no breaking changes done, nor did I upgrade firebase-tools lately.

**Comment by samtstern** [comment]
@Jony-Y thanks for telling us about this!  So as you said we now depend on `@google-cloud/pubsub` which has an `engines` requirement of `8.10.0` and that depends on `@grpc/grpc-js` which has an `engines` requirement of `8.13.0`.

When using `npm` this actually isn't an issue.  It will install the dependencies just fine and warn you about the difference.  When using `yarn` however it looks like the `engines-strict` flag is set to `true`.

So here are a few options for workarounds:

  * Use a later `8.x` node version.  I would recommend `8.15.0` since that is the version that Cloud Functions uses in the Node 8 runtime.
  * Use `yarn` with the `---ignore-engines` flag to install
  * Install the Firebase CLI as a stand-alone binary following the instructions on this page: https://firebase.google.com/docs/cli#install_the_firebase_cli
