### ISSUE TITLE
Standalone binary is very large at 102MB and lags on start up

### ISSUE THREAD

**Issue by leighmcculloch** [firebase/firebase-tools#1834]
### Environment info

**firebase-tools:** `7.8.1`

**Platform:** `Debian Buster` `Linux 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux`

### Test case

Install and use the standalone binary CLI, e.g.:

```
$ curl -Lo firebase https://firebase.tools/bin/linux/latest
$ chmod +x ./firebase
$ ls -lah ./firebase
$ ./firebase
```

### Steps to reproduce

See steps above.

### Expected behavior

Two expectations:
1. A single binary tool would be small and able to install quickly.
2. When using the tool it would respond quickly like most other CLI tools.

### Actual behavior

The tool took a while to download, and appears to be 102MB. This seems excessive for a standalone binary. It takes about 30s to download the binary on a fast connection, and downloading installing node v10 and then firebase-tools from npm takes only about 15s longer, so this benefit of using a standalone single binary release is lost.

There also seems to be lag when using the standalone binary. Running any command, even ones like `--version` pauses for ~2 seconds. This is what the output looks like with `--debug`.
```
$ firebase --debug --version
[2019-11-27T17:14:12.682Z] ----------------------------------------------------------------------
[2019-11-27T17:14:12.693Z] Command:       /home/leighmcculloch/local/bin/firebase /home/leighmcculloch/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/bin/firebase --debug --version
[2019-11-27T17:14:12.694Z] CLI Version:   7.8.1
[2019-11-27T17:14:12.694Z] Platform:      linux
[2019-11-27T17:14:12.694Z] Node Version:  v10.15.3
[2019-11-27T17:14:12.695Z] Time:          Wed Nov 27 2019 09:14:12 GMT-0800 (Pacific Standard Time)
[2019-11-27T17:14:12.695Z] ----------------------------------------------------------------------
[2019-11-27T17:14:12.695Z]
7.8.1
```

It's really great that Firebase is getting a single binary release which should make it much easier to use in some of my environments, but it's size specifically makes it inconvenient to pull into containers and other systems on-demand because it's such a slow install.

**Comment by samtstern** [comment]
@leighmcculloch thanks for the feedback!  Right now the standalone binary actually includes `node` inside of it.  So as you noted, the time is similar to downloading `node` and then `npm install firebase-tools`. 

The main advantage of the single binary is that you can use it without having to actually set up `node` on your system which can be a pain in some environments (Windows in particular).

I will kick this over to @abeisgoat to see if he has any short or medium term plans to reduce the size but as far as I know it's going to remain large for the foreseeable future.

**Comment by abeisgoat** [comment]
So, sadly, this is definitely in `WONTFIX` or `CANTFIX` category.

I agree the CLI bundle is big, but as @samtstern pointed out that's because we're bundling `node`, `npm`, and `firebase-tools` so it's exactly as big as those three things glued together. If we had started writing the CLI in golang or something back in 2013 they we'd be able to ship a smaller binary, but we didn't have that foresight so short of a full rewrite, this is as good as it's gonna get size-wise.

In theory we could do some optimizations to the bundle size, maybe do a post-build tree shaking or some crazy stuff, but it' just not worth it. It would be a lot of engineering time and very prone to introducing new bugs for shaving maybe like 20mb off. There may be other low-hanging fruit I'm missing, but it's not like it's gonna drop from 100mb to 10mb or something, *maybe* we'd drop to 50mb but 🤷‍♂ 

> It takes about 30s to download the binary on a fast connection, and downloading installing node v10 and then firebase-tools from npm takes only about 15s longer, so this benefit of using a standalone single binary release is lost.

Well if it takes 30s to use the standalone binary and 45s to install via the traditional route, then sounds like the benefit is saving 33% of the install time 😆 Joking aside, the value of these binaries is partially the hope that they're easy to pull into containers, but more importantly their value is simplicity. Even if it somehow took longer to physically download the standalone binary, they'd still have a ton of benefit to anyone who isn't a Node developer (like all our native Android and iOS Firebase devs). If we just said run `npm install -g firebase-tools` then a developer who had never heard of `npm` would definitely end up spending more time googling what `npm` is than they would have if we gave them one binary.

In terms of start-up time, the way the firepit (standalone) builds work is that on first run they extract like 20k JavaScript files into a temporary cache which represents a complete install of `firebase-tools` then we do some patch work to basically fake an `npm install` of that extracted package (because a real `npm install` is crazy slow and loves to try to make network calls even if you ask politely not to) so we expect the initial call to the standalone binary to take a couple seconds, then calls after that should be close-ish to a regular install. It wont be as fast as there's still more checking that has to be done (did we already do the extraction? is the firepit env set up right? etc) so yeah the moral is it's just slower. 

Again, there may be some low-hanging fruit here I'm missing, but we're making the best of a bad situation. Node just isn't a good tool for writing CLIs for non-node devs and firepit is a bandaid which gets us 80% of the value of having a standalone binary without the 2k hours of eng time it would take to rewrite the whole CLI.

So I guess the moral is, I hear you and I agree, but this is what we got, sorry.

**Comment by leighmcculloch** [comment]
All makes sense, thanks for the backstory. 

For the start-up time I'm seeing consistent 2s pause on first and subsequent runs. The first run doesn't seem to take longer than the subsequent runs. If this sounds like something you'd want to debug more I'm happy to run any commands or find any specific logs you might want if that's useful to understand.

Thanks for making the best of an imperfect situation, it's great to be able to install the CLI in my environments that don't have node already installed. It's much appreciated even if it doesn't tick all the boxes!

**Comment by abeisgoat** [comment]
Hmm okay, I'll dig a bit more into the start-up delay. There's probably a chance to optimize that a bit if you're seeing it after first run. There's a chance it's not detecting the existing cache and is re-extracting or something. I'll reach out if I have questions for you, thanks!
