### ISSUE TITLE
multiple typescript error when executing an ionic project

### ISSUE THREAD

**Issue by likeveen** [firebase/firebase-tools#1843]
### [REQUIRED] Environment info

**firebase-tools:7.8.1

**Platform: Ubuntu 18.04

i'm a beginner dev, i want to make a database with firebase for my ionic app.
when i look my app, no problem expected but when i launch this on localhost, I’m drowned in mistakes.
https://paste.ubuntu.com/p/VTZgJqDXtm/
paste of the error here

**Comment by bkendall** [comment]
What is your Typescript version? I've not seen these errors before, but my hunch would be that Typescript is out of date.

**Comment by likeveen** [comment]
I think this is version 2.6 because I use angular 5.0.0, I am obliged to use these versions because I code under ionic v3, I can not switch to the latest version of ionic because I can not find a course, I am learning ionic

**Comment by bkendall** [comment]
I'm really not sure what the issue is in your case, sorry. My best bet would be to update Typescript (which should be safe enough to do). I'd recommend asking on Stack Overflow as folks who may be using the same frameworks would be able to help you out.

Since this doesn't seem directly related to the CLI, I'm going to close this.
