### ISSUE TITLE
Unpublish `firebase-cli` module on NPM

### ISSUE THREAD

**Issue by gnerkus** [firebase/firebase-tools#187]
I've noticed the `firebase-cli` module is still being downloaded. Would it be necessary to unpublish it?

**Comment by jwngr** [comment]
Un-publishing a Node.js module is frowned upon in the community and could break existing users (look no further than the [`left-pad` incident](http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/) from a few months ago). We've already marked `firebase-cli` as deprecated so that when you install it, you get the following message:

```
$ npm i firebase-cli
npm WARN deprecated firebase-cli@1.2.0: Deprecated. Please use firebase-tools instead.
```

Also, looking at the stats, it doesn't look like it gets many downloads:

<img width="346" alt="screen shot 2016-07-22 at 12 12 16 pm" src="https://cloud.githubusercontent.com/assets/4149793/17068392/969c8406-5005-11e6-941a-19a940ad124d.png">

Especially when compared to the stats for `firebase-tools`:

<img width="347" alt="screen shot 2016-07-22 at 12 12 47 pm" src="https://cloud.githubusercontent.com/assets/4149793/17068411/a8866b46-5005-11e6-995b-f48c69df1d36.png">


I don't think we want or need to do anything else for the time being.
