### ISSUE TITLE
Error: HTTP Error: 400, Location must equal europe-west1 because the App Engine app that is associated with this project is located in europe-west1

### ISSUE THREAD

**Issue by mjep** [firebase/firebase-tools#1880]
### [REQUIRED] Environment info

Latest:
+ firebase-tools@7.11.0
updated 1 package in 11.916s

**firebase-tools:**

My CLI outputs this: 
matthew$ firebase --version
7.1.0

**Platform:**
macOS Mojave 10.14.5 

### [REQUIRED] Test case

About 5 days ago I started to have problems deploying functions to firebase. This is following a few weeks with an existing firebase project with no deploy problems. I started to get:

"HTTP Error: 400, Location must equal europe-west1 because the App Engine app that is associated with this project is located in europe-west1"

mid deploy in the CLI. I was aware that a colleague had created a function or two in the wrong region so I manually deleted the functions in the google cloud console and I visited all of our functions and added this to each:

functions.region('europe-west1')

this was to a db functions, and https and a pubsub. I also deleted the pubsub function from the google cloud console. Thus removing all previous references. Still upon deploying I get the same problem.  

Today I created a new firebase project in the multi-region, eur3 (europe-west). I tried again to deploy the same code to this new project I was prompted:

Error: HTTP Error: 400, Billing must be enabled for activation of service '[cloudscheduler.googleapis.com]' in project 'xxxxxxxx' to proceed.

I enabled billing account and then ran firebase deploy again and again get the same output. 

Error: HTTP Error: 400, Location must equal europe-west1 because the App Engine app that is associated with this project is located in europe-west1

### [REQUIRED] Steps to reproduce

Create a new firebase project in eur3 (europe-west)
Enable a billing account
Run firebase deploy using the typescript functions provided
Observe CLI error output

### [REQUIRED] Expected behavior

Functions should deploy (https, db and pubsub) and function without any issues showing in CLI
[src.zip](https://github.com/firebase/firebase-tools/files/4002101/src.zip)

### [REQUIRED] Actual behavior

console fails to deploy with the following error:

Error: HTTP Error: 400, Location must equal europe-west1 because the App Engine app that is associated with this project is located in europe-west1

**Comment by mjep** [comment]
info updated

**Comment by atereshkov** [comment]
Still unresolved even using firebase 7.8.2:

https://github.com/firebase/firebase-tools/issues/1500#issuecomment-586678769

**Comment by kmcnellis** [comment]
The error here is that the scheduled function needs to know where the GCP project location is set to in order to use cloud scheduler.  If it doesn't have a location set, then it defaults to us-central1.

Can you get the results of the getAdminSdkConfig API call on your project?  You can use the [API Explorer](https://firebase.google.com/docs/projects/api/reference/rest/v1beta1/projects/getAdminSdkConfig?apix_params=%7B%22name%22%3A%22projects%2Ffir-test%2FadminSdkConfig%22%7D), just replace fir-test with your project.

Also, please provide the full results of deploying your scheduled function with the `--debug` flag

**Comment by lucasdidur** [comment]
I'm having this problem too. I have create a new project im annother location and deploy the same sources to the new project.

In my project, location is "us-east1" but they try to deploy in "us-central1"

	14:58:49  ✔  functions: Finished running predeploy script.
	14:58:49  i  functions: ensuring necessary APIs are enabled...
	14:58:49  ✔  functions: all necessary APIs are enabled
	14:58:51  i  functions: preparing functions directory for uploading...
	14:59:01  i  functions: packaged functions (608.41 KB) for uploading
	14:59:02  ✔  functions: functions folder uploaded successfully
	14:59:03  i  functions: updating Node.js 8 function triggerCount(us-central1)...
	14:59:03  i  functions: updating Node.js 8 function webApi(us-central1)...
	14:59:03  i  scheduler: ensuring necessary APIs are enabled...
	14:59:03  i  pubsub: ensuring necessary APIs are enabled...
	14:59:05  ✔  pubsub: all necessary APIs are enabled
	14:59:05  ✔  scheduler: all necessary APIs are enabled
	14:59:06  
	14:59:06  Error: HTTP Error: 400, Location must equal us-east1 because the App Engine app that is associated with this project is located in us-east1

**Comment by sinapis** [comment]
Having the same problem. I called adminSdkConfig, and it seems the problem is that the locationId is missing. this is the response i get:

`{
  "projectId": "solid-scheme-272409",
  "databaseURL": "https://solid-scheme-272409.firebaseio.com",
  "storageBucket": "solid-scheme-272409.appspot.com"
}`

Is there a workaround for this issue?

**Comment by KevinDanikowski** [comment]
I'm having issues with this as well, despite setting 
```
exports.cronRemindNeverSignedInUsers = functions
  .region('us-east1')
  .pubsub.schedule('every day 00:00')
  .onRun(cronRemindNeverSignedInUsers)
```

Error:

```
[2021-05-25T00:31:58.841Z] >>> HTTP REQUEST GET https://cloudscheduler.googleapis.com/v1beta1/projects/my-project-dev/locations/us-central1/jobs/firebase-schedule-cronRemindNeverSignedInUsers-us-east1  
 
[2021-05-25T00:31:58.954Z] <<< HTTP RESPONSE 400 {"vary":"X-Origin, Referer, Origin,Accept-Encoding","content-type":"application/json; charset=UTF-8","date":"Tue, 25 May 2021 00:31:58 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[2021-05-25T00:31:58.954Z] <<< HTTP RESPONSE BODY {"error":{"code":400,"message":"Location must equal us-east1 because the App Engine app that is associated with this project is located in us-east1","status":"INVALID_ARGUMENT"}}
[2021-05-25T00:31:58.955Z] >>> HTTP REQUEST PATCH https://cloudscheduler.googleapis.com/v1beta1/projects/my-project-dev/locations/us-central1/jobs/firebase-schedule-cronRemindNeverSignedInUsers-us-east1 
```

**Comment by Realtimeknowledge** [comment]
In the end I think that I went to the google cloud console, instead of the firebase console and deleted all my cloud functions from there. This created a blank canvas upon which deploys through firebase then went OK. 

Pick your GCP/Firebase project and visit:
https://console.cloud.google.com/functions/list

Now when I have a problem with a functions deployment, I check in the GCP console. Clear down and try again if that seems the right approach.

Hope this helps.

**Comment by olliepotter** [comment]
I'm having this issue too, suggestion from @Realtimeknowledge did not work for me
