### ISSUE TITLE
Firebase database:set err

### ISSUE THREAD

**Issue by rkowalski1990** [firebase/firebase-tools#190]
Accualy there is no documentation about it. And a... It's still the same problem "error: missing required argument `path'", but it is. I was trying all possibilities, anyone can help me?

**Comment by pejas** [comment]
Same issue, when using --token error occurs:
```
firebase database:set '/config/test' --data '"test value"' --token '1/XXX'
? You are about to overwrite all data at https://undefined.firebaseio.com/config/test. Are you sure? Yes


Error: Firebase error. Please ensure that you spelled the name of your Firebase correctly
```

Works fine when logged in (firebase login first) instead of token. Specifying --project doesn't help (undefined in url).

Our use case (CI) requires to run with --token '1/XXX' --non-interactive --confirm

```
[debug] Command:      /usr/bin/node /usr/bin/firebase database:set /config/test --data "test value" --token 1/Zuvt0RzIeTq8VPBKNwDhQiZbRyET3VDDZn-c_5E1ZUo
[debug] CLI Version:  3.0.4
[debug] Platform:     linux
[debug] Node Version: v6.3.1
[debug] Time:         Mon Aug 01 2016 16:48:28 GMT+0200 (CEST)
```
 options.instance is undefined in commands/database-set.js:41

**Comment by abehaskins** [comment]
Hey folks, this may have been fixed, please re-open if you're still experiencing it!
