### ISSUE TITLE
Feature Request: Method for checking which user is logged in – without prompts

### ISSUE THREAD

**Issue by draperunner** [firebase/firebase-tools#1906]
Hi!

This is a technical feature request for the CLI.

I use Firebase with two different accounts, and I frequently switch between them. This means a lot of `firebase logout` and `firebase login`, and that's fine. But it is easy to forget this before I do a deploy. And when I forget this, I might have waited multiple minutes for my project to build, only for `firebase deploy` to fail because I'm logged in with the wrong user.

What I would like is something like `firebase login --check` which either 1) prints `Not logged in` if no user is logged in, or, 2) the email address of the logged in user. It should exit with a code > 0 if not logged in, 0 if logged in.

This would make me able to create a step in my build pipeline that checks that I'm logged in with the right user, and trigger an early exit if the wrong user is logged in. I could even extend it by creating a bash script that matches the logged in email with my company's domain, use regex, and so on.

The existing `firebase login` command does print the email of the logged-in user, but it will prompt the user and perform a login if not logged in. All in all, this is not very suitable for parsing/scripting.

Thanks for listening!

PS: I know GitHub is not the place for feature requests, as clearly stated in the Issue Template. I did submit this through the feature request form, but the response I got was that I should post this here instead... So if it's correct that feature requests for the CLI should be posted here, I'd suggest clarifying this in the issue template.

**Comment by samtstern** [comment]
@draperunner thanks for the feedback!  This type of FR is fine on GitHub since it's small and scoped just to the to CLI  (rather than being about Firebase in general).

As a short term workaround we sometimes use the `firebase projects:list` command as a basic sanity check for "Am I logged in?" although it does not print the email of the logged in user.

As an even hackier workaround you can examine `~/.config/configstore/firebase-tools.json` which contains the login state.  

For your build pipeline we actually recommend using a service account for authorization.  You can give it custom scopes through Cloud IAM and then use it to authorize via:
```
GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account.json firebase [some command]
```

Now that I've told you all that ... I still think this is a good suggestion for a new command.  What we need to do is:

a) Agree on an API
b) Take it through our internal API approval process
c) Implement it

**Comment by abeisgoat** [comment]
I'd like to just +1 this, we do a weird hack in the binary builds to check if the user is built in and if we just had a like `firebase user` command or something, it would make my life a little easier.

**Comment by bkendall** [comment]
An idea: would it be sufficient to fail out and not prompt if the environment is non-interactive or CI when `firebase login` is run without being logged in (having some form of credentials)?

**Comment by mbleigh** [comment]
If we can come up with a way to not add a flag but get the desired outcome of being able to detect logged in / logged out I'd be happy with that. Having `firebase login` be a no-op when logged in and return the currently logged in user while failing in non-interactive mode when logged out seems like it might work, yeah.l
