### ISSUE TITLE
Authentication Error in using firebase login

### ISSUE THREAD

**Issue by zhoutengshen** [firebase/firebase-tools#1910]
> The problem occurred using "firebase login" In China, I used a proxy;

the error like this:
![1578647583](https://user-images.githubusercontent.com/26021548/72140783-7c4d3100-33cc-11ea-9916-5d89be0acea5.png)

**Comment by samtstern** [comment]
@zhoutengshen it can be very hard to debug what's going wrong when using a proxy.  Could you rin the same failing command with `--debug` (`firebase --debug login --reauth --no-localhost`) and show the logs?  They might contain a hint.

**Comment by zhoutengshen** [comment]
> @zhoutengshen it can be very hard to debug what's going wrong when using a proxy. Could you rin the same failing command with `--debug` (`firebase --debug login --reauth --no-localhost`) and show the logs? They might contain a hint.

this is the error log:
![1578882510(1)](https://user-images.githubusercontent.com/26021548/72230361-be09f180-35ef-11ea-8582-e81ba6c044ea.png)

**Comment by samtstern** [comment]
@zhoutengshen it looks like your connection is timing out (`ETIMEDOUT`) which means there is some issue either with your proxy or your local configuration.

Since it won't be possible for us to debug this issue from here (California for most of us) there's really nothing we can do, and I can't give advice on how to get a better proxy/VPN.

Sorry for the slow response and I hope you get this resolved!
