### ISSUE TITLE
Deployed application uses wrong index.html file

### ISSUE THREAD

**Issue by ngEdmundas** [firebase/firebase-tools#2]
In our app the public directory specified in firebase.json contains several HTML files. The main is called "index.html", the others are "index-full.html" and "facebook-channel.html". After "firebase deploy" the "index-full.html" becomes the default index file and following URLs all load contents of the same file "index-full.html":
- https://name.firebaseapp.com/
- https://name.firebaseapp.com/index.html
- https://name.firebaseapp.com/index-full.html

If "index-full.html" was renamed to "index-full.html-off", then the correct "index.html" is picked up as the default index file.

**Comment by azucenareyes** [comment]
Hello, 
I cannot deploy my web app, well it says deployed but I don't see my app. I just see the standard index.html Welcome page. Do I need to create my own index.html page? I am using create-react-app.
Thank you

**Comment by bhimbolar** [comment]
@azucenareyes Check your firebase.json file Edit the line **"public": "public"** to **"public": "app"**, or any other directory where your app content resides. That will help you.

**Comment by MrAndrew7of9** [comment]
The problem is when firebase is creating the index file, it overwrites the one created by react. So what you have to do is run all the firebase code (minus deploy), then rerun 'npm run build' to get react to recreate the index file you need in the build directory, then change the `firebase.json`  "hosting" block's "public" key to "build". (Specifically for react, as that is the default dir for it.) Finally you can deploy it and all should be right. (Except for how much manual effort that takes.)

**Comment by bkwilcox100** [comment]
I have removed every mention of the auto-generated firebase index.html file from my project, ran 'npm run build' and then 'firebase deploy' and I still am seeing the auto-generated index file when I open the app URL. I don't know where it is getting this file from.
