### ISSUE TITLE
database:get returns null

### ISSUE THREAD

**Issue by johnnyasantoss** [firebase/firebase-tools#2075]
### [REQUIRED] Environment info

**firebase-tools:** 7.16.1

**Platform:** Ubuntu 18.04.4 (bionic) / Linux 5.3.0

### [REQUIRED] Test case

1. Create a new project on Firebase
2. Populate some data
3. Try to export everything (the root path `/`) using `firebase database:get / -P my-project > data.json`

### [REQUIRED] Steps to reproduce

Same as the previous section

### [REQUIRED] Expected behavior

To generate a json with the collections and docs

### [REQUIRED] Actual behavior

Returns: 
```log
null


```

**Comment by samtstern** [comment]
@johnnyasantoss since you mentioned "with the collections and docs" I assume you are using Cloud Firestore?  The `database:get` command is for the Realtime Database.  There is not equivalent command for Cloud Firestore at the moment because there is no `json` export format for Firestore documents.

There is a third-party (not official!) command line tool that may do what you're looking for though:
https://firebaseopensource.com/projects/sgarciac/fuego/
