### ISSUE TITLE
Firestore security rules will not compile if function(map) is called with map==null 

### ISSUE THREAD

**Issue by olivierkrener** [firebase/firebase-tools#2077]
### [REQUIRED] Environment info

**firebase-tools:** 7.16.1

**Platform:** Windows 10

### [REQUIRED] Test case

In some cases, calling a function that takes a Map as parameter with a null value will not compile in the online security rule and will prevent the deployment of the rules. Like for instance:

```
    function faulty(boolx, booly, map) {
      return (boolx && test(map)) || (booly && test(null));
    }
    function test(map) {
      return ...;
    }
```
The error thrown by the compiler being one of the two followings:

> Error saving rules - Line XXX: Invalid type. Received one of [null]. Expected one of [map].
> Error saving rules - An unknown error occurred

Despite all my efforts I cannot give an exact "minimal, complete, and verifiable example", and I did not succeed to identify exactly when each error above is raised. However the issue seems to be influenced by:
- The size of the security rule file, the bigger the more chances to get the error (mine is 45Ko)
- The presence of exists, get and getAfter around the function being called

I can provide 2 security rules files illustrating the issue
[rules_fixed.txt](https://github.com/firebase/firebase-tools/files/4396966/rules_fixed.txt)
[rules_issue.txt](https://github.com/firebase/firebase-tools/files/4396967/rules_issue.txt)

rules_issue.txt will not compile, whether rules_fixed.txt will, notice the only differences.

### [REQUIRED] Steps to reproduce

See above

### [REQUIRED] Expected behavior

This is working fine in the emulator, and null should be a valid value for a map, so the security rules should compile properly.

Note: why am I not using "rules_fixed.txt" if it is working? Well, due to [https://github.com/firebase/firebase-tools/issues/2067](url), this one is not working in the emualtor

### [REQUIRED] Actual behavior

Error is thrown

**Comment by scottcrossen** [comment]
I am sorry you are having such a bad experience and running into both this issue and the issue you mentioned.

*Caveat*: This repo is not for reporting the production services like Rules... It's typically just for issues related to the CLI (and perhaps the emulators). Normally, errors like this should be reported to https://firebase.google.com/support/troubleshooter/report/bugs

The type error is a "red herring" in this particular case because those don't prevent you from saving Rules (it's a warning not an error). The only error that matters is the unknown error which is because you're hitting a complexity limit that isn't well documented or exposed (thus why it's so hard to make a minimal verifiable example). I've spoken with the oncall for the service and we will most likely be deploying a fix on Monday during business hours PST. It will take a few days for it be fully rolled-out before this behavior will change for you. Thanks for your patience and congratulations on creating a ruleset that hits this edge case. It's very very rare.

P.S. I am kind-of lazy about monitoring GitHub/StackExchange issues. Usually I'm too busy unless someone from my team specifically asks me to look at one. In fact, the only issues I ever answered were authored by you. So to cut-out the middle man, and reduce response latency, please add me to the Assignee set or email me at scottcrossen@google.com whenever you have an issue. Please do not spend more than an 1-2 hours trying to figure something out. It's my belief that if an experienced Rules-developer like yourself can't figure it out then something needs to change to make the experience better for everyone.

**Comment by scottcrossen** [comment]
Closing because this issue doesn't belong in this repo and a fix is underway.

**Comment by olivierkrener** [comment]
Great to have a direct line to Firebase support :)

Just a comment that this issue also affects the CLI, as it is impossible to
deploy the rules. Using the command " firebase deploy --only
firestore:rules" will throw the error "Error: HTTP Error: 503, The service
is currently unavailable."

**Comment by olivierkrener** [comment]
Hi Scott,
Related to my last email, I have to deploy my rules manually ever since as
the CLI will throw the mentioned issue. I will raise an issue on github
Rgds
Olivier

**Comment by scottcrossen** [comment]
What do you mean "deploy your rules manually"? Deploying through the frontend console and the CLI are the same endpoint. If one doesn't work then they both probably don't work.

Are you still experiencing flaky submits? Are you still experiencing 503s? If so I think I can get that fixed.

**Comment by olivierkrener** [comment]
deploy manually = deploy through the frontend console, yes. This works, even if it triggers some error.

The CLI will just not deploy it and throw a 503

Note: I raised another issue for that one, https://github.com/firebase/firebase-tools/issues/2127

**Comment by scottcrossen** [comment]
Okay I'm going to try something that will hopefully fix this for you. You should try again on Friday or so. Have you tried deploying your rules to a new project yet? That will likely fix the issue but I know you probably have existing architecture so I'll slap some wrists to get the old one working too.

**Comment by olivierkrener** [comment]
Thanks! Do you mean there will be a new release by Friday?

**Comment by scottcrossen** [comment]
No. I'm adjusting something else within the serving architecture. It doesn't require a rollout!

**Comment by olivierkrener** [comment]
I just tested it and it worked :). Will let you know if I encounter the
issue again
