### ISSUE TITLE
[Tracking] Add import/export support to RTDB emulator

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#2079]
As a follow up to #1167 I am filing this FR for people who want to track the support for `--import` and `emulators:export` on the Realtime Database emulator.

**Comment by samtstern** [comment]
Internally this is http://b/149591624

**Comment by jQrgen** [comment]
Much needed! 

My local emulators are useless until this is complete because it uses config variables from the realtime database

**Comment by prescottprue** [comment]
+1.

@jQrgen you should be able to copy data into the RTDB emulator by using emulator environment variables along with firebase-tools database commands [as described in this comment](https://github.com/firebase/firebase-tools/issues/1957#issuecomment-611538120).

My team currently uses a script which leverages [firebase-tools-extra](https://github.com/prescottprue/firebase-tools-extra) to do this since we are also setting data to the Firestore emulator, but we are planning to switch the RTDB logic to use firebase-tools directly now that it supports emulator. If you are planning on leaving the emulators running instead of using exec you can use concurrently along with wait-on to run your seed command only after the emulator ports are open:

```
"db:seed": "bin/seed_db"
"emulators": "concurrently -n seeding,emulators -c cyan,green yarn:db:seed \"firebase emulators:start --import bin/emulatorData --only firestore,database\"",

```
With `bin/seed_db`:

```
export FIRESTORE_EMULATOR_HOST=localhost:8080
export FIREBASE_DATABASE_EMULATOR_HOST=localhost:9000
# Write File To RTDB
firebase database:update /users bin/data/users.json && echo "Set users"
# Write Data String
firebase database:update /users -d '{ "some": "data" }' && echo "Set user"

## Or use firebase-tools-extra if you need firestore support
# export GCLOUD_PROJECT=my-project
# Write JSON file to Firestore
# firebase-extra firestore:set /users/ABC123 bin/data/some_user.json && echo "Set user"
# Write Data String To Firestore
# firebase-extra firestore:set /users/ABC123 -d '{ "some": "data" }' && echo "Set user"
```

**Comment by samtstern** [comment]
@prescottprue thanks for sharing!  The main reason we need to add something more complex is that we want to enable loading data into the RTDB emulator without triggering any Cloud Functions.

**Comment by samtstern** [comment]
This has been added in #2429 and will be available in the next release.

**Comment by samtstern** [comment]
Version `8.5.0` of firebase-tools contains import/export support for RTDB!  Try it out and let us know how it's going!

**Comment by skwny** [comment]
@samtstern It works!
