### ISSUE TITLE
unable to deploy firebase functions 

### ISSUE THREAD

**Issue by utpaulBS23** [firebase/firebase-tools#2102]
I want to deploy firebase functions in firebase console  from my laptop. But always give me 
`functions: Upload Error: Server Error. read ETIMEDOUT`

Screenshoot: 
![Uploading Screen Shot 2020-04-05 at 11.02.48 PM.png…]()

**Comment by samtstern** [comment]
@utpaulBS23 please use the issue template when filing an issue, this is not enough information to debug.

Since this is a server error I suggest contacting Firebase support:
https://firebase.google.com/support

You will need to help them reproduce the problem, so tell them more about:
- Your development setup.
- What you are trying to deploy.
- The detailed debug logs (that screenshot didn't work)
- etc.
