### ISSUE TITLE
firebase init Error: An unexpected error has occurred.

### ISSUE THREAD

**Issue by timberzen** [firebase/firebase-tools#2114]
Hi
I ran
npm install -g firebase-tools@latest
C:\>firebase init
Error: An unexpected error has occurred.

firebase --open-sesame emulatorgui
firebase emulators:start 

I tried writing the firebase.json file to c:\ but I dont have write access to that as per company guidelines, but admin access all else.
So used C:\temp\ that has the json security api keys in it
All I wanted to do is see the what was at http://localhost:8080/
Somehow I was expecting to see a copy of  "https://console.firebase.google.com/project/" not just 'OK'
It would be nice if it told me what file was missing, what is "default credentials" CRUD access to a folder a project a node?
Is there a youtube vid  for this?

```
C:\>firebase --debug init
[2020-04-08T15:35:36.718Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2020-04-08T15:35:36.737Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (C:\Users\dthompson\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (C:\Users\dthompson\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\dthompson\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)

Error: An unexpected error has occurred.
```

**Comment by joehan** [comment]
Hey @timberzen, it looks like you might be running into a few different issues here - I'll try to address them.
> firebase --open-sesame emulatorgui
firebase emulators:start
 All I wanted to do is see the what was at http://localhost:8080/
Somehow I was expecting to see a copy of "https://console.firebase.google.com/project/" not just 'OK'

When I run ```firebase --open-sesame emulatorgui  && firebase emulators:start```, I get the following output: 
<img width="1433" alt="Screen Shot 2020-04-08 at 9 30 12 AM" src="https://user-images.githubusercontent.com/4635763/78809590-067d4500-797c-11ea-8840-47ca6da1d98c.png">

A few different ports get printed out here - localhost:8080 is the default location for the Firestore emulator. The OK you're seeing is just a health check page. It sounds like you were looking for the emulator GUI, which is spun up on localhost:4000 by default.

It also sounds like you are having a separate issue with `firebase init` related to your application default credentials. Could you try to run `firebase login`, and then rerun your `firebase init` command in an empty directory that you have write access to? I suspect that is the root cause of this issue.

> It would be nice if it told me what file was missing, what is "default credentials" CRUD access to a folder a project a node?
 This one is an internal error, that we should definitely be bubbling up with a better user facing error than `An unexpected error occurred.` 

This is an error message from the library that firebase-tools uses to authorize with google cloud. The 'default credentials' in this case are [Application Default Credentials](https://cloud.google.com/docs/authentication/production#providing_credentials_to_your_application) that firebase-tools uses to access your Firebase/Google Cloud project. firebase-tools normally manages this behind the scenes, but if you have the environment variable GOOGLE_APPLICATION_CREDENTIALS set, it will use that key instead.

**Comment by samtstern** [comment]
@timberzen hi! (it's Sam from the mailing list)

Your `init` issue looks similar to this one:
https://github.com/firebase/firebase-tools/issues/2092

Have you run `firebase login` yet?  If you have already could you try it again as `firebase login --interactive`?

@bkendall it looks like we may have an issue with auth on Windows from the no-auth state related to your recent changes.

**Comment by vedbhawsar** [comment]
I was facing this same issue since yesterday. I was running the `firebase init` command and it resulted in  
Error: An unexpected error has occurred

As I newly installed the `firebase-tools` and was running the command for the first time, running `firebase login` resolved the issue.

**Comment by bkendall** [comment]
Oh hey, I just saw you mentioned me. I also happened to have set up a windows machine so I could test stuff like this. I'll try to get back to this soon. Thanks.

**Comment by bkendall** [comment]
@timberzen - I see the same error as you if I try to `firebase init` after logging out of the CLI. If you run `firebase login` first, does `init` succeed for you?

Maybe an action that can come out of this is better error handling when there's no logged-in user (rather than just saying "unexpected error")

**Comment by samtstern** [comment]
We just got another report of this.  We should never have unexpected errors, I'll take a look.
