### ISSUE TITLE
I have found this

### ISSUE THREAD

**Issue by supermanvimal** [firebase/firebase-tools#2194]
### command:  firebase serve -o [ipAddress]

` functions: Beginning execution of "getTemplates_v1"
⚠  Google API requested!
   - URL: "https://www.googleapis.com/oauth2/v4/token"
   - Be careful, this may be a production service.
i  functions: Finished "getTemplates_v1" in ~2s`

I am using fire functions in emulator more than one month(It is working fine untill today).I didn't change anything but suddenly it comes.

### Admin Setup Code

```js
`  const admin = require('firebase-admin');
    const serviceAccount = require("./serviceaccount")
    const adminConfig = JSON.parse(process.env.FIREBASE_CONFIG);
    adminConfig.credential = admin.credential.cert(serviceAccount);
    admin.initializeApp(adminConfig);`
```

### [REQUIRED] Environment info

**firebase-tools:8.1.1**

**Platform:macOS**

### [REQUIRED] Expected behavior
Usually It don't log this message

### [REQUIRED] Actual behavior

but now I can see this log

**Comment by samtstern** [comment]
@vimalchandhru please fill out the whole issue template when filing an issue.  Can you give an example of the code you're running that causes this?

**Comment by vimalchandhru** [comment]
@samtstern  Edited the question. Can you check now

**Comment by supermanvimal** [comment]
Edited the question. Can you check now? @samtstern 
is this info enough?

**Comment by samtstern** [comment]
@supermanvimal this is working as expected.  You are using a specific production service account inside the Cloud Functions emulator which means that the Firebase Node.js Admin SDK will exchange the service account key for a token using the googleapis endpoint you showed.  The log message we print is to warn you about this, since many people don't want their tests to access any production APIs.
