### ISSUE TITLE
Error when running firebase emulators:start

### ISSUE THREAD

**Issue by tenjojeremy** [firebase/firebase-tools#2268]
running firebase emulators:start returns error promt 
<img width="492" alt="Screen Shot 2020-05-21 at 4 57 26 PM" src="https://user-images.githubusercontent.com/25231946/82606045-71798880-9b84-11ea-984d-9a1fc4e36b36.png">

irebase-tools@8.4.0

**Comment by samtstern** [comment]
@tenjojeremy the Firestore, Realtime Database, and PubSub emulators are `jar` files which we execute using `java`.  On some versions of macOS when you run `java` but don't have it installed it does that popup instead of just failing.

You will need java if you want to run those emulators.  You can run the other emulators with `emulators:start --only functions,hosting` if you don't want to run those.

**Comment by tenjojeremy** [comment]
> @tenjojeremy the Firestore, Realtime Database, and PubSub emulators are `jar` files which we execute using `java`. On some versions of macOS when you run `java` but don't have it installed it does that popup instead of just failing.
> 
> You will need java if you want to run those emulators. You can run the other emulators with `emulators:start --only functions,hosting` if you don't want to run those.

Got it, thanks!
