### ISSUE TITLE
Lint templates should use 'eslint' not 'tslint'

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#2411]
### [REQUIRED] Environment info

**firebase-tools:** 8.4.3

**Platform:** all

### [REQUIRED] Test case

See:
https://github.com/firebase/firebase-tools/tree/master/templates/init/functions/typescript

We use TSLint which is now deprecated in favor of ESLint.

### [REQUIRED] Steps to reproduce

N/A

### [REQUIRED] Expected behavior

The internally filed bug report said:
```
the firebase cli, when setting up Functions and choosing TypeScript, asks if you want to use tslint instead of eslint. I know it's
used internally, but tslint is obsolete. Both the JS and TS options should prompt to set up eslint, and the latter should simply
add the TS parser for eslint. In fact both could use the same default eslint config: see eslint-config-react-app for a dual 
JS/TS config example.
```

### [REQUIRED] Actual behavior

N/A

**Comment by bkendall** [comment]
I think this is a good idea, especially since [TSLint is headed out the door](https://github.com/palantir/tslint/issues/4534) - really out the door and around the corner at this point.

@laurenzlong - could you have someone take a look into this? This repository uses eslint with all the tslint goodness, so it might be a good (if slightly more complex) example.
