### ISSUE TITLE
Can't find documentation on how to use Firebase Emulator for Java functions

### ISSUE THREAD

**Issue by Gintasz** [firebase/firebase-tools#2440]
### [REQUIRED] Environment info

**firebase-tools:**8.5.0

**Platform:** macOS

I'm writing a background function on Java with a Firestore trigger and I want to test it locally. At the moment I do not find any documentation on how to set up the firebase emulator to use a custom jar as a source of functions. Is the emulator available only for nodejs functions?

```
gintas-mac:backend_java gintas$ firebase emulators:start --help
Usage: firebase emulators:start [options]

start the local Firebase emulators

Options:
  --only <emulators>          only specific emulators. This is a comma separated list of emulator names. Valid options are: ["functions","firestore","database","hosting","pubsub"]
  --inspect-functions [port]  emulate Cloud Functions in debug mode with the node inspector on the given port (9229 if not specified)
  --import [dir]              import emulator data from a previous export (see emulators:export)
  -h, --help                  output usage information
```

**Comment by samtstern** [comment]
@Gintasz yes the emulator in the Firebase CLI only supports Node.js functions because that's the only language supported by the [firebase functions SDK](https://github.com/firebase/firebase-functions).

If you want to run Java functions locally try the functions framework:
https://github.com/GoogleCloudPlatform/functions-framework-java
