### ISSUE TITLE
Support multi file functions deployment

### ISSUE THREAD

**Issue by vdjurdjevic** [firebase/firebase-tools#2478]
At this moment, firebase functions require strict structure with package.json pointing to a single entry file that contains (or reexports) all functions. We can deploy single function with `--only functions:some-fn..`,  but it's hard to configure CI systems to deploy only what's changed. [Nrwl Nx](nx.dev) is an awesome tool for managing monorepo workspaces, and building, testing and deploying only targets affected by some change. Now, for Nx to do it's best, every firebase functions should be node application in Nx workspace. That way, CI system can be configured to leverage Nx tools to build, test, and deploy only functions affected by the last change. 

The simplest way I could think of is to make `functions.source` filed in `firebase.json` object instead of a string. Keys would be function names and values source dirs. For example:

```json
{
    "functions": {
        "sources": {
            "func-1": "dist/apps/functions/func-1",
            "func-2": "dist/apps/functions/func-2",
            ......
        }
    }
}
```

Everything stays the same, dist dirs would contain package.json and index.js file with the source for that function.
I would like to contribute plugin to integrate firebase with Nx workspaces to community, and this would unluck it's full power.

**Comment by samtstern** [comment]
@vdjurdjevic thanks for the detailed suggestion!  The single-file Functions deployment model is a core assumption of `firebase deploy` and we're not really looking into changing it now.

Here are some things you may be interested in though:
  * You could modify a tool like [`better-firebase-functions`](https://github.com/gramstr/better-firebase-functions#readme) to dynamically discover all of your functions files and export them from a single location. 
  * Instead of using the `firebase` CLI to deploy, you could try the `gcloud` CLI.  It's much better adapter to the idea of one package per function.  You can still use the `firebase-functions` SDK to define your exported handlers.

**Comment by vdjurdjevic** [comment]
Thanks for the replay, I will check those options out.
