### ISSUE TITLE
error "function ignored because the auth emulator does not exist or is not running."

### ISSUE THREAD

**Issue by ajitgoel** [firebase/firebase-tools#2551]
I am constantly getting a `function ignored because the auth emulator does not exist or is not running.` error when running the application. What am I missing? I have attached the logs as per the request. 

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/5082333/firebase-debug.log)
[firestore-debug.log](https://github.com/firebase/firebase-tools/files/5082334/firestore-debug.log)
[ui-debug.log](https://github.com/firebase/firebase-tools/files/5082335/ui-debug.log)
[database-debug.log](https://github.com/firebase/firebase-tools/files/5082336/database-debug.log)

**Comment by samtstern** [comment]
@ajitgoel there's nothing wrong here.  The emulator suite cannot currently emulate `functions.auth` triggers because there is no Auth emulator to trigger them.

We're working on an auth emulator, for now if you want to test those functions use `functions:shell` or the `firebase-functions-test` library.
