### ISSUE TITLE
.firebaserc and firebase cli completely ignored

### ISSUE THREAD

**Issue by elucidsoft** [firebase/firebase-tools#2558]
If you have a .firebaserc file setup
```
{
  "projects": {
    "dev": "dev-land",
    "stage": "stage-land",
    "prod": "prod-land",
    "default": "dev-land"
  }
}
```

And have a firebase.json like this

```
{
  "hosting": {
    "public": "dist",
    "rewrites": [{
      "source": "**",
      "destination": "/index.html"
    }],
    "site": "dev-land-9008c",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**"]
  }
}
```
Some firebase command or process puts the "site": "dev-land-9008c", line in there, not sure what does it.  Doesn't really matter.  What matters is the behaviors observed when this line exists. This line overrides .firebaserc, and also overrides ALL cli commands.

if you run: ```firebase use dev``` the CLI reports back that it successfully switched to 'dev-land'

If you then run ```firebase deploy``` it will say '=== Deploying to dev-land...' but then in the status updates it will say 'Deployed successfully to 'dev-land-9008c'.

If you run ```firebase deploy --project dev-land``` same thing, it reports its deploying to 'dev-land' but deploys to 'dev-land-9008c' instead.

If you delete .firebaserc, and redo all of it using ```firebase use --add```, same behavior.
If you run ```firebase use --clear```, same behavior.
If you re-run ```firebase init```, same behavior.

Needless to say this took me over 3 hours to find, EXTREMELY frustrating.  It started in my CI/CD pipeline, I spent 2 hours there, then noticed it was happening locally.  Like I said I have no idea what adds the site line to firebase.json but that line shouldn't exist.  Especially with the aliasing, and .firebaserc.  That should be removed entirely, beyond confusing.

**Comment by elucidsoft** [comment]
```firebase --version```
8.7.0

**Comment by elucidsoft** [comment]
Something I didn't clarify, dev-land-9008c is not the same project as dev-land. Completely different projects!

**Comment by samtstern** [comment]
@elucidsoft ok it sounds like at the very least we need to improve our logging messages!  It may also be a bug, @bkendall can comment on that.

When you create a new Firebase Project there is exactly one "site".  However you can have more than one site per project:
https://firebase.google.com/docs/hosting/multisites

So changes we could make:
  1. The logs should definitely declare what site they are deploying to if it's not equal to the project ID
  2. I **think** it would be reasonable if we checked that the `site` actually belongs to the targeted project, but maybe @bkendall will explain to me why that's not a good idea.

**Comment by mbleigh** [comment]
Hi this is working (ish) as intended -- the real question is how the `site` field got populated into your `firebase.json` in the first place (since it sounds like you didn't do it?). Are you sure it was injected by a `firebase` command? Can you reproduce this (if so please let us know where it's happening)?

Firebase Hosting supports multiple sites in a single project directory through two mechanisms: `target` and `site`. The one we want folks to use is `target` (see [docs](https://firebase.google.com/docs/cli/targets)) which allows for per-project aliasing of sites to allow for multiple environments. However we do also support an absolute unique `site` value that is independent of project.

I agree with Sam that we should consider erroring out if the `site` in question does not match the current project.

**Comment by elucidsoft** [comment]
I don't recall ever adding that sites line but honestly I can't say with any degree of certainty that a tool added it or I did.
