### ISSUE TITLE
firebase emulators:start the `__/firebase/init.js` points at the web and not local eumulators

### ISSUE THREAD

**Issue by mikebski** [firebase/firebase-tools#2597]
I have my Firebase stuff setup locally and the emulators work fine (I can get into the UI and everything) but when I access my webapp locally at http://localhost:5000/ and look at the contents of `init.js` all the variables point at the cloud datastore and stuff.

My unit tests will talk to the emulator by doing this:

```
var authenticatedApp = firebaseTesting.initializeTestApp({
    databaseName: "blahblah-d46ae",
    auth: { uid: "alice", email: "alice@example.com" }
})

beforeAll((done) => {
    //initFirebase();
    done()
})

afterAll((done) => {
    //firebase.database().goOffline();
    Promise.all(firebaseTesting.apps().map(app => {
        app.delete()
    })).finally(done)
})

```

How do I start the emulator so that `init.js` will point to everything locally (functions, database, etc...)?

**Comment by yuchenshi** [comment]
If your unit testing is running on Node.js, you don't need `init.js`. For example, if your tests are in `npm test`, just try `firebase emulators:exec "npm test"` and that will start the emulator and set some environment variables for SDKs to talk to emulators automatically.

If your tests run in a browser (e.g. web driver), please let us know the details. We don't recommend this since web drivers are mostly for integration testing, but we'd love to hear your use case.

**Comment by mikebski** [comment]
@yuchenshi I'm just running locally to be able to test without hitting the cloud servers, eventually I would like to do integration tests with a browser pointed at the all-locally-running services...

**Comment by yuchenshi** [comment]
I hate to disappoint you, but full integration testing cannot be fully local for now since Firebase Auth is not locally emulated (yet). It seems you're using Firebase Auth from the snippet you posted.

Would you please try the steps above to see if your unit tests (with mocked auth as shown in your snippets) work correctly?

**Comment by PaulRudin** [comment]
This is still an issue, and now there's an auth emulator, so presumably it should be possible to coax the emulator to do the right thing when running locally.

**Comment by yuchenshi** [comment]
@PaulRudin You can now opt-in to an emulated `init.js` by adding `?useEmulator=true` flag, like so:

```html
<script defer src="/__/firebase/init.js?useEmulator=true"></script>
```

For *new* projects initialized from the Firebase CLI, this flag will be automatically set for you in the generated `public/index.html`.

This flag has no effect in production Firebase Hosting and it only configures enabled and running emulators. If you want the Auth Emulator, please run `firebase init emulators` first and check it from the list.
