### ISSUE TITLE
Custom Token used for Auth does not send Correct user info

### ISSUE THREAD

**Issue by rick-rheo** [firebase/firebase-tools#2779]
### [REQUIRED] Environment info

8.14.1
macOS

### [REQUIRED] Test case

run a FB function, get user info from context

### [REQUIRED] Steps to reproduce

install tools etc enable auth emulator etc etc.
create a user with id  42069,  email:  foo@bar.com , name: Foo Bar

```
fb.auth().createCustomToken('42069').then(customToken => {
```

Using Postman,  include that custom token as Authentication: Bearer X   header   

call FB function in emulator

### [REQUIRED] Expected behavior

```
context.auth == {
	"uid": "42069",
	"token": {
		"name": "Foo Bar", 
		"email": "foo@bar.com",	
		...
		}
	}
}
```

### [REQUIRED] Actual behavior

```
context.auth == {
  "uid": "firebase-auth-emulator@example.com",
  "token": {
    "aud": "https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit",
    "iat": 1604517517,
    "exp": 1604521117,
    "iss": "firebase-auth-emulator@example.com",
    "sub": "firebase-auth-emulator@example.com",
    "uid": "firebase-auth-emulator@example.com"
  }
}
```

Or... you could tell me the correct way to test FB functions that require auth and a complete user record purely with Postman  without using a webapp or ios or android.

**Comment by samtstern** [comment]
@rick-rheo sorry I never responded here! The issue is you're mixing up Custom Auth Tokens and Firebase ID Tokens.

The token you get from `createCustomToken()` is **not** meant to identify the user! Instead you send it down to the client and then call `signInWithCustomToken()` in your app.

Then once you're signed in you can call `getIdToken()` in your app to get an ID token. The ID token is the one you want to send back to Cloud Functions as `Authorization: Bearer X`.

For more information on this flow:
https://firebase.google.com/docs/auth/web/custom-auth
