### ISSUE TITLE
Node version mismatch log possibly incorrect

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-tools#2791]
I am also getting this warning with the Firebase Emulator. I have a minimal reproduction at https://github.com/jthegedus/firebase-emulator-warning-reproduction with a GitHub Action demonstrating the issue.

The short of it is this:
- set Node version with `asdf` and ensure running `node --version` in a later step produces the version set by `asdf`
- `firebase emulators:exec ...` runs and prints
	```
	⚠  Your requested "node" version "10" doesn't match your global version "12"
	```
- Node 12.19.0 is the default for the GitHub Action runner I am using (ubuntu-latest as seen here - https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md)

The emulator runs, but I am unsure if the code is actually running in Node 12 or if this is a just a logging and detection error :shrug:

_Originally posted by @jthegedus in https://github.com/firebase/firebase-tools/issues/1489#issuecomment-722930482_

**Comment by yulkin2002** [comment]
I am getting the same error

**Comment by alexkirmse** [comment]
Looks like this has been fixed by @joehan here:
https://github.com/firebase/firebase-tools/issues/4024

This ticket can be closed.

**Comment by alexkirmse** [comment]
@samtstern There seems to be different behavior depending on how firebase tools is installed. If you use the standalone binary it shows the log message but with the npm install method it doesn't. 

I suspect that the standalone binary is bundled with node 12 (via firepit ?) so when [checking what version node firebase tools is running](https://github.com/firebase/firebase-tools/blob/master/src/emulator/functionsEmulator.ts#L867), its using the embedded node (12) instead of the locally installed version?

**Comment by yuchenshi** [comment]
@alexkirmse Yes, the standalone binary comes with a version of Node.js bundled. If that version doesn't work for you, please use the npm installation method instead

**Comment by alexkirmse** [comment]
@yuchenshi Makes sense. I brought this up specifically with this specific error:
```
Your requested "node" version "10" doesn't match your global version "12"
```

I think the reason there's a mismatch is that the global version comes from the bundled nodejs regardless of what's set in package.json as the engine. With bug reports, it might be interesting to ask how firebase-tools was installed npm or binary.

**Comment by alexkirmse** [comment]
@coffeepostal Did you install firebase-tools via the binary or npm?
If you installed via binary try deleting it and installing via npm. Since the binary ships with it's own node and seems to be at 12.

**Comment by drmanojgrg** [comment]
no solving yet

**Comment by matzeso** [comment]
I had the same issue my code was not running since it required at least node 16 but running emulators ran with node12. It took me quite a while to figure this out. I think it would be really beneficial for the developer if the message could include the fact that the "host" system node@12 is not _really_ coming from the host but from the binary.

**Comment by zerolethanh** [comment]
if you use `nvm` for packages manager, you must check `firebase` command belongs to nvm of using node.
```sh
$ which firebase
/Users/thanhle/.nvm/versions/node/v16.17.0/bin/firebase // this is ok
```
if not, you must install firebase-tools:
`npm i -g firebase-tools`

**Comment by genkiabe21** [comment]
package-jsonで指定されている部分が古すぎて動いてない可能性がある

**Comment by danielfowler** [comment]
I'm having this issue after installing `firebase-tools` with `npm install`.

`functions: Your requested "node" version "22" doesn't match your global version "23". Using node@23 from host.`

Emulator likes my cloud functions but my deployed functions do not work and I'm guessing this is why.
