### ISSUE TITLE
Release assets do not have stable SHAs

### ISSUE THREAD

**Issue by rockwotj** [firebase/firebase-tools#2799]
Hi! :wave:

So we've been using the awesome binary releases of firebase tools to automate deploys, and part of that is downloading a specific release asset of firebase tools to deploy our frontend.

We've noticed that the release assets on the releases change periodically... We take a sha of the binary when we upgrade versions and we've noticed that after some time if someone else pulls down that same URL that SHA does not match. Do you update these assets or is GitHub modifying them somehow? FWIW we do this for sentry-cli as well and their SHAs do not change...

Here is a concrete example. For **MacOS** firebase tools 8.14.1 first had a sha of `88339c6c1dd934f853adc39faa6c3622fc4ec67f19bae3ccc4de1b357fde78b1` when it first was released but now it seems to be `bc9b4f396d8535a20af9aa6b1ba30b2c5036e23dc5719067e8f1615f8a536196`

For now I guess we'll mirror the binaries in our own bucket, but it'd be great if the release assets didn't change :smile:

**Comment by samtstern** [comment]
@abeisgoat @bkendall could this be because of the release pipeline issues we've been having?  I know you had to run the firepit scripts twice.

(👋 hi tyler!)

**Comment by abeisgoat** [comment]
Huh, super interesting (also hello friend!). It is... slightly concerning that this is happening since we all know changing hashes on artifacts is generally a sign of tampering. However, it could def be related to the flakey build pipeline for firepit. For example, I'm sure if we build a binary for a version and sha'd it then did a new build of the same version a week later, they would not line up so if the flakiness is related to the pipeline accidentally picking up an old version and building / releasing for that (which is possible since it uses `@latest` not a specific version). I'll speak with @bkendall first thing in the morning and get to the bottom of this.

**Comment by abeisgoat** [comment]
Alright, we've confirmed this is a bug in the build pipeline where it accidentally builds older versions when the npm cache doesn't get invalidated immediately after release. It's on my list to fix this and this will bump up the priority.

**Comment by rockwotj** [comment]
@abeisgoat did this ever get fixed?

**Comment by bkendall** [comment]
Yes, I believe I fixed this. Short version: the version of `firebase-tools` that was being pulled down when the assets were being made was old, and then it was being re-pushed to that release, changing the SHA. This should be done.
