### ISSUE TITLE
 Value listening event on Unity

### ISSUE THREAD

**Issue by nhutthanh340** [firebase/firebase-tools#2833]
Hi, I'm currently having a problem with the value change listening event in Unity. I use Firebase emulator locally. I just get the snapshot with null value. Can you help me solve this problem. Thanks.

![image](https://user-images.githubusercontent.com/36669308/99405483-65963580-291f-11eb-8a93-3442adb486d8.png)

![image](https://user-images.githubusercontent.com/36669308/99405328-38e21e00-291f-11eb-9690-3ec9bd84eeeb.png)

**Comment by samtstern** [comment]
@nhutthanh340 please use the issue template when filing issues.  We can't help you without that information.

Since you've only posted screenshots of your Unity editor there's no reason for us to think this is a bug in the Firebase CLI or the emulators.  It is likely a bug in your code or in the Firebase Unity SDK.

I would suggest posting the question here, where you can get help from a Unity expert:
https://github.com/firebase/quickstart-unity
