### ISSUE TITLE
Sign-in with E-mail link from Admin SDK is rejected due to invalid action code

### ISSUE THREAD

**Issue by dound** [firebase/firebase-tools#2936]
### [REQUIRED] Environment info
**firebase-tools:** 8.14.1
**Platform:** Ubuntu

### [REQUIRED] Test case

See steps.

### [REQUIRED] Steps to reproduce
1. Start the emulators with `firebase emulators:start`
1. Use the Admin SDK to generate a dynamic Firebase link to sign-in with e-mail:
```js
const admin = require('firebase-admin')
process.env.FIREBASE_AUTH_EMULATOR_HOST = 'localhost:9099'
process.env.FIRESTORE_EMULATOR_HOST = 'localhost:8080'
admin.initializeApp({
  projectId: 'my-app-name'
})
const auth = admin.auth()
const user = await auth.createUser({ displayName: 'some name', email: 'test@example.com', emailVerified: true })
const firebaseDynamicLink = await auth.generateSignInWithEmailLink(user.email, {
  url: 'http://localhost:3000'
})
console.log(firebaseDynamicLink)
```
3. Try to open the link in the web application running on localhost that's opened via the URL output from the previous step:
```js
  if (firebase.auth().isSignInWithEmailLink(window.location.href)) {
    const email = window.prompt('Please type your email to confirm login')
    firebase.auth().signInWithEmailLink(email, window.location.href)
      .then(result => {
        // we never get here
      })
      .catch(error => {
        console.error(error) // we always get an auth/invalid-action-code error
      })
  }
```

### [REQUIRED] Expected behavior
Email link should work. When the Admin SDK generates a non-emulator link, that link works fine with the deployed app. Only the emulator link fails.

### [REQUIRED] Actual behavior
`firebase.auth().isSignInWithEmailLink(window.location.href)` throws an exception (auth/invalid-action-code) when using the emulator.

**Comment by yuchenshi** [comment]
First, please note that your `projectId: 'my-app-name'` in Admin SDK must match the project you're using for the emulator suite for this to work. When in doubt, start the emulator suite with `firebase emulators:start --project my-app-name` (where `my-app-name` matches your admin SDK config).

Second, please make sure you've called `firebase.auth().useEmulator('http://localhost:9099')` BEFORE you do anything else (like `signInWithEmailLink`). Preferably, `useEmulator` should be the first thing after `firebase.initializeApp`. Otherwise, there is a chance that the SDK is hitting production -- where that action code of course won't exist. You can also double check this by having browser DevTools open and then navigate to the link. Double check that all requests start with `http://localhost:9099/`, not `https://www.googleapis.com/`.

**Comment by dound** [comment]
Sorry, I'll reply shortly after trying Yu's suggestion.

**Comment by dound** [comment]
> First, please note that your `projectId: 'my-app-name'` in Admin SDK must match the project you're using for the emulator suite for this to work. When in doubt, start the emulator suite with `firebase emulators:start --project my-app-name` (where `my-app-name` matches your admin SDK config).

Thanks, in my first attempt I didn't realize this. But I did figure this out and correct my code before opening this PR.

> Second, please make sure you've called `firebase.auth().useEmulator('http://localhost:9099')` BEFORE you do anything else (like `signInWithEmailLink`). Preferably, `useEmulator` should be the first thing after `firebase.initializeApp`. Otherwise, there is a chance that the SDK is hitting production -- where that action code of course won't exist. You can also double check this by having browser DevTools open and then navigate to the link. Double check that all requests start with `http://localhost:9099/`, not `https://www.googleapis.com/`.

This was the issue; I'd missed this call when trying to piece together the documentation.

Thanks for your help and patience.
