### ISSUE TITLE
After updaiting my firebase tools (8.19.0), --import of database doesnt allow database modification

### ISSUE THREAD

**Issue by Bakavani** [firebase/firebase-tools#2967]
### [REQUIRED] Environment info

**firebase-tools:** 8.19.0

**Platform:** Windows 10

### [REQUIRED] Test case
If I start firebase emulator with

firebase emulators:start --import <pathToMyDB>
After upgrade I'm not able to modify the db either with web interface or from the app (android app), it gets reset automatically to the stored exported files.

### [REQUIRED] Steps to reproduce
start firebase emulator with 
firebase emulators:start --import <pathToMyDB>

After the emulator is up it doesn't allow modification to realtime database at all.

Only way is to load emulator without --import and then import it with the gui, but with functions it cannot be done as it complains that it will trigger functions too many times.

### [REQUIRED] Expected behavior
After the emulator is started, it should allow modification of realtime database, through web interface or via a front end (my case android app)

### [REQUIRED] Actual behavior
 it gets reset immediately to the imported version whenever any modification is made.

**Comment by samtstern** [comment]
@Bakavani I am not able to reproduce this, here's what I tried:

1. Start in an empty directory
2. Run `firebase init` and select "Database" and "Emulators"
3. Run `firebase emulators:start --export-on-exit=./data` and start the emulators
4. In the Emulator UI for Realtime Database create some simple data
5. Exit the emulators
6. Start the emulators again with `firebase emulators:start --import=./data`
7. In the Emulator UI confirm I can edit some data

So I don't think import/export is the problem.  Please create a minimal reproducible example or equivalent steps so that we can reproduce this:
https://stackoverflow.com/help/minimal-reproducible-example
