### ISSUE TITLE
Firebase Push Multiple

### ISSUE THREAD

**Issue by phidias51** [firebase/firebase-tools#300]
It would be useful if there was a way to push multiple records in one shot.  For example, if the file you specify in the **database:push** command contains an array of values, then push each individual element of the array as a separate node with its own unique ID.

**Comment by mbleigh** [comment]
Thanks for the suggestion! Unfortunately I don't think this is something we'll be supporting as we want to try to closely mirror the structure and capabilities of the Realtime Database with the CLI and, since everything is an object, I feel that allowing an array of items to push would get confusing.

**Comment by hhsadiq** [comment]
Is there a way to push multiple items using object notation. Consider the following example,

User collection having multiple users.
![image](https://user-images.githubusercontent.com/8002757/30688420-88c47a1a-9ed7-11e7-9ad2-964572eb4f18.png)

Now I want to database:push multiple users to this collection. @mbleigh Is there any way to do that?
