### ISSUE TITLE
`firebase serve` requires login

### ISSUE THREAD

**Issue by ithinkihaveacat** [firebase/firebase-tools#302]
In 3.6, `firebase serve` requires login (i.e. **actual behavior**):

```sh
$ firebase serve
Error: This command requires new authorization scopes not granted to your current session. Please run firebase login --reauth
```

Version 3.5 does not require login (i.e. **expected behavior**):

```sh
$ firebase serve
Starting Firebase development server...
...
```

Requiring login makes it impossible to create an `npm` package that can be installed and run locally without a firebase account. (In 3.5, it was possible to create a package with a dependency on `firebase-tools` that would run on a local port if the developer executed `npm run` or similar. (Such a package could optionally be deployed to a production instance if the developer happened to have a firebase account.) This does not appear to be possible with version 3.6.)

**Comment by mbleigh** [comment]
A few comments here. This was a change for 3.6, and wasn't intended to be breaking for folks (since `firebase serve` is intended for local development and not deployed to production we weren't really considering this use case).

There is [new functionality](https://firebase.googleblog.com/2017/04/easier-configuration-for-firebase-on-web.html) that requires us to know information about the current project to be able to run an accurate local server. We expect that over time there is going to be more, not less, of this and so the login is here to stay (even if we decide to temporarily walk it back).

If you're just looking for the static serving aspects of `firebase serve`, you could take a look at firebase/superstatic which is the open-source static web server that powers Firebase Hosting.

**Comment by ithinkihaveacat** [comment]
Ah thanks, I didn't know about superstatic, looks like that will do the trick!

(There's a small bug (https://github.com/firebase/superstatic/issues/227) that makes it not quite work as a drop-in replacement right now, but I imagine that can be fixed.)

**Comment by socsieng** [comment]
For me, I needed firebase functions support and found that `firebase emulators:start` didn't require login.

Instead of `firebase serve --port 8080`, I now use `firebase emulators:start` with an updated `firebase.json` file:

```js
{
  "functions": { /* ... */ },
  "hosting": { /* ... */ },
  "emulators": {
    "hosting": {
      "port": "8080"
    },
    "functions": {
      "port": "8081"
    },
    "ui": {
      "enabled": false
    }
  }
}
```

**Comment by nipunasudha** [comment]
> For me, I needed firebase functions support and found that `firebase emulators:start` didn't require login.
> 
> Instead of `firebase serve --port 8080`, I now use `firebase emulators:start` with an updated `firebase.json` file:
> 
> ```js
> {
>   "functions": { /* ... */ },
>   "hosting": { /* ... */ },
>   "emulators": {
>     "hosting": {
>       "port": "8080"
>     },
>     "functions": {
>       "port": "8081"
>     },
>     "ui": {
>       "enabled": false
>     }
>   }
> }
> ```

This was extremely helpful. Thank you!
