### ISSUE TITLE
Error when trying to upgrade firetools

### ISSUE THREAD

**Issue by rjpruitt16** [firebase/firebase-tools#3027]
When I run the command "npm install -g firebase-tools  ",  I receive 
'''
EEXIST: file already exists, symlink '../lib/node_modules/firebase-tools/lib/bin/firebase.js' -> '/usr/local/bin/firebase'
npm ERR! File exists: /usr/local/bin/firebase
npm ERR! Remove the existing file and try again, or run npm
''''

There is no "../lib". I have tried reinstalling but it does not work. Any Ideas?

**Comment by bkendall** [comment]
1. Maybe you need to run `npm un -g firebase-tools` first?
2. Have you previously installed the CLI using the firebase.tools script? (`curl -sL firebase.tools | bash`)
3. What does `firebase --version` currently do?

**Comment by rjpruitt16** [comment]
I am on a mac by the way. Thanks.
1.  just tried. but I am guessing it did not work properly because I can continue to run firebase commands.
2.  I dont think I did. It's been a long time but I would guess I did a npm install -g firebase-tools at some point.
3.  "7.11.0"

**Comment by bkendall** [comment]
My hunch is that you have another version of `firebase-tools` on your path somewhere that has unexpected permissions. Typically this is because it was installed with `sudo npm i -g firebase-tools`.

If you try the following, it will show you some of the permissions of the file:

```
ls -al `which firebase`
```

Depending on your Node installation, you may have to use `sudo` to manage the installed version of `firebase-tools`.

**Comment by rjpruitt16** [comment]
I tried deleting /usr/local/bin/firebase, and it install correctly thank you.
