### ISSUE TITLE
Not able to verify email using emulator

### ISSUE THREAD

**Issue by anubhavkamath** [firebase/firebase-tools#3048]
9.2.1
**firebase-tools:**

MacOS BigSur
**Platform:**

### [REQUIRED] Test case
See above.

### [REQUIRED] Steps to reproduce
See above.

### [REQUIRED] Expected behavior

The URL link to verify the newly added user in the auth emulator should be printed on the terminal and/or the provided link in the documentation should work so that I can get past email verification for the emulated user.
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/5825138/firebase-debug.log)

### [REQUIRED] Actual behavior

firebase-debug.log attached.

**Comment by anubhavkamath** [comment]
Not sure what I did but all of a sudden the emulator console started printing out the verification URL when creating a new user in the emulator console.
So, now, I'm past that issue but am still not able to connect to the FIRESTORE emulator. I get this error:

"Firestore (8.2.2): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend."

This is the relevant code where I set up the emulators:
  Firebase.initializeApp(firebaseConfig)

  const firestoreSettings = {}
  firestoreSettings.host = 'localhost:8080'
  firestoreSettings.ssl = false
  Firebase.firestore().settings(firestoreSettings)
  Firebase.firestore.setLogLevel('debug')
  Firebase.firestore().useEmulator('http://localhost:5002')
  Firebase.auth().useEmulator('http://localhost:9099')

Firestore emulator is running on port 5002 according to the console.

**Comment by samtstern** [comment]
@anubhavkamath please use the issue template when filing an issue, "See above" is not helpful if there is no detailed test case above.

As for your Firestore issue, you're doing conflicting things:

This sets the Firestore port to 8080:
```js
firestoreSettings.host = 'localhost:8080'
firestoreSettings.ssl = false
Firebase.firestore().settings(firestoreSettings)
```

This sets it to 5002 but uses the wrong syntax:
```js
Firebase.firestore().useEmulator('http://localhost:5002')
```

Delete both of those and do this:
```js
Firebase.firestore().useEmulator('localhost', 5002);
```

I know this can be a bit confusing because the Firebase Auth `useEmulator` function has a different syntax than the others.  For that one the single-argument syntax `Firebase.auth().useEmulator('http://localhost:9099')` is correct.

For more information see the docs here:

- https://firebase.google.com/docs/emulator-suite/connect_auth
- https://firebase.google.com/docs/emulator-suite/connect_firestore
