### ISSUE TITLE
Firestore Emulator REST API always returns "Not Found"

### ISSUE THREAD

**Issue by nidegen** [firebase/firebase-tools#3077]
### [REQUIRED] Environment info

**firebase-tools:**  9.2.2
**Platform:** macOS Catalina

### [REQUIRED] Test case

empty firestore running in emulator

### [REQUIRED] Steps to reproduce

- `firebase emulators:start`
- `curl -X POST -H "Content-Type: application/json" -d'{"a": "b"}'\"http://localhost:8080/emulator/v1/projects/<project-name>/databases/(default)/documents/sd/aa"`

### [REQUIRED] Expected behavior

Add `{a: b}` to document aa in collection sd

### [REQUIRED] Actual behavior

returns `Not Found`

After adding data to firestore, only the command `curl -v -X DELETE "http://localhost:8080/emulator/v1/projects/<project-name>/databases/(default)/documents"` works as expected

**Comment by samtstern** [comment]
@nidegen this is working as intended because that is not a correct use of the Firestore REST API.  Unlike with Realtime Database, you can't just `POST` JSON data to the document path.

For information on writing data using REST see the `commit` API:
https://firebase.google.com/docs/firestore/reference/rest/v1/projects.databases.documents/commit

**Comment by penx** [comment]
For anyone looking at this in future, the issue seems to be that the url needs to start with "http://localhost:8080/v1" rather than "http://localhost:8080/emulator/v1"
