### ISSUE TITLE
Hosting: allow to upload an app version, but not activate/deploy it

### ISSUE THREAD

**Issue by Birowsky** [firebase/firebase-tools#311]
The scenario I wanna be able to accomplish

1. Upload to staging and production - activate/deploy/publish only staging
2. Testers test, developers keep developing
3. Testers like the staging version, they are able to activate/deploy/publish the matching production app version without developer's engagement

**Comment by mbleigh** [comment]
Since this is a feature request for Firebase Hosting more than a bug for the CLI, I'm going to close. However, I've added this to a related issue we're already tracking internally. We have some interest in doing something like this in the future, but don't have anything specific to talk about right now.
