### ISSUE TITLE
firebase deploy --only functions:oneFunction fails but function is deployed successfully

### ISSUE THREAD

**Issue by ljle** [firebase/firebase-tools#3147]
### [REQUIRED] Environment info

**firebase-tools:** 9.4.0

**Platform:** Arch Linux on WSL2 with Node 12.20.1

### [REQUIRED] Test case

I don't have a minimal test case for this.

### [REQUIRED] Steps to reproduce
- Run `firebase deploy --only functions:oneFunction`

### [REQUIRED] Expected behavior

- Output in the console that the function was successfully deployed.

### [REQUIRED] Actual behavior

- Output says there were errors deploying the function:
![image](https://user-images.githubusercontent.com/696474/108413524-e52aed80-7209-11eb-8e00-6134a4c6ff89.png)
- If I run the command with the `--debug` flag, the last lines of the logs say this:
![image](https://user-images.githubusercontent.com/696474/108415867-cd089d80-720c-11eb-9aa5-c5ea680a4214.png)

- But in the Google Cloud Console for Cloud Functions dashboard, in the "last deployed" column it displays the time as if it was correctly deployed, I had to manually test my app and the change was deployed correctly.
![image](https://user-images.githubusercontent.com/696474/108413951-64202600-720a-11eb-9ce1-31b99a0c39ec.png)

**Comment by m4recek** [comment]
We have had same problem and few more with 9.4.0 and reverted to 9.3.0 to get our deploys working again.
- error in deploy, success in cloud console
- error in deploy, in progress in cloud console (subsequent retry failed because `HTTP Error: 400, An operation on function ... is already in progress`
- reporting error for one function from a batch and not reporting status of the rest of the batch 
- 9.4.0 is creating new functions without `Allow unauthenticated` flag, 9.3.0 is using it. I believe this is not documented anywhere

**Comment by joehan** [comment]
Hi @ljle, thanks for reporting this. It looks like the issue here is that the function you deployed is taking longer to deploy than our timeout on polling the operation. I'll make a PR to increase this timeout, which should help. 

@m4recek I think the first 2 issues are related to this timeout - I'll take a closer look into the other 2 shortly.

**Comment by joehan** [comment]
@m4recek 
> * reporting error for one function from a batch and not reporting status of the rest of the batch
Could you open a separate issue for this and include logs of what you're seeing? I think I identified one issue with the code that might cause this, but I want to make sure its actually what you are seeing,
> * 9.4.0 is creating new functions without `Allow unauthenticated` flag, 9.3.0 is using it. I believe this is not documented anywhere
On further inspection, I think this is related to the same timeout issue - we set the necessary IAM policy to 'allow unauthenticated' for new functions here: https://github.com/firebase/firebase-tools/blob/master/src/deploy/functions/tasks.ts#L81, but it the operation polling times out, this will never be run.

**Comment by komachi** [comment]
Experienced same problems on 9.4.0. Trying multiple functions deploy, only one get actually deployed (as indicated by cloud console), but CLI reports all failing. Running deploy with `--debug` indicate that it tries to re-run deploy of that function until timeout is hit (lots of `Retrying task index 0` followed by `FirebaseError: Task index 0 failed: timed out after 300000ms.`).

Downgrade to 9.3.0 helped, and build are passing fine again, but was hard to debug, running deploy without `--debug` just fails without any meaningful message.

**Comment by janswist** [comment]
I have the very same issues. Trying to upload barely changed functions and I get deployment error.

**Comment by taylorhoward92** [comment]
I've been seeing this issue as well since upgrading `firebase-tools` from `v9.2.0` to `v9.4.0`.

**Comment by mbleigh** [comment]
I've created #3150 to increase the timeout and address this. We will likely get it released in the next day or two, but in the meantime you can either downgrade to v9.3.0 or install directly from the PR branch:

    npm i -g firebase/firebase-tools#mb-fn-timeout

**Comment by LincolnFerreira** [comment]
The deployment time actually increased very quickly, it went from 5-7 minutes with 800kb to 30 minutes + with 950kb, I understand that it can take a while due to the size but I only take timeout and I don't know if it is actually an upload timeout or If there is something in the code that could be causing some kind of bottleneck, has anyone experienced this?

![Captura de Tela 2024-07-31 às 12 57 17](https://github.com/user-attachments/assets/515f4fd5-e0a5-4235-b653-e982c6012518)
