### ISSUE TITLE
Add App to Project

### ISSUE THREAD

**Issue by Desnoo** [firebase/firebase-tools#319]
It would be nice to add the android, ios and web App over the command line to a project.
Additionally it would be nice to receive the metadata of the applications as a response.

**Comment by visiolink-android-dev** [comment]
Our CI server adds product flavors to our Android app. When a flavor is added, the project must be sync'ed
using the Firebase plugin in Android Studio, so that the new flavor is added to the Firebase project and the new "google-services.json" file is downloaded to the project.

We would like to be able to do that without Android Studio. If it was added to this project, one could execute that from the CI server.

**Comment by samtstern** [comment]
Looking at old issues, this is a duplicate of https://github.com/firebase/firebase-tools/issues/233 which is being tracked internally.
