### ISSUE TITLE
Cloud scheduler for Cloud Functions timezone is not set correctly

### ISSUE THREAD

**Issue by saurabhshah23** [firebase/firebase-tools#3425]
Cloud functions pubsub set with .timezone("America/New_York") not working since firebase-tools latest update.
.pubsub
.schedule('0 12 * * *')
.timeZone("America/New_York")
CI pipeline successful but the timezone for cloud-scheduler was always set to default ("Los Angelos") without any errors.

It worked only after reverting the firebase-tools version back to 9.6.1 in CI.
> npm install -g firebase-tools@9.6.1

**Comment by astefer** [comment]
Same issue. This crashed my production environment without any warning

**Comment by mikan3rd** [comment]
I had the same problem with `"firebase-tools": "9.12.0"`
Downgrading to `"firebase-tools": "9.11.0"` brought it back.

**Comment by astefer** [comment]
I think 33ff495242e7d9e9b76f89452fe9f7e009c54bf3 broke something.

**Comment by ashking** [comment]
I caused a loss of close to $1000 transactions due to this issue (~70k thousand INR) on production
I regret upgrading to this version and deploying on a Friday night.

**Comment by samtstern** [comment]
@saurabhshah23 @mikan3rd @astefer thank you for reporting this and we are really sorry about the timing of this bug. Googlers in the US were on holiday for Friday and Monday and because this was an SDK issue rather than a backend issue it didn't page the on-call team.

We'll get a fix out ASAP. In the meantime the workaround is to downgrade to `9.11.0` and redeploy.

@ashking or anyone else who experienced a loss due to this issue please write in to Firebase support and mention this bug, we'll see what we can do.

**Comment by inlined** [comment]
Fixed in #3434 and released to npm

**Comment by Smartiex** [comment]
in asecond generation how can i set this time zone
