### ISSUE TITLE
<Functions dir> is outside project directory when customising config and functions locations

### ISSUE THREAD

**Issue by trullock** [firebase/firebase-tools#3548]
This is somewhere between a bug and a feature change

The firebase cli lets you do `--config not/the/root/firebase.json`, which is great

Firebase lets you specify an alternative directory for functions, as per the example json below, which is great

But if you combine them as per the example below, you get `<functions path> is outside of the project directory`. Which isn't especially useful.

Not sure why the protection for functions being outside the project directory matters that much? I can see its trying to be helpful, but in this case its prohibitive. 

**Request:** Can this protection be overridden or removed?

### [REQUIRED] Environment info

**firebase-tools:** 9.14.0

**Platform:** Windows

### [REQUIRED] Test case

I'd like to tidy up my project, something like this:

```
/
  package.json
  .firebase/
      firebase.json
      firestore.rules
      storage.rules
      (etc)
  src/
      functions/
          index.js
      hosting/
          index.html
```

    "functions": {
		"source": "../src/functions"
	},

### [REQUIRED] Steps to reproduce

Run this with the above project dir structure:

`firebase deploy --config .firebase/firebase.json`

### [REQUIRED] Expected behavior

Functions can be deployed

### [REQUIRED] Actual behavior

`Error: ../src/functions is outside of project directory`

**Comment by joehan** [comment]
Hey @trullock, thanks for this suggestion. I really like how organized your proposed directory structure looks! Unfortunately, I chatted with the team about this, and I don't think we want to lift this restriction ATM. We have 2 main reasons we'd like to keep it:
- We semi-regularly see users experience issues caused by putting local dependencies outside of the functions directory. We definitely are unable to support this, and we're concerned that lifting this restriction encourages this even more. We don't want to offer users a foot gun :) 
- We've got some exciting plans for new Cloud Functions/serverless compute features coming in the next few quarters. Removing this restriction would make some of these features much more complicated to implement and support.

Thank you for the thoughtful FR!

**Comment by trullock** [comment]
I appreciate those reasonse, they seem logical.

However, is there a workaround, or would you be willing to have some `--force` switch to support this?

**Comment by samtstern** [comment]
@trullock the only workaround is to make sure that your `firebase.json` file is always in a parent directory of your `functions` code. You could do this with a script like:

```
cp .firebase/config.json ./firebase-config.json && firebase --config=firebase-config.json deploy && rm ./firebase-config.json
```

**Comment by trullock** [comment]
@samtstern haha i mean, yeah theres that, but then the paths inside firebase.json will be "wrong", as in you'd need to write them relative to the root because you are moving it at runtime like so....

I still think this issue deserves to be open, even if "remove the function dir protection" isnt the solution - its still a real problem
