### ISSUE TITLE
400 Error: BadRequest - HTTP request sent to Firebase Local Storage Emulator from Flutter Desktop

### ISSUE THREAD

**Issue by TheSlateAndChalk** [firebase/firebase-tools#3566]
I try to upload image to Firebase local storage emulator from flutter desktop software. I'm using file_selector_windows plugin for file selection.

```
void _openImageFile() async {
  final typeGroup = XTypeGroup(
    label: 'images',
    extensions: ['jpg', 'png'],
  );
  final files = await FileSelectorPlatform.instance
      .openFiles(acceptedTypeGroups: [typeGroup]);
  final file = files[0];
  final fileName = file.name;
  final filePath = file.path;
  final responseFireStorage = await http.post(
    Uri.parse('http://localhost:9199/v0/b/default-bucket/o?name=sample.jpg'),
    headers: <String, String>{
      'Content-Type': 'image/jpeg',
    },
    body: filePath,
  );
  print(responseFireStorage.statusCode);
}
```

Error: 400 BadRequest

**Comment by abeisgoat** [comment]
1) Please use the Github issue template when reporting issues, it helps us a lot.
2) Is there a reason you're not using the [firebase_storage](https://pub.dev/packages/firebase_storage) package?
3) We only test the emulator against a set of known SDKs so this use case is kind of on the fringe, but since it works in prod, I'll look into it.

**Comment by tonyjhuang** [comment]
@TheSlateAndChalk can you provide the error message and the emulator version you are using?

Closing this for now due to inactivity and missing information but feel free to re-open if you have more context to provide.
