### ISSUE TITLE
Emulator export does not find running emulator if emulators were started with NPM script

### ISSUE THREAD

**Issue by michaelyfan** [firebase/firebase-tools#3581]
### [REQUIRED] Environment info

**firebase-tools:** 9.12.1

**Platform:** Windows 10

### [REQUIRED] Test case

Create a new empty directory, run `npm init` and `firebase init` and take defaults (it can be connected to any odd Firebase project you have, I don't think this really matters), then go to `package.json` and add an NPM script that starts the emulators:

```
// package.json
{
  "name": "test-case-1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "emulate": "firebase emulators:start",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```
This is all I needed to reproduce the problem. 

### [REQUIRED] Steps to reproduce

1. In a CLI window (I'm using Powershell), navigate to the project directory and run `firebase emulators:start`
2. In another CLI window, run `firebase emulators:export path_here` and observe that an export works as expected
3. Shut the emulators down, then start them again with `npm run emulate`
4. In another CLI window, run `firebase emulators:export path_here_2` and observe the error message `Error: Did not find any running emulators for project [project name here].`
5. Perform steps 1-4 in any order or combination and observe that emulator export will output this error message if the emulators were started with an NPM script

### [REQUIRED] Expected behavior

Emulator export functions no matter if the emulators were started with `firebase emulators:start` or with an NPM script which starts the emulators.

### [REQUIRED] Actual behavior

If the emulators were started with an npm script (which in turn only runs `firebase emulators:start`), then `firebase emulators:export path_here` outputs the previously mentioned error message.

Full debug log:

```
PS C:\Users\micha\code\recycling_website> firebase emulators:export test_dir_2 --debug
[2021-07-16T20:22:44.728Z] Found locator with mismatched version, ignoring: {"version":"8.20.0","host":"localhost","port":4400}

Error: Did not find any running emulators for project gt-recycling.
```

**Comment by inlined** [comment]
@samtstern Do you have any idea here?

**Comment by samtstern** [comment]
The key line is `[2021-07-16T20:22:44.728Z] Found locator with mismatched version, ignoring: {"version":"8.20.0","host":"localhost","port":4400}`

What's happening here is that you're running two different versions of `firebase-tools`. These can't talk to each other. When you run `firebase` outside an NPM script it resolves to your global install. When you run `firebase` inside an NPM script it looks in `./node_modules/bin` and uses your local install.

So you can do either of these solutions:

1. Make sure your Firebase CLI versions match exactly. Check `firebase --version` and `npx firebase --version` and then make them match.
2.  Instead of using `firebase emulators:export` use `npx firebase emulators:export` to run the export using the locally installed version.
