### ISSUE TITLE
Very slow initial query to Firestore emulator

### ISSUE THREAD

**Issue by jpreynat** [firebase/firebase-tools#3594]
### [REQUIRED] Environment info

**firebase-tools:** 9.13.0

**Platform:** macOS, Ubuntu

### [REQUIRED] Test case

```ts
import * as firebaseTesting from '@firebase/rules-unit-testing';
import type firebase from 'firebase';

let iteration = 0;
let projectId: string;
let testApp: firebase.app.App;

beforeEach(async () => {
    iteration += 1;
    projectId = `test-${iteration}`;

    testApp = firebaseTesting.initializeTestApp({
        projectId,
        databaseName: projectId,
        // @ts-ignore
        storageBucket: projectId,
    });

    testApp.firestore().settings({
        ignoreUndefinedProperties: true,
        // Merge settings to not override settings from initializeTestApp
        merge: true,
    });
});

describe('Firestore initial query', () => {
    it('should be long for the first one', async () => {
        console.time('firstQuery-initial');
        await testApp.firestore().collection('some-collection').doc('some-doc').get();
        console.timeEnd('firstQuery-initial');
        // firstQuery-initial: 8437 ms

        console.time('firstQuery-hot');
        await testApp.firestore().collection('some-collection').doc('some-doc').get();
        console.timeEnd('firstQuery-hot');
        // firstQuery-hot: 36 ms
    });

    it('should be quicker for the second one', async () => {
        console.time('secondQuery');
        await testApp.firestore().collection('some-collection').doc('some-doc').get();
        console.timeEnd('secondQuery');
        // secondQuery: 3055 ms
    });
});
```

### [REQUIRED] Steps to reproduce

Run the test case provided above with the Firestore emulator and actual data.

### [REQUIRED] Expected behavior

As you can see from the logs in the tests above, the very first query `.get()` to the Firestore emulator takes a **huge** amount of time: around 8s on my mac M1 machine.
As reflected in the following logs, when making a subsequent request in the same test that uses the same test app, it only takes a few milliseconds (36 when I ran it).
Finally, as reflected by the second test case, subsequents queries `.get()` using another Firebase test app takes around 3s.

From these tests, it seems that there are multiple things at stake while running the emulator:
- The initial call made by a new Firebase test app to the Firestore emulator, evaluated to around 3s. It looks to me like it could be related to a kind of authentication process for the new app before making new requests. But that still looks pretty long for an emulator. Are there any actual HTTP requests being sent to the actual Firestore infrastructure that could explain this latency?
- The very first connection made to the Firestore emulator by whichever Firebase test app makes this initial request, evaluated to 8 (total time) - 3 (first query for a new app) = 5 seconds, which is even longer.

We noticed this because one of our tests was failing because we use a timeout of 8 seconds for the test. To test the actual behavior of our function, we thus had to make a first initial request to make sure that when our test happens, the Firestore emulator was "hot" and this behavior didn't affect our test results.

Is there any specific reason why both of these steps take so much time?

### [REQUIRED] Actual behavior

It would be great to reduce this latency to the minimum. Given that we are using a new Firebase test app for almost all of our tests, our test suite takes at least `<number-of-tests> * 3s` to be processed, which is definitely not sustainable on the long run.

**Comment by akauppi** [comment]
@jpreynat Could you try otherwise the same but with project id's starting `demo-`?

>Are there any actual HTTP requests being sent to the actual Firestore infrastructure that could explain this latency?

This is exactly why. `test-{123}` are treated as normal project id's by Firebase, but `demo-...` are special, and guaranteed to be "offline".

>Why `demo-`???  It's a notation that GCP uses for "invalid" project names. I find it surprising that it matters to Firebase end users; Firebase normally does protect us from many of the GCP intricacies.

Let's see where the 8400 and 3000 ms may fall.

Other things? Have the emulators fully started, when the tests are run?

My own experience is that Firestore emulation seems to be pretty swift but Cloud Functions emulation takes seconds to start up. However, this is system specific (Docker on macOS is slow; Docker on Windows + WSL2 is faster).

**Comment by jpreynat** [comment]
Thanks for the tip @akauppi, but that didn’t change a thing in the timings.

**Comment by akauppi** [comment]
Such nice quietness.

I plan to study this in more detail, one day, making a breakout of where the time with the initial tests goes. 

In my projects, most initial runs are < 2000ms which I deem tolerable, but in some setups (Docker Desktop for Mac, in particular), times are way worse.

This is ... *interesting*. If someone wants to help in tracking the startup times down, happy to join efforts!

**Comment by akauppi** [comment]
Heads up:

I got my timings under control, by adding a special "warm up" step in Docker Compose.

`emul` step just starts the emulators. `warm-up` depends on it, waits until the Firestore port is opened, then runs the Cloud Functions tests (were timeouts have been a problem, due to cold started functions), once the tests pass, it opens a signalling port to downstream.

My actual tests wait for the port and run, with engines warm.

**Comment by akauppi** [comment]
@jpreynat What would work in your case (Firestore), is placing this in a `beforeAll` block:

```
await testApp.firestore().collection('some-collection').doc('some-doc').get();
```

In my exploration, Firestore warm-up needs to be in both server and client side. As you report, the initial fetch is slow (though 8s is stretching even that!). By having it in the `beforeAll`, you can at least have the hand-shakes done before the tests start.

**Comment by bkendall** [comment]
I'm struggling to get this working in my environment. Could you create a repo as a [minimum viable reproduction](https://stackoverflow.com/help/minimal-reproducible-example) for this? Unfortunately I don't have the time to tinker and get to a setup that displays this behavior, so it would help a ton if you can create one. Thanks!

**Comment by jpreynat** [comment]
@bkendall I won't have time to publish a MVR repo in the 3 days timeframe before the issue is closed.
I'll try to do that as soon as I've got spare time though.

**Comment by bkendall** [comment]
Happy new year! If you've got a bit of time, it'd be great to get a repro case so we can debug more. Thanks!

**Comment by emmerich** [comment]
@bkendall 

Hey Bryan, I'm a colleague of @jpreynat and have been looking at this. I've got an MVP of the issue that I can send though I'm not comfortable uploading it publicly (not sensitive stuff but nothing I'd like uploaded publicly as it contains some of GitBook's Firestore rules stuff) - can I e-mail it over?

Upon further investigation it seems that have a complicated Firestore rules file - that is one that is quite large with multiple collections, functions, logic - is the main source of the problem here.

In my MVP I have the exact same test as @jpreynat posted above. I run the emulator, read a value twice, then reinitialize the emulator with a new projectId and read a value. With a large rules file, we can see the results:

![Screenshot 2022-05-12 at 17 39 44](https://user-images.githubusercontent.com/701222/168114471-bdae3fdb-0313-4889-a649-3a6b7a7f2479.png)

If I swap that complicated rules file out for a simpler one (a single collection without any rules to it):
![Screenshot 2022-05-12 at 17 40 47](https://user-images.githubusercontent.com/701222/168114676-44249036-02a0-4b80-a5aa-5be17939b132.png)

So having a complex rules file seems to be a key part here. Let me know how I can send you the repo.

For more context, and to reply to @akauppi 

> In my exploration, Firestore warm-up needs to be in both server and client side.

Our tests are doing a bunch of Firestore operations like reading, writing, deleting. We want to ensure each test runs in its own sandbox and has a clean version of our test data, so we re-initialize the emulators after each test. I've tried doing something like a warm-up, but it's still adding 1s to each test so not practical.

**Comment by jpreynat** [comment]
Friendly ping @bkendall following @emmerich's comment that provides more details.
It'd be great to reopen the issue for further investigation.

**Comment by akauppi** [comment]
@emmerich I used to have a setup where warm-up (though tedius in itself!) tended to work pretty fine. Not so, any more. Some update changed the behaviour in the way that what used to warm the engine earlier no longer does so. Using 10.8 now.
