### ISSUE TITLE
How to use firebase behind a corporate proxy

### ISSUE THREAD

**Issue by gdespres** [firebase/firebase-tools#36]
Hi,

I try to use firebase-tools behind a corporate proxy and I can't login with command 'init' or 'bootstrap'.
Have you any advice for me ?

G.Després

**Comment by mm-gmbd** [comment]
@drtriumph, I've set the environment variables as mentioned in the request documentation, but still had no success. Wondering if there are others with the same issue?

**Comment by drtriumph** [comment]
Unfortunately I think this is a limitation of the Firebase client that the CLI uses to monitor progress of the upload - the client doesn't pick up the environment variables and so never knows when the upload completes, which means the deploy never gets released. The fix is likely a change in the `firebase` npm module, but unfortunately I can't promise anything soon on fixing that

**Comment by mm-gmbd** [comment]
@drtriumph, I feel like this should be re-opened considering this requires a change in the `firebase` npm module. It being closed, to me, means that it is no longer an issue, but it currently impacts my daily workflow...

**Comment by drtriumph** [comment]
I understand your frustration. The reason the issue is closed on this repo is that there's no code that needs to change in this repo for it to work; the issue is with the `firebase` npm module not `firebase-tools`, and we have a separate, internal method of tracking feature requests for that.

I have passed on your frustration.

p.s. The issue has nothing to do with `request`, which you're right does an awesome job of supporting all sorts of use-cases like this

**Comment by mm-gmbd** [comment]
Ah, I didn't realize that the `firebase` npm module was the one that needed modification -- I was considering forking this repo and implementing! Thanks for passing this along :)

**Comment by maheshbeeravelli** [comment]
This issue solved after adding below line in api.js in firebase-tools:
Code: 
`process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;`

Path:
`C:\Users\<user_name>\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js`
