### ISSUE TITLE
[FUNCTIONS] global variables behaving as locals

### ISSUE THREAD

**Issue by ShaMan123** [firebase/firebase-tools#3675]
### [REQUIRED] Version info

**node:** v12.14.0

**firebase-functions:** 3.14.1 (had to downgrade https://github.com/firebase/firebase-functions/issues/942)

**firebase-tools:** 9.16.3

**firebase-admin:** 9.11.0

### [REQUIRED] Test case

https://github.com/ShaMan123/firebase-error

### [REQUIRED] Steps to reproduce

1. clone https://github.com/ShaMan123/firebase-error
2. cd to functions dir
3. install deps
4. run `npm start -- -- --project <firebase-project-id-or-alias>`
5. invoke the https functions: subscribe, subscribe2, increment

### [REQUIRED] Expected behavior
As stated in this [official video](https://www.youtube.com/watch?v=2mjfI0FYP7Y) global vars should maintain their values.
The global vars `i, j, k` should continue incrementing indefinitely from invocation to invocation.
The vars should be shared by all invactions, should they not?

### [REQUIRED] Actual behavior
The SSE functions `subscribe`, `subscribe2` behave as if they create a local var from the global one. Changing a var doesn't affect the global scope.
The function `increment` behaves as expected though it seems to run in isolation so it doesn't affect the global vars of the other functions. If I understand correctly this behavior is what the video states....

The subscriber functions do not return, they timeout. Is this why the vars don't persist?
Even though, during the invocation the vars change but are not changed on the global scope.

I don't understand if this is design or not but is more than strange.

## How to Proceed?
If this is intentional design I do not understand how to implement SSE with firebase functions

**Comment by inlined** [comment]
Every function runs in isolation from other functions, so you will never be able to share state between `subscribe` and `subscribe2`. What's more, production will spin up more than one container to handle your requests, so different containers for `subscribe` will have different values for your globals. If you need to coordinate state between different functions, you should be using some kind of database. I recommend the [Firebase Realtime Database](https://firebase.google.com/products/realtime-database) since it allows you to propagate state changes almost instantly.
