### ISSUE TITLE
firebase deployment error with npm script 'prepare' 

### ISSUE THREAD

**Issue by ryuseikurata** [firebase/firebase-tools#3743]
### [REQUIRED] Environment info

**firebase-tools: 9.16.5

**Platform: macOS

### [REQUIRED] Test case

https://github.com/ryuseikurata/firebase-functions-deploy-err

### [REQUIRED] Steps to reproduce

1. firebase deploy --only functions --project=anywhare

### [REQUIRED] Expected behavior

- deployment success

### [REQUIRED] Actual behavior

- deployment failure
- functions.config() output => `{}`

### AdditionalInformation
- as npm script's prepare removed, deployment success, but as npm scripts' prepare exists, deployment fails
- if you configure nodejs10, deployment success even if  npm scripts' prepare exists
https://github.com/ryuseikurata/firebase-functions-deploy-err/blob/main/functions/package.json

**Comment by joehan** [comment]
Hey @ryuseikurata, sorry to hear that you are having trouble. Some background here:

Under the hood, when you deploy a Cloud Function, we run a Cloud Build job to create the image that your function will use. This job runs through the [npm lifecycle](https://docs.npmjs.com/cli/v7/using-npm/scripts#life-cycle-operation-order), which will run `prepare`. You set a `prepare` script that depends on `firebase`, but you don't have firebase listed as a dependency in your [package.json](https://github.com/ryuseikurata/firebase-functions-deploy-err/blob/main/functions/package.json#L17), so this step errors out.

To fix this, you just need to add a dependency on firebase: 
```
"dependencies": {
    "firebase": "^9.16.0",
   ...
  },
```

I'm not sure why this was working on Node 10 previously - maybe the base image already had `firebase` installed. However, since you depend on it, you should explicitly add it to your dependencies.
