### ISSUE TITLE
Installing firebase-tools fails

### ISSUE THREAD

**Issue by gigocabrera** [firebase/firebase-tools#389]
I'm installing firebase-tools for the first time and it is failing. Am I missing something?

Here's the command i'm using 
`npm install -g firebase-tools`

npm version --> 5.1.0
node version --> 6.11.0
OS --> Windows 7 Professional SP1

Attached is the log produced:

[firebase-tools-error.pdf](https://github.com/firebase/firebase-tools/files/1131854/firebase-tools-error.pdf)

**Comment by laurenzlong** [comment]
Looks like it might a permission thing, since the last line from the error log is: 4400 error Please try running this command again as root/Administrator.

Not sure the exact steps for doing that on Windows, so you would have to look that up. Could you file a [support ticket](https://firebase.google.com/support/) if you have further problems?
