### ISSUE TITLE
Auth Emulator Email Link broken

### ISSUE THREAD

**Issue by steeling** [firebase/firebase-tools#3906]
The auth emulator returns a link where the domain is set to localhost. This should be configurable so that I can point it to any url of my choosing, particularly so that I can make this work with iOS and Android apps.

Further, there is little to no documentation on what the API is within the firebase.json for the emulator fields.

**Comment by yuchenshi** [comment]
The Auth Emulator [does not support email-link sign-in on iOS and Android apps at all](https://firebase.google.com/docs/emulator-suite/connect_auth#sign-in_via_email_link_on_mobile) due to technical limitations. Even if we could fix the the hostname, it will only open on the mobile web browser instead of handled in the apps. The only workaround is to test using a real Firebase project for now.

The emulator-related fields in `firebase.json` are documented at: https://firebase.google.com/docs/emulator-suite/install_and_configure#configure_emulator_suite

**Comment by MartinReiche** [comment]
Hi,

I am having a related isssue. I cannot open the Emulator Email sign In Link in the browser. Chrome asks me with which application I want to open the link. Firefox says: Firefox doesn’t know how to open this address, because one of the following protocols (http) isn’t associated with any program or is not allowed in this context.You might need to install other software to open this address.

I am running the latest version of firebase-tools (10.2.2). Am I Missing something?
