### ISSUE TITLE
node10 is no longer supported by cli-table

### ISSUE THREAD

**Issue by tachibanayu24** [firebase/firebase-tools#3914]
Thank you for always providing such great libraries.
I know that you have been speedy in responding to issues related to cli-table, which is a dependent library.

In a recent release, you have updated cli-table to 0.3.8, which appears to have a issue.

The cli-table seems to have unlisted node10 from 0.3.7.
However, firebase-tools used to be available for node10.

Is there a problem if I pin the cli-table to 0.3.6 instead of updating it to 0.3.8?
Thank you for your help.

### [REQUIRED] Environment info

**firebase-tools: v9.23.0**

**Platform: masOS nad Ubuntu**

### [REQUIRED] Steps to reproduce

1. set node to 10
2. run `yarn add -dev firebase-tools`.
3. you can see the message that node10 is not available

### [REQUIRED] Expected behavior

It should be able to be installed on node10.

**Comment by bkendall** [comment]
I don't love this answer, but it's the one I think I have to settle on: my suggestion is to update your node version, if possible. Node 10 has been deprecated (end of life) for some time now, and 16 is the current version (https://nodejs.org/en/about/releases/). 

I'm actually actively working on dropping support for Node 10 in the CLI, so that day is coming soon. Even if this _wasn't_ the case, the package dropping support on a patch version is a bummer because even older versions of the CLI would have trouble with this.

I don't personally use `yarn`, but I do believe there's ways to ignore `engines` requirements if necessary and would encourage you to do so. I don't believe `cli-table` doesn't _work_ on node 10, it just advertises that it doesn't support it. There might be some code that doesn't work, but I've not gone digging.

If you have the ability to re-pin a dependency in your environment, that'd be cool, but unfortunately I think I need to be a little more forward-looking for this tool as a whole.

**Comment by tachibanayu24** [comment]
@bkendall 
Thanks for the answer!
The old version of node is I've been having problems with in my project, so I think you're really right.

I'm going to work on getting firebase-tools working on node10, even if I have to force it, and then update the node version as soon as possible.
Thank you very much.
