### ISSUE TITLE
Deployment of firebase cloud functions copies the entire directory into the Container Registry Image

### ISSUE THREAD

**Issue by raul-madrigal** [firebase/firebase-tools#3982]
### [REQUIRED] Environment info

**firebase-tools:** 10.0.0

**Platform:** macOS Big Sur 11.6

### [REQUIRED] Test case

According to the [Lifecycle of a background function](https://firebase.google.com/docs/functions#lifecycle_of_a_background_function) the following happens during a function deployment.
```
The Firebase CLI creates a .zip archive of the function code, which is then uploaded to a Cloud Storage bucket (prefixed with gcf-sources) in your Firebase project.
```

When using the [Typescript example](https://firebase.google.com/docs/functions/typescript), we can see in the `tsconfig` the `"outDir": "lib"` and the `package.json` pointing to `"main": "lib/index.js",`, which its correct so far. The problem is when we go to GCP Cloud Registry and pull any function image and inspection it. 

<img width="1443" alt="Screen Shot 2022-01-03 at 6 23 50 PM" src="https://user-images.githubusercontent.com/30184031/147994165-737d59c9-d8a9-4df3-947c-a5386496140a.png">

My entire source code is being copied to the image instead of only copying the generated bundle from `lib/index.js`

### [REQUIRED] Steps to reproduce

1. Configure Typescript project.
2. Deploy a function.
3. Pull the docker image from the Cloud Registry.
4. Run the image and check its contents.

### [REQUIRED] Expected behavior

Cloud Registry Image contains only the lib folder.

### [REQUIRED] Actual behavior

Cloud Registry Image contains the entire source code in all functions deployed.

**Comment by colerogers** [comment]
Hi @raul-madrigal thanks for your first issue in Firebase!

This behavior is actually working as intended. As part of the deployment process, we build the typescript, upload the entire function source code (the whole directory), then call the GCF API to build the individual containers/functions using the upload from the previous step.

Is your feature request to delete the `src` directory before upload?

**Comment by raul-madrigal** [comment]
@colerogers The issue I'm seeing is regarding space and budget, for example, I have 100+ functions being deployed with this same project, every function has its own HTTP trigger. My surprise when I went to the GCR is that all the 100+ functions are taking ~500mb of disk space. 

When using the `firebase.json` inside the `hosting` key there is a key array to ignore files when uploading but I haven't found anywhere documented the same for `functions` to prevent this to happen.

**Comment by colerogers** [comment]
@raul-madrigal sorry for the late reply, we've been discussing this internally. So we think that trying to optimize storage costs in your case won't really do much since you're charged per GB. Per the Cloud Storage pricing,

> The price for Standard buckets in a multi-region is about $0.026 per GB per month.

But, if your really wanted to play around with it, we do seem to allow the `ignore` key inside `firebase.json` inside the `functions` object. It's not really documented anywhere and I was a bit surprised by this, I'll make a push internally to get that published somewhere. Additionally, if you do ignore files on your own, you need to make sure to add `node_modules` to that list on your own. [Here's the spot in the CLI where we check for the `ignore` key if your interested.](https://github.com/firebase/firebase-tools/blob/a8ccc7afec817389a7ab5565a1bbf59f24bd68bd/src/deploy/functions/prepareFunctionsUpload.ts#L70)

**Comment by raul-madrigal** [comment]
@colerogers I tried using the ignore key but I'm still seeing the exact same files in the Docker image. 
<img width="1061" alt="Screen Shot 2022-01-22 at 3 49 06 PM" src="https://user-images.githubusercontent.com/30184031/150656552-5a0b620e-a2e1-4a25-86bf-0d589fc0af92.png">

I even used the exact same default array is in the code you sent and doesn't ignore the `node_modules` dir.

**Comment by colerogers** [comment]
@raul-madrigal Interesting, can you try using the glob pattern like in the [hosting example](https://firebase.google.com/docs/hosting/full-config#specify-files-to-deply)? Something like,

```
"functions": {
    "predeploy": "npm --prefix \"$RESOURCE_DIR\" run build",
    "source": "functions",
    "ignore": [
      "**/node_modules/**",
      "**/.git/**",
      "**/src/**",
      "some-inner-file.txt"
    ]
 }
```

I used this as an example and I'm able to get these files ignored from the source deploy.

**Comment by raul-madrigal** [comment]
@colerogers thanks for the suggestion, 
<img width="1391" alt="Screen Shot 2022-02-02 at 9 17 13 AM" src="https://user-images.githubusercontent.com/30184031/152182337-0b7bb237-6214-4542-8af9-9d159010efea.png">

Now I'm seeing fewer files, but `node_modules` is still in there.

**Comment by colerogers** [comment]
@raul-madrigal Instead of checking out the container image, can I ask you to look inside the uploaded zip of the functions directory? It will be easier to debug what is actually being sent to Google Cloud from the CLI. The zip is located in a Cloud Storage Bucket titled `gcf-sources-${project-number}-${region}`. Simply download the zip and inspect in locally. If that directory contains the `node_modules` then the CLI isn't actually ignoring on upload.

You can probably get away with ignoring development files, but these are usually very small and you won't notice any reasonable difference in size.

**Comment by raul-madrigal** [comment]
@colerogers thanks for helping out, by inspecting the zip file I can see only the files I'm not ignoring, `node_modules` is not part of it, meaning the CLI does work as expected.
