### ISSUE TITLE
TRANSACTION TOO BIG error for batch deletes of 500

### ISSUE THREAD

**Issue by tfang17** [firebase/firebase-tools#3992]
### [REQUIRED] Environment info

Firebase 9.5.0
Firebase Tools 2.0.1
MacOS

### [REQUIRED] Test case

```let batch = admin.firestore().batch()
            for (let requestDoc of chunk) {
                batch.delete(requestDoc.ref)

                failedRequestsCount += 1
            }
            await batch.commit()
```

### [REQUIRED] Steps to reproduce

Delete a batch of 500 documents.

### [REQUIRED] Expected behavior

Successful delete.

### [REQUIRED] Actual behavior

Received error `Error: 3 INVALID_ARGUMENT: Transaction too big. Decrease transaction size.`. Same as https://github.com/firebase/firebase-tools/issues/1036

**Comment by abeisgoat** [comment]
Is this against the Cloud Firestore emulator or production service?

**Comment by tfang17** [comment]
Production. Transaction size is well below the 10 MB limit as well.

**Comment by tfang17** [comment]
Any updates on this @abeisgoat

**Comment by yuchenshi** [comment]
Thanks for filing the issue! FYI, this is the repo for Firebase CLI and your question seems more related to Firestore SDK / Backend.

For production issues like this, Firebase Support will be better equipped to help you since they'll have access to your project information. Please contact Support instead.
