### ISSUE TITLE
[Firestore] [Functions]

### ISSUE THREAD

**Issue by AdamTeodoro** [firebase/firebase-tools#4185]
On execute:
`firebase deploy --only functions `

i receive the error:
```
Error: Error occurred while parsing your function triggers.

TypeError: Cannot read properties of undefined (reading 'INTERNAL')
```

**Comment by AdamTeodoro** [comment]
i solved the problem, thanks for yours commentarys!

**Comment by doppio** [comment]
@AdamTeodoro Can you please share how you solved this, for other people like me with the same issue?

**Comment by Niron68** [comment]
@doppio I got the same problem and it was my `initializeApp` that was not correctly imported. Instead of `import { initializeApp } from 'firebase-admin/app' i wrote 'import { initializeApp } from 'firebase-admin''`. Hope it can help you with this problem, i search for like 3 hours before undersanding that --'

**Comment by Zjaaspoer** [comment]
@Niron68 TY! This solved it for me too 🙏

**Comment by AdamTeodoro** [comment]
Para resolver esse problema eu copiei a minha pasta src para uma outra pasta apaguei tudo, comecei uma novo functions project e substitui a src pela minha src antiga XD

**Comment by AdamTeodoro** [comment]
For solve this problem i copy the folder src for other location, and i start new functions project and i past my src copied over the src from the new project created.
