### ISSUE TITLE
Having issue with deploy

### ISSUE THREAD

**Issue by thandaanda** [firebase/firebase-tools#43]
Progress hangs up after deploying few files.

Preparing to deploy Public Directory...
progress: 43%Deploy Error - socket hang up 

Preparing to deploy Public Directory...
progress: 14%Deploy Error - read ECONNRESET

**Comment by katowulf** [comment]
We’re in the process of upgrading our hosting tools and asset storage. There may be some unavailability for deploys. There is just a very large amount of data throughput right now with the combined user access, deploys, and our internal upgrades. If this isn’t mission-critical, I’d recommend trying again later tomorrow. If it is critical, you may want to try again in a couple hours.

Sorry for the annoyance. It should be smooth sailing once this transition is complete and we should be back at our reliable uptime for this service. Since this is unrelated to the CLI tools, closing this issue.
