### ISSUE TITLE
Version >10.2.0 does not run my test data code when running firebase emulators:start

### ISSUE THREAD

**Issue by zakton5** [firebase/firebase-tools#4343]
### [REQUIRED] Environment info

**firebase-tools:** 10.2.0

**Platform:** macOS

### [REQUIRED] Test case

In my `index.ts` I have the following code. admin.initializeApp() gets called (I know this because the app starts and the logs say so). All of my functions are properly exported and active. But my code between initialize and the exports doesn't run at all. Even if I add console.logs all over that file none of them actually do anything. I have confirmed that the transpiled JS code is correct. This one has me stumped. No clue what could be going on here.

```ts
import * as admin from 'firebase-admin';
import { createTestData } from './scripts/seed-test-data';

admin.initializeApp();
const firestore = admin.firestore();
firestore.settings({ timestampsInSnapshots: true, ignoreUndefinedProperties: true });

// Create test data when the emulator is running
if (process.env.FIRESTORE_EMULATOR_HOST?.endsWith('8080')) {
  createTestData(); // Executes on 10.1.5, but not on >10.2.0.
}

// Exports for cloud functions and API
export * from './app'; 
```

### [REQUIRED] Steps to reproduce

1. Using firebase-tools >10.2.0, add some console.log into the index file.
2. Observe that the console.log output is not displayed in the terminal.

### [REQUIRED] Expected behavior

My test data code runs on startup.

### [REQUIRED] Actual behavior

It almost seems like any code meant to execute immediately on startup is ignored.

**Comment by yuchenshi** [comment]
@taeold Looks like this may be related to env vars in functions. Any thoughts?

**Comment by littletime** [comment]
Same issue here, MacOS also, using firebase-tools 10.4.2

**Comment by taeold** [comment]
@zakton5 One change we made in recent versions of the Functions Emulator was to "lazily" load cloud functions. Before, all functions were loaded at startup - now they are loaded only on first request.

Sorry for unknowingly pushing out a breaking change here.

Though I'm a bit concerned about this "init" pattern, e.g. IIUC your `createTestData` function will be called once per function. In fact, if you put sufficient load on the emulated function, you can probably have it run multiple times per function (e.g. when the Emulator decides to spin up a new process to handle the load). How do you handle for this situation?

(I'm thinking whether there are other patterns for running INIT code for seeding test data since 's probably "safer" for you to rely on some other process to run the "seed my data" script rather than rely on the function emulator process to do so. Please share any idea that you might have)

**Comment by zakton5** [comment]
@taeold Very good to know! Thanks for that info. I'm not a fan of this init pattern either, but I wasn't able to find any examples on how to do something like this properly. I handle the multiple runs by manually checking if test data already exists to prevent duplicate data creation. I'll attempt to move this code outside of the emulator process and run it separately.

**Comment by trex-quo** [comment]
I have a similar issue here where I am using a third party secrets library Doppler, and attempt to load those in the top-level. The command is `doppler run -- firebase emulators:start`. It works fine on 10.1.4 but breaks if I upgrade any further, as it does not end up loading in the secrets by the time the functions try to read them in, and I get a "cannot read property 'example_secret' of undefined".

**Comment by zakton5** [comment]
@taeold A perfect solution would be to use something like `firebase:exec` but have it work with already running emulators instead of starting them up and immediately shutting them down.
