### ISSUE TITLE
New .env-based configuration is not available on functions start in emulator

### ISSUE THREAD

**Issue by uvesten** [firebase/firebase-tools#4361]
I've spent quite a bit of time to move from the old `functions.config()` system to the new `.env`-file based config for better developer ergonomics. I'm very, very disappointed that this "feature" was released at all in its current state, since it's a major regression compared to `functions.config()`. 

That an environment variable needs to be set in the environment _before_ starting to execute an arbitrary function, that should be obvious. The config values _might_ be available inside `runWith(), .onCall()` etc, but that's not enough. Please fix this or release a new major version, removing support until you can get it right. 

My case: 

Using a config variable to decide which region to deploy functions to fails, since the  `.env`-based config is not available on function deploy. 

Example: 

```
export const copy = region(process.env.DEPLOY_REGION)
  .runWith()
  .https.onCall(
```

breaks, because the environment variable does not exist... (It's set correctly in the `.env` file)

```
export const copy = region(functions.config().deploy.region)
  .runWith()
  .https.onCall(
```

Works well.  

It's not OK to release a new feature in this state... Please fix or un-release it asap

(Reported to both here and in https://github.com/firebase/firebase-functions/issues/1065 because I don't know which project is responsible for this change)

**Comment by DibyodyutiMondal** [comment]
While they are working on a change, I discovered the two places where we can insert our required env variables, both for the emulator, and deployments.

I dove into the node_modules and changed the code at the locations in the images below. All it does is add the `NODE_OPTIONS` environment variable. The alternative is to append `.js` and `/index.js` to imports as necessary.
(this is specific in my case - you can insert your own variables here as required)

And it works like a charm with nothing more needed.

I have not been able to deploy this on functions v2, but I think that's because of some other issue, not this.

(the location of the file I am editing is visible in the left sidebar)

![deploy-patch](https://user-images.githubusercontent.com/50345677/160052527-0793856a-79f7-4656-9ce6-bd859897eba0.png)
![emulator-patch](https://user-images.githubusercontent.com/50345677/160052524-f8e7c0d1-73f2-4925-90b6-ab0eea1ff72d.png)

**Comment by taeold** [comment]
Other issues that touches on this problem:

https://github.com/firebase/firebase-functions/issues/1058
https://github.com/firebase/firebase-functions/issues/1044

Pasting a response I posted in another issue:

> As both of you have already found out, we are intentionally not including user-defined environment variables when parsing your source code to discover your functions. This limits their use when compared to functions config.
>
> We are preparing something new that digs into exactly this problem -stay tuned. Until then, I'd suggest that you continue to rely on functions config if need environment-aware logic when deploying your functions.

Since this is a common point of confusion, I'm going to try to consolidate our response in a single issue. Arbitrary going to pick the earliest reported issue (https://github.com/firebase/firebase-functions/issues/1044) as our single source of truth. Let's continue our discussion there.

**Comment by inlined** [comment]
See https://github.com/firebase/firebase-functions/issues/1084 for our plans around this area.
