### ISSUE TITLE
Logs not showing without at least one function invocation | Firebase Functions | Emulator | Mac

### ISSUE THREAD

**Issue by thesrs02** [firebase/firebase-tools#4410]
### [REQUIRED] Environment info

**firebase-tools:** 10.6.0
**Platform**: MacOS Monterey 12.3
**Environment:** Node v17.8.0

### [REQUIRED] Test case
```
const { CronJob } = require("cron");

new CronJob("* * * * *", function () {
    console.log("Refreshing...");
}).start();
```

### [REQUIRED] Steps to reproduce

1 - Firebase init with functions
2 - Install node-cron
3 - Use the code shared above without un-commenting the function code
4 - Move to functions folder and run `npm run serve`

### [REQUIRED] Expected behavior
The console log should appear in the terminal and should also update the value on save / value change.

### [REQUIRED] Actual behavior
The log statement "Refreshing..." will not appear in the terminal unless you invoke the helloWorld function first.

**Comment by louis030195** [comment]
Same here when updating from firebase-tools 9.23.0 to 10.9.2

firebase-tools: 10.9.2
Platform: MacOS Monterey 12.3.1
Environment: Node v14.17.3

`index.ts`
```ts
console.log("hello");
```

Nothing show in the logs

**Comment by bkendall** [comment]
There's things the CLI does around wrapping `console.log` and how we load Functions code that might have this effect. @colerogers might be best to shed some light

**Comment by colerogers** [comment]
A while back we changed how functions are discovered and it looks like that might have changed this behavior. This no longer matches what production does, so I'm going to bring this up internally to see what steps forward we should take. Thanks for reporting this!

**Comment by taeold** [comment]
I think this issue is best explained in this comment:

https://github.com/firebase/firebase-tools/issues/4343#issuecomment-1077881832

It's likely that your code is running, but the output is no longer shown to you. I'm generally worried about this pattern though - IIUC and based on my knowledge of the Functions Emulator, this means that the code you wrote to setup a cron job will run for each function that you've defined (because each functions runs on a separate process).

Would love to hear more about your use case and work together to get to the bottom of your issue.

**Comment by thesrs02** [comment]
Hi, still have this issue and am surprised that no one else is running into this issue.
