### ISSUE TITLE
runWith options are not applied after functions deployment

### ISSUE THREAD

**Issue by xar** [firebase/firebase-tools#4418]
### [REQUIRED] Environment info

**firebase-tools:** 10.3.0

**Platform:** macOs, Ubuntu

### [REQUIRED] Test case

After updating `runWith` options for cloud function probably without modifying function code and running `firebase deploy --only functions` we don't see updated runtime options in google cloud console. Cloud function which has modified options still shows old configuration of `memory: 2GB` and `minInstaces: 1` even we have changed it to 256mb & 0. 

### [REQUIRED] Steps to reproduce

- Create cloud function with `runWith({ memory: 2GB, minInstances: 1 })`
- Deploy
- Verify that it's deployed with those options in console.cloud.google.com
- Change runtime options to `runWith({ memory: 256MB, minInstances: 0 })`
- Check cloud console

### [REQUIRED] Expected behavior

- runWith get propagated correctly

### [REQUIRED] Actual behavior

- runWith options doesn't get propagated

**Comment by joehan** [comment]
Hey @xar, could you update to the latest version of firebase-tools and try this again? We recently caught and fixed a bug that caused a similar problem to what you are experiencing here.

**Comment by xar** [comment]
Sorry for late update on the issue - I have tried to run with latest version of `firebase-tools - 10.7.0` but without success. Specifically I have updated `runWith` of function to `.runWith({ memory: '2GB'. minInstances: 1 })` - this got updated correctly and I can see updated options in gcloud console. But when I change runWith back to `.runWith({})` function doesn't get updated...

**Comment by joehan** [comment]
@inlined Could you take a look at this? IIRC, we intentionally tried to handle this case correctly and it seems like it may have regressed.

**Comment by inlined** [comment]
`.runWith({})` does nothing. We only reset values that are explicitly set to `undefined`. For better or worse, this is to preserve changes made out of band in the Google Cloud console. So if you said:

````
runWith({ memory: "2GB", minInstances: 0 })
```

or 

```
runWith({ memory: "2GB", minInstances: undefined })
```

we'd reset the value, but if you just remove "minInstances" from the object we don't know (when looking only at your current source code) whether you stopped wanting minInstances or whether you configured minInstances using other tools like `gcloud` or the website. We opt for ignoring what might have been out-of-band changes because your case can be fixed once yet having your out-of-band changes overwitten on every deploy can be maddening
