### ISSUE TITLE
Aliased .env file skipped erratically during function deployments

### ISSUE THREAD

**Issue by trex-quo** [firebase/firebase-tools#4656]
### [REQUIRED] Environment info

**firebase-tools: 11.0.1**

**Platform: macOS**

### [REQUIRED] Test case

`firebase deploy --only functions:functionName`

### [REQUIRED] Steps to reproduce

1. Create a `.firebaserc` file in `functions` directory and assign an alias for the project
```
{
  "projects": {
    "default": "project1",
    "staging": "project2",
    "prod": "project1"
  },
  "targets": {}
}
```
2. Create a `.env` file in the functions directory for the appropriate alias e.g. `.env.prod`

### [REQUIRED] Expected behavior

I see the output `i  functions: Loaded environment variables from .env, .env.prod.` every time I deploy

### [REQUIRED] Actual behavior

When I deploy, sometimes I see
`i  functions: Loaded environment variables from .env.`

and sometimes I see 
`i  functions: Loaded environment variables from .env, .env.prod.`

Recently, I did two back-to-back deployments with no changes to the environment whatsoever and saw different behavior for each.

I would expect the environment variables to be loaded from `.env.prod` on every single deployment, seeing that the project is selected by alias in the predeploy script every time, and the `.env.prod` file is populated within the predeploy script every time. The inconsistent fetching of environment variables has lead to production function deployments with all environment variables missing. I believe the only solution in the meantime is to redundantly output our environment variables into the `.env` file for whichever environment we are deploying to.

**Comment by trex-quo** [comment]
My temporary workaround has been to make sure that our predeploy script populates both the `.env` and `.env.{{alias}}` files with that project's environment variables. That way there is no chance of the environment variables being omitted. This defeats the purpose of the aliased .env files in my opinion, but the fix works for now.

**Comment by DibyodyutiMondal** [comment]
I can see why https://github.com/firebase/firebase-functions/issues/1084 (function params) would make sense, as well as several advantages it brings to the table over dotenv.

However I strongly agree with https://github.com/firebase/firebase-functions/issues/1044#issuecomment-1080433233.

If we want to use file-based environment config, we should have full support for it. As it stands, `.env` is not available during deploys/emulator startup, only at run-time. While this is fine for most use cases, it's a no-go for any global objects that depend on environment variables. [Firebase documentation](https://firebase.google.com/docs/functions/tips#use_global_variables_to_reuse_objects_in_future_invocations) mentions that it's a good optimisation to have. 

For example, let's say I want to connect to an elasticsearch cluster. Since I know that every function will need to connect to elasticsearch, then I can optimise by initializing the elasticsearch client library globally, only once, instead of inside every function. To do that, I would need the node address and the api key, which I want to come from `.env` files.

However, that option has been snatched away from me because of the way firebase-tools works with dotenv. To work around this problem, I have to implement a initialise-if-required-then-return logic for every shared service that I need (we have elasticsearch, twilio, and some more API tools we integrate with).

For reference, let me illustrate how one has to work around firebase-tools in this scenario:

#### What code ideally looks like
```typescript
// file: environment.ts
export const env = {
  ES_NODE: process.env['ES_NODE'],
  ES_API_KEY: process.env['ES_API_KEY']
};

// file: elasticsearch.ts
export const esClient = new elasticSearhcClient({
  node: env.ES_NODE,
  auth: { apiKey: env.ES_API_KEY }
});

// file: index.ts
export const someFunction = firebaseFunctions.https.onCreate(async (req, res) => {
  // search for documents
  esClient.search()

  // ...more work
})
```

#### What we actually have to write just to make it deploy/run locally:
```typescript
// file: environment.ts
let env;
export function getEnv() {
  if (!env) {
    env = {
      ES_NODE: process.env['ES_NODE'],
      ES_API_KEY: process.env['ES_API_KEY']
    }
  }
  return env;
}

// file: elasticsearch.ts
let esClient;
export function getEsClient() {
  if (!esClient) {
    env = getEnv();
    esClient = new elasticSearhcClient({
      node: env.ES_NODE,
      auth: { apiKey: env.ES_API_KEY }
    });
  }
  return esClient;
}

// file: index.ts
const someFunction = firebaseFunctions.https.onCreate(async (req, res) => {
  // search for documents
  const esClient = getEsClient();
  esClient.search()

  // ...more work
})
```


Yes, it is not complex at all, but it's not straightforward either. 
Currently, for the emulator, we have deliberately decided to not load user environments during the parsing phase:
https://github.com/firebase/firebase-tools/blob/7258fca2687e17d19cf8f7104bae2dbce30669d8/src/emulator/functionsEmulator.ts#L499-L514

I have to go into my firebase-tools installation folder after every install/update of the firebase cli and edit javascript file to include my environment variables.

I have not yet tried a production deploy yet. I'll update once I have tried it.

**Comment by blidd-google** [comment]
This issue is quite stale but wanted to check in - I'm unable to reproduce this issue using firebase-tools v13. Are folks still having issues with this? If not, I'll go ahead and let the bot close this one.
