### ISSUE TITLE
Get an error: An unexpected error has occurred, when try to get runtimeconfig(firebase functions:config:get)

### ISSUE THREAD

**Issue by maylorsan** [firebase/firebase-tools#4706]
### Environment info

**firebase-tools:** 11.2.0

**node**:  16.15.0

**Platform:** macOS

### Test case

Run command:
```
firebase functions:config:get
```

Get error:
<img width="572" alt="Screen Shot 2022-07-04 at 11 38 29" src="https://user-images.githubusercontent.com/51034456/177116608-c136d132-d2a8-4458-9fac-b8726e2d1c2a.png">

firebase-debug.log
```
[debug] [2022-07-04T08:09:43.150Z] >>> [apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1/projects/*project_id*/configs/env/variables/backups/project_id [none]
[debug] [2022-07-04T08:09:43.209Z] TypeError: Cannot read properties of undefined (reading 'map')
    at traverseVariables (/usr/local/lib/node_modules/firebase-tools/lib/functionsConfig.js:90:38)
    at Object.materializeConfig (/usr/local/lib/node_modules/firebase-tools/lib/functionsConfig.js:95:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
    at async Object.materializeAll (/usr/local/lib/node_modules/firebase-tools/lib/functionsConfig.js:105:5)
    at async Command.actionFn (/usr/local/lib/node_modules/firebase-tools/lib/commands/functions-config-get.js:32:20)
[error] 
[error] Error: An unexpected error has occurred.
```

**If downgrade to firebase-tools version 10.2.2 it is fixed.**

### Steps to reproduce

Run commands:
```
firebase login
firebase init
firebase functions:config:get
```

### Expected behavior

Getting variables from runtimeconfig

### Actual behavior

Getting an error

**Comment by haroldadmin** [comment]
I can confirm that I get this error too, but only on CI builds in GitHub Actions. It works fine locally.

Here's a screenshot of the error:
<img width="651" alt="Screenshot 2022-07-04 at 2 47 09 PM" src="https://user-images.githubusercontent.com/24315306/177123985-6734e945-7508-474a-831c-256d789c7d30.png">

I can confirm the following:
- Firebase CLI is installed on the workflow runner
- The `TOKEN` environment variable is correctly set to the token generated using `firebase login:ci`
- This command used to run successfully on CI until a few days ago.

Other solutions I tried that did not work:
1. Use the `>` operator instead of `>>` to write the `.runtimeconfig.json` file. 
2. Use a Node.js script to run the `firebase functions:config:get --token $TOKEN` command.
3. Use an NPM script to execute the same command.

I'm out of ideas at this point. Any help would be greatly appreciated.

**Comment by haroldadmin** [comment]
I can confirm the presence of this issue in my CI environment for `firebase-tools` version 11.2.0, 11.1.0, as well as 10.9.2.

**Comment by betocardenas94** [comment]
Yep, firebase bug with Firebase CLI Version 11.2.0.
Downgrade is the best option until they solve this. 
Run:
`npm install -g firebase-tools@^10.2.2`

**Comment by maylorsan** [comment]
Yes, the problem happens when there is a config in which there is not a single variable.

Corrected it in https://github.com/firebase/firebase-tools/pull/4707
