### ISSUE TITLE
getIdToken(true) is not returning a new token

### ISSUE THREAD

**Issue by octaviodivy** [firebase/firebase-tools#4856]
### [REQUIRED] Environment info

**firebase-tools:** 11.5.0

**Platform:** Windows 10

**Node:** 14.20.0

### [REQUIRED] Test case

```javascript
let token1 = await firebase.auth().currentUser.getIdToken(true)
await firebase.auth().currentUser.updateEmail("test@test.com")
let token2 = await firebase.auth().currentUser.getIdToken(true)

token1 == token2
```

### [REQUIRED] Steps to reproduce

On localhost, against the Auth emulators:

- In a Firebase project with firebase Auth working, authenticate with phone
- Invoke the getIdToken(true) to force refresh the token
- Update e-mail (which forces token to be revoked)
- Invoke the getIdToken(true) to force refresh the token

### [REQUIRED] Expected behavior

- Being able to retrieve a new valid token as the old one had been revoked by e-mail update

### [REQUIRED] Actual behavior

Code running on emulator:
![image](https://user-images.githubusercontent.com/87962027/183992678-21317474-00ab-4280-ba01-0c12f78e7544.png)

Code running on firebase production:
![image](https://user-images.githubusercontent.com/87962027/183992957-d0b013c2-4bfe-4837-af48-8958b1a8e22f.png)

**Comment by diegodulval** [comment]
The same is happening here, but I use the macOS operating system.

**Comment by lisajian** [comment]
I'm on macOS, firebase-tools v11.5.0, node 14 and using JSSDK v9 (it seems like you're using v8 based on the syntax and that I know of, the refresh logic hasn't changed significantly since v8), but unfortunately, I'm not able to reproduce this.

Could I get a bit more information about how you're doing phone auth? Are you also seeing any errors in your console when you did any of the steps (e.g. during phone auth, while refreshing the token, etc)?

**Comment by zhebil** [comment]
Have the same issue

**Comment by petem24** [comment]
Having same issue here. Token is revoked and I cant generate new ones

**Comment by taeold** [comment]
Hi folks. If you are seeing similar issue, please feel free to file a new issue. Would appreciate if you can include reproduction steps or firebase debug logs along with the issue. Thanks.
