### ISSUE TITLE
Storage Emulator Timeout

### ISSUE THREAD

**Issue by vdiaz1130** [firebase/firebase-tools#4908]
### [REQUIRED] Environment info
node -v v18.0.0
npm -v 8.6.0

**firebase-tools:**
firebase --version: 11.7.0

**Platform:**
OSX version 10.15.7

I came across this researching my problem:
Re: https://github.com/firebase/firebase-tools/issues/4741#issuecomment-1215750676

This was working in a prior version. I updated a few libs so am hoping this is trivial (don't want to revert if possible).

### [REQUIRED] Test case
```
    import * as fs from 'fs';
    import * as admin from 'firebase-admin';
    import { connectStorageEmulator, getDownloadURL, getStorage, ref, uploadBytes, uploadBytesResumable } from 'firebase/storage';
    import { initializeApp } from '@firebase/app';

    const PROJECT_ID = 'XXX';
    const firebaseConfig = {
      ...
    };

    const serviceAccount = {
      ...
    }

    const app = initializeApp({
      ...firebaseConfig,
    });

    admin.initializeApp({
      credential: admin.credential.cert(serviceAccount),
      storageBucket: `${PROJECT_ID}.appspot.com`
    });

    const auth = admin.auth();
    const storageApp = getStorage(app);
    connectStorageEmulator(storageApp, 'localhost', 9199);

    function uploadResumable(name: string, path: string) {
      const p = new Promise<boolean>((resolve, reject) => {
        const storageRef = ref(storageApp, `media-library/${name}`);
        const data = fs.readFileSync(`${__dirname}/${path}`);

        console.log('About to upload resumable file', `${__dirname}/${path}`);
        const uploadTask = uploadBytesResumable(storageRef, data);
        
        uploadTask.on('state_changed', (snapshot) => {
          const progress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
          console.log('Upload is ' + progress + '% done');
        },
        (e) => {
          console.log('Failed to upload file: ', e);
          reject(e);
        },
        () => {
          getDownloadURL(uploadTask.snapshot.ref).then((downloadURL) => {
            console.log('File available at', downloadURL);
          });
          console.log('File upload complete', `${__dirname}/${path}`);
          resolve(true)
        });
      });

      return p;
    }

    function uploadNoneResumable(name: string, path: string) {
      const p = new Promise<boolean>((resolve, reject) => {
        const storageRef = ref(storageApp, `media-library/${name}`);
        const data = fs.readFileSync(`${__dirname}/${path}`);

        console.log('About to upload none-resume file', `${__dirname}/${path}`);
        uploadBytes(storageRef, data).then((snapshot) => {
          console.log('File upload complete', `${__dirname}/${__dirname}/${path}`);
          resolve(true)
        }).catch(e => {
          console.log('Failed to upload file: ', e);
          reject(e);
        });
      });

      return p;
    }

    uploadResumable('alice.jpg', 'assets/avatars/alice.jpg');
    uploadNoneResumable('alice.jpg', 'assets/avatars/alice.jpg');

```

### [REQUIRED] Steps to reproduce
See above snippet.
Ensure there is an image in the path specified.

### [REQUIRED] Expected behavior
The files should be uploaded.

### [REQUIRED] Actual behavior
It hangs and eventually times out.

**Comment by valeriangalliat** [comment]
I have the same problem! It doesn't happen all the time for me but it seems related to having multiple uploads running in parallel

I changed my code when using the emulator to upload files one at a time and I don't have the timeout/hanging problem anymore, but it would be great to be able to have parallel uploads with the emulator too 😄

**Comment by vdiaz1130** [comment]
I changed my Node version to 16.9.1 and everything is working again with the latest version of fb-tools.

@valeriangalliat can you share your script to upload in parallel?

**Comment by macksal** [comment]
I had test timeouts crop up in my CI environment. It appears to be because github actions are now using Node 18 by default, and I can reliably reproduce the issue with firebase-tools 11.24.1 on Node 18 locally (16.x works fine).

For me, I had all of my storage rules test cases failing except two. I don't use any parallel uploads, they are all awaited in sequence. Interestingly, the two passing tests upload a larger file (10+ MB) while all the failing cases deal with reads and creating small files of only 1000 bytes. The failing cases include reads and writes that are either expected to fail or expected to succeed (with assertsSucceeds/assertsFails from `@firebase/rules-unit-testing`). The passing cases are one assertsSucceeds and one assertsFails. So the only commonality seems to be the filesize and nothing related to rules.

Maybe it is *only* the multipart uploads that are working, while gets and single-part uploads are failing under Node 18? Not sure why.

My workaround was to pin Node to 16.x. I think this should be reopened @vdiaz1130
