### ISSUE TITLE
Firebase Local Emulator Suite Storage blank when clic on a file with content type image/png

### ISSUE THREAD

**Issue by dumabg** [firebase/firebase-tools#4915]
Steps:
- Put an image on Storage Emulator with content type 'image/png'
![imagen](https://user-images.githubusercontent.com/35224760/186012436-c1e2ed48-df95-4e1a-a50f-010a8aa8190e.png)

- Clic on this file.

Doesn't appear the file information (like appears if is application/octet-stream), it appears a blank page.

**Comment by andymcgunagle** [comment]
Running into this same issue - clicking on a file in the Storage Emulator leads to a blank page and the following error in the console:

![Screen Shot 2022-08-23 at 3 29 48 PM](https://user-images.githubusercontent.com/75338107/186277412-4147ba31-d8ac-4899-9971-7dbcf598738c.png)

**Comment by tonyjhuang** [comment]
Verified this is broken. I've filed https://github.com/firebase/firebase-tools-ui/issues/862 to track this since it seems to be affecting the emulator UI, not the emulator.

@dumabg and @andymcgunagle  for now, you can use the `Open all files` button that shows up when you mark the checkbox next to the file that you want to preview, see below:

![image](https://user-images.githubusercontent.com/1237337/194355592-5c538548-24ef-47d1-9fd2-151d826a5841.png)
