### ISSUE TITLE
Manual Firestore rules are overwritten

### ISSUE THREAD

**Issue by TheIronDev** [firebase/firebase-tools#4929]
### [REQUIRED] Environment info

11.5.0

**firebase-tools:**

macOS

**Platform:**

### [REQUIRED] Test case

* `firebase deploy`

### [REQUIRED] Steps to reproduce

* Run `firebase deploy` - firestore rules are uploaded
* Update firestore rules using the UI
* Run `firebase deploy` - firestore rules are overwritten

### [REQUIRED] Expected behavior

Possibly prompt the user that they are about to overwrite firestore rules (especially if the firestore rules were updated from something other than `firestore.rules`)

### [REQUIRED] Actual behavior

Firestore rules are overwritten without informing end-user that the UI was overwritten.

**Comment by bkendall** [comment]
I believe this is the intentional behavior. The problem as I understand is that we can't figure out (a) which ruleset is "newer" and (b) which ruleset is "expected". So, we assume that a deploy of firestore rules is the intended end state. Maybe @sam-gc could tell us otherwise, but I think this is WAI.

**Comment by sam-gc** [comment]
@bkendall's assessment is correct. Unfortunately we don't have a good way of resolving this issue but we're definitely aware of it. For now though, the best practice is to only use the CLI (along with some sort of source control) to deploy your Rules, with the Console UI as an emergency backup
