### ISSUE TITLE
Error 403: The caller does not have permission

### ISSUE THREAD

**Issue by bengaoose** [firebase/firebase-tools#5035]
### [REQUIRED] Environment info

**firebase-tools:**
11.11.0

**Platform:**
Ubuntu
### [REQUIRED] Test case

`GOOGLE_APPLICATION_CREDENTIALS=./serviceAccountKey.json firebase functions:config:unset app`

### [REQUIRED] Steps to reproduce

- Generate serviceAccount key within Firebase and output the content to `./serviceAccountKey.json`;
- Run the command in CLI `GOOGLE_APPLICATION_CREDENTIALS=./serviceAccountKey.json firebase functions:config:unset app`;

### [REQUIRED] Expected behavior

`GOOGLE_APPLICATION_CREDENTIALS=./serviceAccountKey.json firebase functions:config:unset app` should be executed.

### [REQUIRED] Actual behavior

It throws error:
```
Error: HTTP Error: 403, The caller does not have permission
```

**Comment by bkendall** [comment]
May seem like an obvious question but one that's important: what role does your SA have? You may have to check the [cloud console IAM page](https://console.cloud.google.com/iam-admin/iam) to find out.

**Comment by bengaoose** [comment]
@bkendall By searching around the web, some suggested to assign the service account with a higher privilege like `Editor` role, but I am not sure if it is the best practice.

**Comment by bkendall** [comment]
Setting the SA to have the `Editor` role is indeed a fairly high privilege, but it will work. You can also look into the "Firebase Admin" or "Firebase Editor" roles which scope the permissions down significantly to Firebase-related (and adjacent/dependencies) products. Of course, you can always make a custom role too, but that's fairly involved.

The `--debug` logs should show you which permissions are being checked (and which tests may be failing), should you want to narrow it down further.

Since this isn't a CLI issue though, I'm going to close this issue out.
