### ISSUE TITLE
`npm` warnings when installing `firebase-tools`

### ISSUE THREAD

**Issue by aravindvnair99** [firebase/firebase-tools#5057]
### [REQUIRED] Environment info

**firebase-tools:** 11.13.0

**Platform:** Ubuntu

### [REQUIRED] Test case

Install the latest `firebase-tools`

### [REQUIRED] Steps to reproduce

Install the latest `firebase-tools`

### [REQUIRED] Expected behavior

```
$ npm i -g firebase-tools
added 677 packages, and audited 678 packages in 23s
```

### [REQUIRED] Actual behavior

```
$ npm i -g firebase-tools
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 677 packages, and audited 678 packages in 23s

39 packages are looking for funding
  run `npm fund` for details

5 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

**Comment by bkendall** [comment]
Thanks for raising. We're aware of these but some are buried so deep in other dependencies we cannot update that it'll be impossible to address them. We do try to take these on when we can; I'm going to close this issue though since there's no immediate action I believe we can take today.

**Comment by aravindvnair99** [comment]
Thanks for the quick reply @bkendall! However, I see that `request` is a direct dependency as seen here:

https://github.com/firebase/firebase-tools/blob/9e524c18f4038dfcadbab637c9f661165feb1753/package.json#L134

And as per `request`'s [official README](https://github.com/request/request/blob/3c0cddc7c8eb60b470e9519da85896ed7ee0081e/README.md?plain=1#L1-L6):

```markdown
# Deprecated!

As of Feb 11th 2020, request is fully deprecated. No new changes are expected to land. In fact, none have landed for some time.

For more information about why request is deprecated and possible alternatives refer to
[this issue](https://github.com/request/request/issues/3142).
```

**Comment by michaelsogos** [comment]
> Thanks for raising. We're aware of these but some are buried so deep in other dependencies we cannot update that it'll be impossible to address them. We do try to take these on when we can; I'm going to close this issue though since there's no immediate action I believe we can take today.

@bkendall did you tried to inform or open an issue on other packages in order that they also update deep dependencies ?
I guess that in a open source world everybody have to contribute 😄

**Comment by bkendall** [comment]
Re `request`: the package has been completely replaced by `node-fetch` in our codebase. The only spot is where it still is used is `functions:shell` where there's a "request-like" API to interact with functions. To change that shell would be a breaking change, so we've been punting on making that change until then. There's nothing wrong with continuing to use `request` AFAIK, especially since it's only being used internally, so it hasn't merited a breaking change in the CLI of its own.

Re other packages: sometimes. Unfortunately there are a couple examples, like `update-notifier` which have moved to only exporting a ES module, which cannot be imported by commonjs code (which is what the CLI is). Converting the CLI to use ES modules is... non-trivial, and there really isn't a great "partial upgrade" story where we can convert it slowly. All that said, some packages just won't fix their dependencies - the only real viable idea would be to fork it ourselves, fix it, maintain that package, etc. It's a lift. It's definitely something on my radar, but I have other priorities that take precedence. (not to mention that the CLI is sometimes used as a module and _that_ would be a breaking change and force more people to use ESM, and then we're causing the same problem for more people - it's a tough spot).

Anyway, there's some thoughts.
