### ISSUE TITLE
Error when updating a functions config from a string to an object

### ISSUE THREAD

**Issue by SamyPesse** [firebase/firebase-tools#510]
When changing the functions config to extend a namespace, `firebase functions:config:set` without helping us.

For our deployments, we set a lot of variables at once, the error message didn't help us debug and find the issue.

### Steps to reproduce

Create a variable `a.b`

```
$ firebase functions:config:set a.b=12
✔  Functions config updated.

Please deploy your functions for the change to take effect by running firebase deploy --only functions
```

Then try to create a variable `a.b.c`:

```
$ firebase functions:config:set a.b.c=12

Error: HTTP Error: 400, Precondition check failed
```

### Expected behavior

Do not fail, and replace `a.b` by `{ c: 12 }`.

OR

Fail gracefully with an helpful error message.

### Version info

```
$ firebase --version
3.12.0
```

**Comment by laurenzlong** [comment]
You cannot modify an atomic config value to a tree of config values, and we do not plan on supporting it. The error message comes directly from the server. I've filed a bug internally to improve the server message so that it is clear which precondition check actually failed. Thanks for filing the bug!

**Comment by RickFrom1987** [comment]
This error also occurs when you set a.b="foo" then try to set a.b="bar"
