### ISSUE TITLE
Storage List behaviour does not match real GS bucket.

### ISSUE THREAD

**Issue by emcfarlane** [firebase/firebase-tools#5129]
### [REQUIRED] Environment info

11.14.4

macOS

cloud.google.com/go/firestore v1.7.0
cloud.google.com/go/storage v1.27.0

### [REQUIRED] Test case

```
package main

import (
	"context"
	"fmt"
	"os"

	"cloud.google.com/go/storage"
	firebase "firebase.google.com/go"
	"google.golang.org/api/iterator"
)

func init() {
	os.Setenv("FIRESTORE_EMULATOR_HOST", "localhost:8080")
	os.Setenv("FIREBASE_STORAGE_EMULATOR_HOST", "localhost:9199")
	os.Setenv("STORAGE_EMULATOR_HOST", "localhost:9199")
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	ctx := context.Background()
	app, err := firebase.NewApp(ctx, nil)
	check(err)

	st, err := app.Storage(ctx)
	check(err)
	bkt, err := st.DefaultBucket()
	check(err)

	w := bkt.Object("some/object.txt").NewWriter(ctx)
	check(err)
	_, err = fmt.Fprintf(w, "This object contains text.\n")
	check(err)
	check(w.Close())

	it := bkt.Objects(ctx, &storage.Query{
		Delimiter: "/",
		Prefix:    "some/",
	})
	for {
		attrs, err := it.Next()
		if err != nil {
			if err == iterator.Done {
				break
			}
			check(err)
		}
		fmt.Println(attrs.Name)
	}
}
```

### [REQUIRED] Steps to reproduce

Run the code above with accesse to a real cloud storage bucket, and then the storage emulator.

### [REQUIRED] Expected behavior

Expect output to be:
```
some/object.txt
```

### [REQUIRED] Actual behavior

```
panic: bucket name not specified

goroutine 1 [running]:
main.check(...)
        /Users/edward/src/github.com/emcfarlane/mems/main.go:21
main.main()
        /Users/edward/src/github.com/emcfarlane/mems/main.go:33 +0x31b
exit status 2
```

Also `"FIREBASE_STORAGE_EMULATOR_HOST"` should control the firebase bucket. But it looks like it is ignored.

**Comment by abhis3** [comment]
Hi there,

I believe this should have been fixed with the merge of https://github.com/firebase/firebase-tools/pull/5209. Please try again once we cut a new version of the emulator, or download the latest version straight from Github if you need it sooner.

Be aware there is another small issue in our GO SDK, that I've documented and provided a workaround for here: https://stackoverflow.com/a/74322070/20420645

If both of the above don't fix your issue, please feel free to reopen.
