### ISSUE TITLE
Feature request: specify the region for the SSR function in Web Frameworks

### ISSUE THREAD

**Issue by pothos-dev** [firebase/firebase-tools#5154]
### [REQUIRED] Environment info

**firebase-tools:** 11.15.0

**Platform:** Ubuntu

### [REQUIRED] Test case

(omitted)

### [REQUIRED] Steps to reproduce

I added a NextJS project to an existing Firebase project with a Default GCP resource location in **europe-west3**, then enabled the `webframeworks` experiment, and tried to deploy the project.

### [REQUIRED] Expected behavior

The CLI should create a cloud function to process SSR for NextJS. This cloud function should be created in the default GCP resource location, in this case **europe-west3**

### [REQUIRED] Actual behavior

The SSR cloud function is deployed to **us-central1**, and the deployment fails:

```
i  functions: creating Node.js 16 function firebase-frameworks-educom-beta:ssrmytestproject(us-central1)...
Failed to replace Run service projects/educom-beta/locations/us-central1/services/ssrmytestproject

Functions deploy had errors with the following functions:
        firebase-frameworks-educom-beta:ssrmytestproject(us-central1)
Function URL (firebase-frameworks-educom-beta:ssrmytestproject(us-central1)): https://ssrmytestproject-jvujsx44zq-uc.a.run.app
i  functions: cleaning up build files...

Error: There was an error deploying functions

**Comment by inlined** [comment]
Support for setting a region other than us-central1 is coming. I do not suspect it will be automatic because Cloud Functions for Firebase already has the existing behavior of defaulting to us-central1 and it will likely have unforeseen consequences to default just the SSR function to the AppEngine region.

**Comment by aaronSig** [comment]
Is there any way to manually work around this in the meantime?

**Comment by Erfa** [comment]
Would definitely appreciate this. Doesn't have to be automatic, just a field in firebase.json would be great.

**Comment by nidegen** [comment]
Yes that would be great indeed!

**Comment by qwezey** [comment]
Agreed. A much-needed feature!

**Comment by qwezey** [comment]
found the culprit: https://github.com/firebase/firebase-tools/blob/abcaaab6574a82bf163668cab943a0370aacbe68/src/frameworks/index.ts#L482-L483

seems like this feature is planned for sometime in the future

**Comment by davidrayc** [comment]
I was able to change the region in the `functions.yaml` file inside `./firebase/<my site>`. I can only do it though in a very short window during `firebase deploy`, right after it recreates the yaml file (usually right after next build completes) and before it uploads it to the cloud. 

Had to do it because I don't want to pay for another vpc serverless in us-central1 since I already have one in another region. I could just reuse that for the ssr function. Quite a hacky solution but works well for me.

**Comment by jamesdaniels** [comment]
Will be addressed once [d6826ee](https://github.com/firebase/firebase-tools/commit/d6826ee9e9c2dc5b8e320953aa794be7ba2fdcdb) is out the door in the next CLI release.

**Comment by jasan-s** [comment]
@jamesdaniels  i'm deploying next js app with the following `firebase.json` using firebase tools `11.24.1`  and evertime the ssr cloud function deploys to `us-central1`
```
{
	"hosting": {
		"target": "webapp",
		"source": ".",
		"cleanUrls": true,
		"region": "us-west1",
		"ignore": ["firebase.json", "**/.*", "**/node_modules/**"]
	}
}
```

**Comment by jalexw** [comment]
Why are the regions locked to `us-central1`, `us-west1`, `us-east1`, `europe-west1`, and `asia-east1` when specifying the `hosting.frameworksBackend.region` property?

Hoping to use Next.js SSR in `northamerica-northeast1`...

**Comment by gustavopch** [comment]
I'd also like to know what's the current situation, if it's already possible to use other regions.
