### ISSUE TITLE
NextJS Middleware fails when running locally against emulator

### ISSUE THREAD

**Issue by bruceharrison1984** [firebase/firebase-tools#5243]
### [REQUIRED] Environment info

**firebase-tools: 11.16.0**

**Platform: Windows/Linux**

### [REQUIRED] Test case

Running NextJS middleware locally should work the same as when deployed

### [REQUIRED] Steps to reproduce

Init a basic firebase project with emulators in a NextJS project. Add some kind of basic [Middleware ](https://nextjs.org/docs/advanced-features/middleware)to the `src` directory. 
Start the project via `firebase emulators:start`. Do something to trigger a route change, which should fire the Middleware.

The middleware will fail due to the next-url packaging not being able to interpret the hosted url.
`> Invalid URL: http://undefined:undefined/app/news?__nextDefaultLocale=&__nextDataReq=1`

### [REQUIRED] Expected behavior

I would expect some type of hostname:port to be passed into the custom nextJs server. Whether this is hardcoded, or something that can be added to `firebase.json` would work.

### [REQUIRED] Actual behavior

The host is undefined, so the middleware immediately fails. This does not happen when deployed to Firebase, nor when running without the emulators (`next dev`).

**Comment by cjsewell** [comment]
I believe this is due to the same issue as https://github.com/vercel/next.js/discussions/40344

As a workaround for testing, I manually added hostname and port to https://github.com/firebase/firebase-tools/blob/master/src/frameworks/next/index.ts#L305 and it seems to work...
```
     const nextApp = next({
         dev: true,
         dir,
         hostname: 'localhost',
         port: '3000'
     });
```

Additionally, the same must be done to https://github.com/FirebaseExtended/firebase-framework-tools/blob/main/src/next.js/index.ts#L6 for middleware to work once deployed

**Comment by jamesdaniels** [comment]
Middleware should now be supported in firebase-tools v11.19.0
