### ISSUE TITLE
to host my site on firebase

### ISSUE THREAD

**Issue by code-by-cl** [firebase/firebase-tools#5284]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment]
Hey @code-by-cl, if you are having an issue with Firebase CLI Tools, could you open a new ticket with the template filled out with the required information so that we can conduct an initial investigation? That said, I'll be closing this for now.

Though, looking at the title of the ticket, I’m assuming that you want to deploy your website to Firebase Hosting. If so, I would recommend checking out the [public documentation](https://firebase.google.com/docs/hosting) about Firebase Hosting.
