### ISSUE TITLE
Blocking function beforeCreate won't get triggered when adding users in emulator UI manually

### ISSUE THREAD

**Issue by tzuhaohuang** [firebase/firebase-tools#5299]
### [REQUIRED] Environment info

**firebase-tools: 11.16.1**

**Platform: macOS 13.0.1**

### [REQUIRED] Test case

Adding a new user manually in emulator UI console -> did not trigger beforeCreate.
But when I integrated my ios project with emulator and added a user programmatically, beforeCreate blocking function was triggered.

### [REQUIRED] Steps to reproduce

Add a new user in emulator UI console when beforeCreate function is initiated when starting emulator.

### [REQUIRED] Expected behavior

BeforeCreate function should be triggered even when adding a user in emulator UI, since onCreate will be triggered.

### [REQUIRED] Actual behavior

beforeCreate blocking function is not triggered when adding users in emulator UI console.

**Comment by aalej** [comment]
Hi @tzuhaohuang, thanks for reporting this. I asked our team and they mentioned that adding new users using the console UI will not trigger `beforeCreate`. This is because it is considered as an admin action.

The same behavior can be observed after deploying to Cloud Functions, e.g. creating a user using the Firebase Authentication SDK triggers both `beforeCreate` and `onCreate`, while creating a user via the Firebase console UI only triggers `onCreate`.

I would recommend filing a feature request to [Google Cloud Identity Platform](https://cloud.google.com/identity-platform/docs/support#file_feature_requests_and_bug_reports) if triggering [Auth blocking functions](https://firebase.google.com/docs/auth/extend-with-blocking-functions#understanding_blocking_functions) when creating users using the console is something you would like to see implemented.
