### ISSUE TITLE
Firebase storage emulator hangs when checking if file exists

### ISSUE THREAD

**Issue by ir-fuel** [firebase/firebase-tools#5400]
### [REQUIRED] Environment info

**firebase-tools:**
11.19.0

**Platform:**
macOS 13.0.1

**Node**
18.12.1

### [REQUIRED] Test case

```
    const file = admin.storage().bucket().file(`images/someFileName`)
    let exists = [false]
    do {
      exists = await file.exists()
      console.log('x')
    } while (!exists[0])

```

### [REQUIRED] Expected behavior
This should loop and print `x` all the time until the file exists

### [REQUIRED] Actual behavior
The `exists = await file.exists()` line just hangs

This used to work on 9.20.0, but no longer does. I don't know in what version it started breaking.

**Comment by aalej** [comment]
Hi @ir-fuel, thanks for the information you provided. I am unable to replicate the issue you mentioned. From what I understand, the actual behavior from the test case you provided is that it gets stuck in `exists = await file.exists()` and does not print `x`.

I tried to replicate the issue using the code snippet below. After running the Firebase Emulator and executing the `helloWorld` function, the behavior was that it would keep on looping, and once I uploaded the file `images/test.png`, the loop stopped. This was the expected behavior.

```
const functions = require("firebase-functions");
const admin = require("firebase-admin");
admin.initializeApp();
// // Create and deploy your first functions
// https://firebase.google.com/docs/functions/get-started

exports.helloWorld = functions.https.onRequest(async(request, response) => {
   functions.logger.info("Hello logs!", { structuredData: true });
   await loadImage();
   response.send("Hello from Firebase!");
});

const loadImage = async() => {
   const file = admin.storage().bucket().file(`images/test.png`);
   let exists = [false];
   do {
       const dateNow = new Date();
       exists = await file.exists();
       console.log(dateNow.getTime());
       console.log(exists);
   } while (!exists[0]);
};
```

Let me know if I may have missed anything. Also, could you provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) or more details on the steps you took so that we can properly replicate the issue you encountered? Lastly, you mentioned that “This used to work on 9.20.0, but no longer does”. Just to verify, could you let me know if you’re referring to firebase-tools v9.20.0 or something else?

**Comment by ir-fuel** [comment]
This was firebase-tool 9.20.0 indeed.
I'll see if I can come up with a complete example that breaks on my machine. It's in a test where in the background a file is uploaded to Firebase Storage and the test waits until the file exists. My colleague developed it and it worked on his computer. It failed on mine, so we started investigating, and as soon as he updated his firebase-tools to the latest version he had the same issue.

**Comment by bkendall** [comment]
Let us know if you come up with a complete example. That'd be greatly appreciated!

**Comment by christhompsongoogle** [comment]
Shot in the dark: are you using the host 'localhost' to connect to the emulator? What IP:port are you specifying in your connection logic?
