### ISSUE TITLE
Firebase `deploy --only functions` does not retry deployment after a `quota exceeded` error.

### ISSUE THREAD

**Issue by adakhno** [firebase/firebase-tools#5474]
### [REQUIRED] Environment info

**firebase-tools:**
11.20.0

**Platform:**
macOS
### [REQUIRED] Test case

We have a project with 342 functions. After moving to firebase-tools@11.20.0, we can no longer deploy all functions.

### [REQUIRED] Steps to reproduce

run `firebase deploy --only functions`

### [REQUIRED] Expected behavior

deploy succeeds

### [REQUIRED] Actual behavior

The process finished without any errors.
Only some functions have been deployed (~80 out of  342).
There are 'quota exceeded' errors in the logs for missing functions.
There are no signs that these functions were attempted to be redeployed.

This feature worked on firebase-tools@9.10.0.

```
[2023-01-31T12:37:30.061Z] <<< [apiv2][status] PATCH https://cloudfunctions.googleapis.com/v1/projects/auction-dev-1985f/locations/us-central1/functions/GROUP-FUNCTION_NAME 429
[2023-01-31T12:37:30.061Z] <<< [apiv2][body] PATCH https://cloudfunctions.googleapis.com/v1/projects/auction-dev-1985f/locations/us-central1/functions/GROUP-FUNCTION_NAME {"error":{"code":429,"message":"Quota exceeded for quota metric 'Write requests' and limit 'Write requests per minute' of service 'cloudfunctions.googleapis.com' for consumer 'project_number:273276632660'.","status":"RESOURCE_EXHAUSTED","details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"RATE_LIMIT_EXCEEDED","domain":"googleapis.com","metadata":{"quota_metric":"cloudfunctions.googleapis.com/write_requests","quota_location":"global","quota_limit":"WriteRequestsPerMinutePerProject","service":"cloudfunctions.googleapis.com","consumer":"projects/273276632660","quota_limit_value":"50"}}]}}
⚠  functions: got "Quota Exceeded" error while trying to update projects/auction-dev-1985f/locations/us-central1/functions/GROUP-FUNCTION_NAME. Waiting to retry...
Failed to update function projects/auction-dev-1985f/locations/us-central1/functions/GROUP-FUNCTION_NAME
```

**Comment by taeold** [comment]
Hey @adakhno - thanks for filling the issue.

IIUC, the CLI will retry the deploy in case of a quota exceeds error ([code](https://github.com/firebase/firebase-tools/blob/e8a59e64d85dee0273e58e1bc5eb86860e5f660d/src/deploy/functions/release/executor.ts#L21-L26)) and my best guess in this situation is that the deployment ultimately exhausted the retry (30 per function) or timed out.

Trying to deploy >100 functoins at once is unlikely to succeed due to the Quota Limitation enforced by the Google Cloud Functions API (80 calls for 100 seconds).

Do you mind sharing timing/full debug log? I wonder whether retry or timeout was exhausted in your deployment, and curious to see if we can improve the situation by increasing the limit for both.

You can also try organizing your functions using [codebases](https://firebase.google.com/docs/functions/organize-functions#organize_functions_in_codebases) - that way you'd only need to re-deploy function that actually includes a code change.

**Comment by adakhno** [comment]
Hi @taeold. thank you for your reply.
We'll look at the "codebase" feature.
I can share debug logs, but only privately. Can I send you an email?

**Comment by taeold** [comment]
@adakhno

**Comment by wreulicke** [comment]
Hi, @taeold

I submitted the PR to fix this issue.
https://github.com/firebase/firebase-tools/pull/5577

Could you review this PR?

**Comment by blidd-google** [comment]
Hey @wreulicke, thanks you for pointing this out! The team has been making an ongoing effort to improve deploy reliability, and this was indeed an issue that caused retries to not actually happen when we were expecting them to. However, fixing the status error code issue surfaced some other problems with the retry logic, and we are continuing to work on addressing those issues. Stay tuned for a PR containing a wider set of fixes to be pushed soon!

**Comment by wreulicke** [comment]
Hey, @blidd-google 
I'm looking forward to improving deployment reliability.
When will the improvement be released?

**Comment by blidd-google** [comment]
Hey @wreulicke, see the PR #5601. A couple more changes to follow (addressing v2 deploy reliability specifically).
