### ISSUE TITLE
v2 functions don't support `retry` even though cloud functions gen2 do

### ISSUE THREAD

**Issue by pavelgj** [firebase/firebase-tools#5484]
### [REQUIRED] Environment info

**firebase-tools:** 11.21.0

**Platform:** macOS

### [REQUIRED] Test case

```
exports.customeventhandler = onCustomEventPublished(
  {
    eventType: "firebase.extensions.storage-resize-images.v1.complete",
    retry: true,
  },
  (e) => {
    console.log(JSON.stringify(e));
  });
```

### [REQUIRED] Steps to reproduce

firebase deploy --only functions

### [REQUIRED] Expected behavior

Should deploy function with retry policy

### [REQUIRED] Actual behavior

Shows a warning `Cannot set a retry policy on Cloud Function` and does not set the retry policy.

Warning is coming from here: https://github.com/firebase/firebase-tools/blob/a2b9389928c7586d2bbdfda4f9212bd7fcc88f21/src/gcp/cloudfunctionsv2.ts#L528

`EventTrigger` has `retryPolicy` field, so it should be set when `retry` option is specified.
https://cloud.google.com/functions/docs/reference/rest/v2/projects.locations.functions#eventtrigger

**Comment by icopp** [comment]
Any news on this issue?

**Comment by alexstroukov** [comment]
any news on this? its concerning that you cant deploy event functions with retries since the ability to retry an event is kind of the whole point.

for anyone stuck on this you can update [this](https://github.com/firebase/firebase-tools/blob/a2b9389928c7586d2bbdfda4f9212bd7fcc88f21/src/gcp/cloudfunctionsv2.ts#L528) file (with [patch-package](https://github.com/ds300/patch-package)) to set a `retryPolicy` instead of the warning in the console as a temporary measure 

```
  if (endpoint.eventTrigger.retry) {
    gcfFunction.eventTrigger.retryPolicy = 'RETRY_POLICY_RETRY'
    // logger_1.logger.warn("Cannot set a retry policy on Cloud Function", endpoint.id);
  }
```

**Comment by andy-lee-vat-calc** [comment]
upvote on this, any plans for it?
