### ISSUE TITLE
storage trigger causes ffmpeg ENOENT error only on Node 18, works on Node 16

### ISSUE THREAD

**Issue by wonsangchoi-airballoon** [firebase/firebase-tools#5489]
### [REQUIRED] Environment info

**firebase-tools:** 11.22.0

**Platform:** macOS Monterey Version 12.6.2 / Intel Mac

### [REQUIRED] Test case

I'm creating a thumbnail for a video using cloud storage trigger using ffmpeg.

const spawn = require('child-process-promise').spawn;

  await spawn('ffmpeg', [
        '-i',
        tempFilePath,
        '-vframes',
        '1',
        '-an',
        locatThmbFilePath,
      ]);

This produces an error when node is set to 18 in package.json.

In cloud after deployment:
Node 18 => spawn ffmpeg ENOENT error
Node 16 => OK

In local emulator:
Node 18 => OK
Node 16 => OK

### [REQUIRED] Steps to reproduce

package.json 

{
  "engines": {
    "node": "18" // if set to 16, works well.
  },

### [REQUIRED] Expected behavior

with node set to 18, ffmpeg command should work without eror.

### [REQUIRED] Actual behavior

Error logs from cloud function logs.

errno: -2,
code: 'ENONET'
sys call: 'spawn ffmpeg',
path: 'ffmpeg',

**Comment by alexplumb** [comment]
I've experienced the same issue when trying to use the `convert` tool from the imagemagick package. Is the Node 18 image missing these utilities?

**Comment by colerogers** [comment]
Hi @wonsangchoi-airballoon thanks for opening your first issue here. Cloud Functions for Firebase is a tooling/sdk layer on top of Google Cloud Functions. It looks like your issue is with the Node 18 runtime of the underlying function, which the Google Cloud Functions team owns. If we check out the public docs, it looks like [these are the includes packages for Cloud Functions](https://cloud.google.com/functions/docs/reference/system-packages) and Ubuntu 22.04 doesn't have `ffmpeg` anymore. If we take a peek at the [mapping of Node runtime to OS](https://cloud.google.com/functions/docs/concepts/execution-environment#node.js) then it looks like Node 18 is indeed on Ubuntu 22.04 which doesn't have `ffmpeg`. 

My colleague (@taeold) pointed out the reason for its absence is that GCF is only taking packages that are listed in Ubuntu 22 main. (`ffmpeg` is a universe package - [Community-maintained free and open-source software](https://cloud.google.com/functions/docs/concepts/execution-environment#node.js))

If you have questions or want to raise this up to the GCF team, you can reach out to Cloud support - https://cloud.google.com/functions/docs/getting-support

Thanks!

**Comment by colerogers** [comment]
@alexplumb it also looks like `imagemagick` is also not a main ubuntu 22 package - https://cloud.google.com/functions/docs/reference/system-packages

**Comment by alexplumb** [comment]
This is a pretty major breaking change @colerogers - this has been a supported use case of cloud functions for a while, to such an extent that it's included as a sample function in the firebase github repo: https://github.com/firebase/functions-samples/tree/main/convert-images

Does this break the image optimization extension as well, or is that running an older version of Node?

**Comment by alexplumb** [comment]
I should note that the official docs also mention that Cloud Functions implicitly support imagemagick https://firebase.google.com/docs/storage/extend-with-functions

**Comment by colerogers** [comment]
@alexplumb [Node 16 uses Ubuntu 18.04 under the hood](https://cloud.google.com/functions/docs/concepts/execution-environment#node.js) which still has `imagemagick`. Our sample uses node 16 so it shouldn't be effected at all. If you're upgrading from Node 16 -> Node 18, that should be an indication that breaking changes can occur. I agree that it is weird that even the official Google Cloud samples showcase `imagemagick` - https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/main/functions/v2/imagemagick - while also listing Node 18 as the recommended version.

Again, we (Firebase) do not own the underlying runtime of a Cloud Function (just the SDK and CLI) and have no control over what packages are used. I'll try to raise this internally with them, but additional public requests from the community would help too - https://cloud.google.com/functions/docs/getting-support

**Comment by alexplumb** [comment]
Thanks - it looks like someone's already gone through the trouble to make a ticket https://issuetracker.google.com/issues/265809642
