### ISSUE TITLE
Hosting webframeworks: NextJS - 404 not being used (only when hitting /404)

### ISSUE THREAD

**Issue by jabza** [firebase/firebase-tools#5537]
### [REQUIRED] Environment info

**firebase-tools: 11.23.1**

**Platform: Windows**

### [REQUIRED] Test case

firebase.json
 "hosting": {
    "source": ".",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
NextJS app with a pages/404.jsx component.

### [REQUIRED] Steps to reproduce

firebase experiments:enable webframeworks
firebase init hosting
firebase deploy

### [REQUIRED] Expected behavior

When navigating to any invalid page, the 404.jsx page is displayed.

### [REQUIRED] Actual behavior

index.html is always showing, unless /404 is went to directly

**Comment by hanifmhd** [comment]
is there any update?

**Comment by DerLev** [comment]
I just bumped into this problem yesterday. I haven‘t tested it any further until now but my guess is that a url rewrite is created for the `index.html` just like a normal SPA. You can probably do a 404 with a condition inside the `/pages/index.tsx` or `/app/page.tsx` but I haven‘t tested if that will work. It‘s also not the most elegant solution because doing this won‘t really throw a 404 status code. Its just a 200 OK with a page *displaying* a 404.

**Comment by DerLev** [comment]
I just checked and this issue seems to be resolved. Probably as of `v12.3.0` due to many fixes to the webframeworks experiment. I didn't follow this issue that closely but my guess is that this version fixed it 🎉

**Comment by DGB161** [comment]
Hi @jabza! Can you please confirm if this issue is resolved on your end, and can be closed? Thanks! cc @leoortizz
