### ISSUE TITLE
Inconsistent CLI error when running firebase ext:install for a local extension in forced non-interactive mode

### ISSUE THREAD

**Issue by ste26054** [firebase/firebase-tools#5591]
### [REQUIRED] Environment info

**firebase-tools: 11.24.1**

**Platform: macOS, Ubuntu**

### [REQUIRED] Test case

I am trying to install a local Firebase Extension to a test project through our CI, using non-interactive mode. I am getting an inconsistent error message regarding use of `--params` argument:

```
firebase ext:install ./ --project=my-project --non-interactive --force
i  extensions: ensuring required API firebaseextensions.googleapis.com is enabled...
✔  extensions: required API firebaseextensions.googleapis.com is enabled
i  extensions: Checking project IAM policy...
✔  extensions: Project IAM policy OK
✔  Uploaded extension source code
i  extensions: information about './':
Name: My-Extension-Name
Description: My-Extension-Description
Roles granted to this Extension:
  Firebase Authentication Admin (Full read/write access to Firebase Authentication resources.)
  Cloud Datastore User (Provides read/write access to data in a Cloud Datastore database. Intended for application developers and service accounts.)


Error: In non-interactive mode but no `--params` flag found. To install this extension in non-interactive mode, set `--params` to a path to an .env file containing values for this extension's params:
        ENV_VARIABLE_1
        ENV_VARIABLE_2
        ENV_VARIABLE_3
        ...
```

Yet, if I provide the `--params` argument:

```
firebase ext:install ./ --project=my-project --non-interactive --force --params ./.extension-params.env
error: unknown option '--params'
```

The rationale for this configuration is to install locally the extension to a test project to ensure it works properly before releasing a new version.

### [REQUIRED] Steps to reproduce

See above commands and their result

### [REQUIRED] Expected behavior

Provide a consistent command regarding the usage or not of `--params` argument, either by allowing to read directly from `.env` files, or allowing the use of `--params` for the specific use case of installing a local extension

### [REQUIRED] Actual behavior

I should not have an error message 🙂 

Thanks a lot for your support!

**Comment by joehan** [comment]
Hey @ste26054, sorry for the confusion here. This looks like a bit of missed clean up on our end, but fortunately, I think your intended use case is well supported.

In v11 of firebase-tools, we made a breaking change to how we manage extensions via firebase-tools, to be more similar to other Firebase products and to work better with the emulator suite. After v11, installing an extension onto a Cloud project is a 2 step process: first, you add it to your local directory's`firebase.json` by running ext:install and interactively configuring the extension, then you run `firebase deploy` to deploy it onto your Cloud project or `firebase emulators:start` to test it in the local Emulator Suite. `--params` is an old flag that is now redundant, and we missed cleaning up some references to it. 

For your use case, so I recommend the following set up;

- In your extension directory, make a new folder called `ci` (or whatever you would like)
- Inside the 'ci' folder, run `firebase init` and select whatever other products you need for your extension to run. If you don't need any other products, just choose `emulators`. This will also prompt you to choose a project - I see that you currently provide this via an environment variable, so choose no project. This step will create a `firebase.json` and a `.firebaserc` file in `ci`.
- From the 'ci' folder, run `firebase ext:install .. -P [your test project]` and configure your extension interactively. Once you've done this, you'll see a new file `ci/extensions/purchasely-in-app-purchases.env`, with the config values you chose. 
- Now, in your CI script, you can replace [this line](https://github.com/Purchasely/Purchasely-Firebase-Extension/blob/master/.github/workflows/ci-develop.yml#L139) with `firebase deploy --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN --non-interactive --force`

Since this points at your local code path, it will automatically pick up any changes you make there. If you add new params or need to change the values of old ones for your tests, go in to 'ci' and run `firebase ext:configure purchasely-in-app-purchases` to interactively reconfigure, or simple edit `ci/extensions/purchasely-in-app-purchases.env`

Switching to this set up will bring some extra benefits, too. When testing locally, you can go to the 'ci' directory and run `firebase emulators:start` to test out your extension in the emulator suite.

Please let me know if this makes sense - I'm happy to clarify any confusion or help debug any issues you may run into.

**Comment by ste26054** [comment]
Thanks a lot for the detailed answer! I will update our CI accordingly.
