### ISSUE TITLE
Random Failures on Deploy

### ISSUE THREAD

**Issue by benoj** [firebase/firebase-tools#585]
### Version info
 3.16.0

### Steps to reproduce
I have 13 database functions and 2 https functions mapping to express apps.

`firebase deploy  --only functions` 

### Expected behavior

Deployment works for valid code

### Actual behavior

When I deploy I get random "Deployment error." from CLI on some of the functions. When I run again I get it on other functions. After a while they all deploy.

Logs say "Error in the build environment"

**Comment by merlinnot** [comment]
Please see https://github.com/firebase/firebase-tools/issues/536#issuecomment-354337374

> "Error in the build environment" usually indicates a production issue, in that case please file a support ticket at https://firebase.google.com/support/, you can see if there are any ongoing production issues by visiting the Firebase Status Dashboard

Many people get these, I've filled an issue myself.

You should provide the following information so that they can investigate on this more:
- Complete error logs you're referring to (Screenshots would be great)
- Your function's code that reproduces the issue (index.js) so they can run this locally and replicate the issue on their end
- Detailed step by step instructions to reproduce the issue
- package.json
- Your "firebase-debug.log" (Add --debug flag when executing firebase deploy)
- The "firebase-tools" version that you are using (You can obtain the version by running the "firebase -V" or "firebase --version" command)
- Your "Node.js" version (You can obtain the version by running the "node --version" command)
- Any other extra information that you can share

**Comment by mbleigh** [comment]
Please re-open with more details if you're still having trouble, and thanks for the suggestions @merlinnot
