### ISSUE TITLE
firebase database:get on non-default database

### ISSUE THREAD

**Issue by samodadela** [firebase/firebase-tools#589]
Hi, 

My project has multiple databases (besides the default one)... how can I get the contents of another database? 

This retrieves the data from the default database:
    # firebase database:get /
{"test":123}

How can I get data from let's say db01?

**Comment by mbleigh** [comment]
We haven't yet updated the `database:*` commands to work for non-default databases. I'll leave this open as a feature request.

**Comment by harshadptl** [comment]
+1

**Comment by inteist** [comment]
> Definitely need database:profile to support multiple databases.... flying blind without it.

Same here. How can you recommend using multiple buckets to avoid bottlenecks and not support profiling for all the databases...?

**Comment by laurenzlong** [comment]
@rockwotj Is this something that you'd like to tackle?

**Comment by rockwotj** [comment]
I'd be happy too, I might need to understand how multidb works in general with the CLI first.

**Comment by inteist** [comment]
@rockwotj what I have seen in the documentation it should have bee `-f db_name` directive

**Comment by rockwotj** [comment]
`-f` is a scary flag and most certainly not be the right flag for changing the database name, where have you seen that flag documented? It won't work.

I'd be nice if it worked with:
https://firebase.google.com/docs/database/usage/sharding#edit_and_deploy_for_each_instance

But I'm not sure of a clean way, as you can only do these commands with a single database at a time, maybe adding a `--target` flag to change the DB name?

**Comment by inteist** [comment]
@rockwotj, I certainly agree that -f is a very bad choice but I am pretty sure I've seen this used with :get command lines in older documentation. I am not suggesting anything, I just mentioned what I saw already used.

the documentation also says that you can change the database used in the dot config file but there is no direction as to what syntax to use and apparently it plainly isn't supported. 

All in all, since we had a pretty serious problem, I've spent couple hours digging through docs to try to find a way to profile the problematic shards. My point here being that docs also really need to be updated to reflect the current state.

I hope this feature and other management features (delete database) can be implemented very soon.

**Comment by rockwotj** [comment]
Disable (not delete) database is implemented on the backend, I'm hoping support can land soon, but no promises on timeline.

**Comment by mjesuele** [comment]
Yeesh, this seems like a pretty big omission, no? There's really currently no good way to use the CLI to get data from a non-default db? 😖

**Comment by rockwotj** [comment]
@mjesuele it's implemented as of #800, just need a new release from @mbleigh

**Comment by mjesuele** [comment]
@rockwotj ooooooh amazing, thanks!

**Comment by laurenzlong** [comment]
It is now released in v3.19.0
