### ISSUE TITLE
Error Deploying Specific Function

### ISSUE THREAD

**Issue by gbourne1** [firebase/firebase-tools#5933]
### [REQUIRED] Environment info

**firebase-tools:** 12.3.0

**Platform:** OSX 13.3.1

### [REQUIRED] Test case

`firebase deploy --only functions:api`

### [REQUIRED] Steps to reproduce

With the latest Firebase Tools deploying a specific function fails. Deploying all functions is successful.

`firebase deploy --only functions:api`

Fails now for all functions if specify.

### [REQUIRED] Expected behavior

Deployment for the specific function.

### [REQUIRED] Actual behavior

=== Deploying to 'system'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint .

✔  functions: Finished running predeploy script.

Error: No function matches given --only filters. Aborting deployment.

**Comment by inlined** [comment]
I cannot reproduce this error on the latest version of firebase-tools. It sounds like you have a typo in your function name or command. Since this is not a reproducible bug, I'm going to send you to [Firebase Support](http://firebase.google.com/support) who can work with you on your particular project.
