### ISSUE TITLE
Connect Cloud Functions (not us-central1 region) 2nd gen to Firebase Hosting in emulator

### ISSUE THREAD

**Issue by absemetov** [firebase/firebase-tools#5957]
**Firebase-tools: 12.3.1**
Firstly, thanks to the developers for adding the ability to set different regions for the hosting function. But now I found that the emulator does not support this feature, hosting rewrites all functions to  **us-central1** region
````
// 2nd gen function
const site = onRequest({region: "europe-central2", maxInstances: 10, memory: "1GiB"}, async (req, res) => {
  //
});
````
firebase.json
````
"rewrites": [
        {
          "source": "**",
          "function": "site"
        }
      ]
````
Hosting log:
````
[hosting] Rewriting / to http://127.0.0.1:5001/rzk-warsaw-dev/us-central1/site for local Function us-central1/site
i  hosting: 185.94.214.106 - - [11/Jun/2023:12:00:07 +0000] "GET / HTTP/1.1" 404 685 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"

**Comment by bkendall** [comment]
hi @absemetov - I'm able to replicate this! And I even think I know why...

Would you give something a try for me? In your `firebase.json` could you specify the function with the newer syntax and specify the region there? It's not strictly necessary - and that's why it works when you deploy, I imagine - but if you can confirm this, I think it's an oversight that we just are reading the wrong information when doing rewrites in the emulator.

Update your rewrite to:

```json
{
  "source": "**",
  "function": {
    "functionId": "site",
    "region": "europe-central2" // Should match what's in code.
  }
}
```

LMK if that works for you - and I can see about addressing this in the emulator.

**Comment by absemetov** [comment]
Thanks @bkendall! Emulator read region opt from firebase.json, rewrites work correct.
