### ISSUE TITLE
Failed to load function definition from source: FirebaseError: User code failed to load. Cannot determine backend specification

### ISSUE THREAD

**Issue by Sahmuraii** [firebase/firebase-tools#6007]
### [REQUIRED] Environment info

![image](https://github.com/firebase/firebase-tools/assets/91084502/83f5e059-ea3d-45a6-b6a1-da07a1e457d6)
![image](https://github.com/firebase/firebase-tools/assets/91084502/7e9edfee-b734-4dde-94ed-760b6dade40a)

**firebase-tools: 11.29.1**

**Platform: Ubuntu (Windows WSL)**

### [REQUIRED] Test case

 Followed steps are said here: https://firebase.google.com/docs/functions/get-started?gen=1st

### [REQUIRED] Expected behavior

 No Error should have occurred 

### [REQUIRED] Actual behavior

Error is being produced when I run firebase emulators:start --only functions
![image](https://github.com/firebase/firebase-tools/assets/91084502/e30e4c6e-da14-44e3-8d28-ab2c6e1a5ea1)

Also attached debug-log 
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/11791278/firebase-debug.log)

Maybe it's caused by updating the WSL? Not entirely sure though since it was working fine before and that's the only change I can think of.

**Comment by aalej** [comment]
Hi @Sahmuraii, thanks for reaching out. I am unable to reproduce the issue you’re encountering. I followed the steps in https://firebase.google.com/docs/functions/get-started?gen=1st, but no errors were raised when I started the emulator. As a first troubleshooting step, could you try updating to the latest version of firebase-tools which is currently [v12.4.0](https://github.com/firebase/firebase-tools/releases/tag/v12.4.0).

It would also be helpful if you could provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) where the issue is reproducible so that I can try it out on my end? This will also help us narrow down the cause of the error. Thanks! 

I’m using the following to replicate the issue:
- Platform: Debian GNU/Linux
- firebase-tools: v12.4.0
- Node: v18.15.0

**Comment by ugoi** [comment]
I had the same problem. You have tu turn of Nordvpn or any other VPN. That fixed it.
