### ISSUE TITLE
Deploy Specific Function Doesn't Work in Cloud Function V2

### ISSUE THREAD

**Issue by gOzaru** [firebase/firebase-tools#6008]
### [REQUIRED] Environment info

**firebase-tools: 12.4.0.**

**Platform: Windows**

### [REQUIRED] Test case

Sorry, this is company project. I am not allowed to share anything. 
Anyway, I am using Cloud Function version 2, and this is the documentation [link](https://firebase.google.com/docs/cli/#deploy_specific_functions).

### [REQUIRED] Steps to reproduce

Just run: 
`firebase deploy --only functions:hadsignup`

Or: 
`firebase deploy --only functions:hadsignup,functions:hadsignin`

### [REQUIRED] Expected behavior

The functions should be deployed at all!

### [REQUIRED] Actual behavior

```dart
i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint .

+  functions: Finished running predeploy script.

Error: No function matches given --only filters. Aborting deployment.
```

**Comment by JEndler** [comment]
Am also experiencing this issue.
Neither specifying codebases, nor specific function names are working.

**Comment by blidd-google** [comment]
Hi @gOzaru, a couple follow-up questions about your configuration — in your `firebase.json` file, do you have multiple codebases specified?

Running `firebase deploy --only functions:hadsignup` means that the deployment logic will first look for a codebase named `hadsignup`; if no codebase by that name is found, then we will then look for a specific function named `hadsignup` in the `default` codebase to deploy. However, if your `hadsignup` function is not in the default codebase, we won't find it. This behavior is intentional to avoid naming collisions between functions in different codebases.

For now, I would suggest keeping the functions you want to deploy specifically in the source directory that corresponds to the `default` codebase. For example, given a `firebase.json` like so:

```
"functions": [
  {
    "source": "functions",
    "codebase": "default",
  },
  ...
]
```
Put `hadsignup` and `hadsignin` inside the `functions` source directory. Alternatively, you could keep those functions you would like deployed together in the same codebase and specify `--only functions:[codebase-name]` when deploying.

In the future, we will explore enabling users to specify a codebase and individual function via a syntax like `firebase deploy --only functions:[codebase-name]:[function-name]` to allow users to specify individual functions in other codebases.

If you've tried the above suggestions and are still having issues, please let us know.

**Comment by Flucadetena** [comment]
Hi! @gOzaru can you tell me how to deploy multiple functions by name with an specific codebase please.

- I have a monorepo that I use to migrate from gen1 to gen2. My "codebase" names are: "functions" and "functions-v2".
- When I had only one source for gen1, I would do: `functions:NAME-OF-FUNCTION,functions:NAME-OF-FUNCTIONS`
- But now that I have two sources, whenever even If I specify the second one "functions-v2" in each, it throws me an error related to the gen1 source. But If only deploy one functions by name this does not happen.

Thanks a lot for the help. Did not want to open a new issue just for this as it seems related.

**Comment by Flucadetena** [comment]
Ok, solving the problem in Gen1 side solved the problem for me, but it is strange why deploy only one function was not affected by the other source and deploy multiple yes.

Leave it here in case it helps someone. :)
