### ISSUE TITLE
Emulator restarts during external HTTP request

### ISSUE THREAD

**Issue by jelling** [firebase/firebase-tools#6065]
### [REQUIRED] Environment info

**firebase-tools:** Firebase 12.4.2
**Platform:** Windows 11
**Node** Version 18

### [REQUIRED] Test case

This is an unusual issue so please bear with me for a moment. Here's the situation:

- I have a function that called `Foo` that POSTs to a 3rd party website using Axios
- `Foo.test` calls `Foo` and that test passes reliably using a cloud firebase environment with Jest
- When I try to run `Foo` with the same values on the emulator the function completes but the emulator restarts in the middle of the process and outputs: `shutdown requested via /__/quitquitquit`

  
### [REQUIRED] Steps to reproduce

For the sake of discussion, let's assume there is an issue with my code even though the function completes.

What I'm looking for is some sort of pointer to figuring out how why the emulator is restarting. I turned on verbose logging and didn't see anything that jumped. And it's just a POST of a small amount of JSON.

### [REQUIRED] Expected behavior

Emulator should not restart during cloud function run, especially if the function subsequently completes successfully.

### [REQUIRED] Actual behavior

Emulator restarts in the middle of the cloud function request and outputs: `shutdown requested via /__/quitquitquit`. 

...but the function still completes successfully.

**Comment by aalej** [comment]
Hi @jelling, thanks for reaching out. I think a file within your directory may be changing whenever the function `Foo` runs, and the emulator reloads because of that. Could you try running `firebase emulators:start --debug` and share the output with us? Passing the `--debug` flag provides a more detailed log so that we can verify if this is indeed the case. Please remove any PII (personal identifiable information) if needed.

If there is a file being changed, you should see logs similar to `File <file_path> changed, reloading triggers`.

**Comment by jelling** [comment]
Ahh, I haven’t tried yet but I am writing a temporary file to local disk so
that is almost certainly the issue. I’ll move the temp file location
somewhere else. Thank you for your help.

**Comment by aalej** [comment]
Glad I was able to help out. For now, I’ll be closing this issue. Feel free to ask this to be reopened if you still encounter the issue, and please share with us your `firebase-debug.log` so that we can further investigate. Thanks!

**Comment by jelling** [comment]
@aalej is there a secret to writing files to the os.tempdir using the file emulator? I switched to sticking the temp files there but my code now fails with a "no such file or directory error." 

```
  const tmpDir = fs.mkdtempSync(join(tmpdir(), "signed-url-"));
  console.log("tmpDir", tmpDir);
  const tmpFilePath = `${tmpDir}/${fileName}`;
  await fileRef.download({ destination: `./${tmpFilePath}` });
```

I've verified that:

- The temporary directory is being created within the os temp dir
- Running the emulator as admin (on Windows) does not fix the do

Re: debug log, I don't have the restart issue if I don't write to a temp dir within the application folder, so not certain what there is to debug. But a better error message when the emulator restarts - ex. "file changed within emulator, restarting" - would be appreciated.

**Comment by aalej** [comment]
Hi @jelling. Thanks for the feedback! I agree that it would be helpful to have a message showing why the functions re-loads. I think my initial comment may have been misleading, so I updated it to make it clearer. Just to clarify, the emulator only reloads the functions.

Since it looks like the emulator no longer reloads the functions when you don't write to a temp dir within the application folder. I’m guessing that is the cause of the issue.

Also, just to make sure we’re on the same page. When you mentioned “is there a secret to writing files to the os.tempdir using the file emulator?”, do you mean you plan to store the temporary files in the Storage Emulator?

**Comment by jelling** [comment]
@aalej I'm saying that 1) if I write the temp files to a sub-folder inside the functions dir, then the emulator restarts, and 2) if I try writing the files to `os.tmpdir` - it's a node function - the emulator is unable to write to the application even when the emulator is running as admin on windows.

Will the emulator not restart if I write to directory higher than the functions dir?

**Comment by aalej** [comment]
Thanks for the clarification @jelling. To answer your question, yes, when updating files not within your functions directory, the emulator should not reload the functions.

Let me know if writing outside the functions directory works in your case, or if there are still any issues.

**Comment by jelling** [comment]
Writing to `os.tempdir()` works around issue so closing.
