### ISSUE TITLE
flutterfire configure generates GoogleService-Info.plist and google-services.json

### ISSUE THREAD

**Issue by flenair** [firebase/firebase-tools#6111]
<!--
Thank you for contributing to the Firebase community!

### [REQUIRED] Environment info

0.2.7

**firebase-tools:**

macOS

**Platform:**

### [REQUIRED] Test case

"flutterfire configure" generates the firebase_options.dart file (it's ok) but also GoogleService-Info.plist and google-services.json. And i wand to user just a dart file pour le firebase configuration in order to avoid to have these json file in the App.
Il a remove these file i have this error

_Launching lib/main.dart on iPhone 14 Pro in debug mode...
Running Xcode build...
Xcode build done.                                           23,0s
Failed to build iOS app
Error (Xcode): Build input file cannot be found: '/Users/flenair/Developments/macifmobiapp_flutter/ios/Runner/GoogleService-Info.plist'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro._

I'm starting my App with:

// Initialize Firebase
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

How can i have firebase working just with dart file for ios and android ?

**Comment by aalej** [comment]
Hi @flenair, based on the title of your issue, I’m thinking that this might be more related to the  FlutterFire CLI. If so, please file a ticket to the [FlutterFire CLI repository](https://github.com/invertase/flutterfire_cli/issues). 

However, if you think that this issue is caused by the Firebase Tools CLI, please specify the details using the provided template in a new ticket. This way, it would be more efficient in identifying the cause of the issue. Thanks!
