### ISSUE TITLE
Can't deploy Eventarc-triggered Cloud Function v2 with disabled default compute service account - How to specify service account used for Eventarc trigger?

### ISSUE THREAD

**Issue by jketcham** [firebase/firebase-tools#6206]
### Version info

**node:** v18.14.2

**firebase-functions:** 4.3.1

**firebase-tools:** 12.4.5

**firebase-admin:** 11.8.0

### Test case

See below.

### Steps to reproduce

Not exactly sure all the factors at play here, but I'm creating a v2 Cloud Function with node 18, using the `firebase deploy` command with firestore eventarc triggers.

The default compute service account in this project has been disabled, as recommended for security purposes. I have specified the `serviceAccount` option, both at the individual function level and as a 'global option' to use another service account in the same project, but for some reason I still get an error complaining about the default service account not being valid. This is apparently due to the default compute account being used for the eventarc triggers.

I've granted my other service account I'm trying to use the 'Cloud Datastore User', 'Cloud Run Invoker' and 'Eventarc Event Receiver' roles.

### Expected behavior

Deploy works without complaining about the default compute service account which is not referenced anywhere in my setup.

### Actual behavior

When running `firebase deploy --only functions` in a fresh repo setup with `firebase init functions`, I get this error:

```console
⚠  functions: HTTP Error: 400, Validation failed for trigger projects/prj-XXX/locations/nam5/triggers/mytrigger-123456: The request was invalid: invalid service account YYY-compute@developer.gserviceaccount.com provided
```

Despite trying to set my other service account via:

```ts
import { setGlobalOptions } from "firebase-functions/v2";

setGlobalOptions({
  serviceAccount: "sa-firestore-events@prj-XXX.iam.gserviceaccount.com",
});
```

and

```ts
export const myFunction = onDocumentCreated({
  document: "/documents/{docId}",
  serviceAccount: "sa-firestore-events@prj-XXX.iam.gserviceaccount.com",
}, (event) => { ... });
```

For reference, this is what the returned endpoint configuration looks like for the function I'm trying to deploy:

```js
{
  availableMemoryMb: ResetValue {},
  timeoutSeconds: ResetValue {},
  minInstances: ResetValue {},
  maxInstances: ResetValue {},
  ingressSettings: ResetValue {},
  concurrency: ResetValue {},
  serviceAccountEmail: 'sa-firestore-events@prj-XXX.iam.gserviceaccount.com',
  vpc: ResetValue {},
  platform: 'gcfv2',
  labels: { service: 'firestore-events' },
  eventTrigger: {
    eventType: 'google.cloud.firestore.document.v1.created',
    eventFilters: { database: '(default)', namespace: '(default)' },
    eventFilterPathPatterns: { document: 'documents/{docId}' },
    retry: false
  }
}
```

### Were you able to successfully deploy your functions?

I temporarily re-enabled the default compute service account, and after doing so with no other changes to my code, the deploy command worked, and the functions were created with the service account I specified.

I can see that the Eventarc triggers were created with the default compute service account.

**How can I specify a different service account to use for the Eventarc triggers?**

**Comment by aablsk** [comment]
We're running into the same issue (currently evaluating whether we can move from setting up EventArc & CFv2 manually to Firebase Functions, without losing control of important settings).
It seems that it tries to use the default compute service account to set up the `EventArc` trigger. Is there a way to explicitly set the service account to be used by that `EventArc` trigger?

**Comment by mvarchdev** [comment]
Same issue here!

**Comment by mvarchdev** [comment]
Similiar issue here:
```
⚠  functions: HTTP Error: 400, Validation failed for trigger projects/glassfinder-develop-uhsnm/locations/europe-west3/triggers/onglassesupdateindexalgolia-342010: The request was invalid: invalid argument: event type google.cloud.firestore.document.v1.written not supported: attribute topic not found within event type
⚠  functions:  failed to update function projects/glassfinder-develop-uhsnm/locations/europe-west3/functions/onGlassesUpdateIndexAlgolia

Error: Failed to update function projects/glassfinder-develop-uhsnm/locations/europe-west3/functions/onGlassesUpdateIndexAlgolia
Error: Process completed with exit code 1.
```

**Comment by russellwheatley** [comment]
Hello 👋 @jketcham, I took a look at this issue. As you mentioned, I disabled the default compute service account & even the App Engine default service account as a sanity check.

I created a custom service account with the 'Cloud Datastore User', 'Cloud Run Invoker' and 'Eventarc Event Receiver' roles enabled. 

I was able to deploy using both methods you mentioned:
```js

// Method 1
setGlobalOptions({
  serviceAccount: "firestore-event-arc-test@***.iam.gserviceaccount.com",
});

 exports.function_with_custom_service = onDocumentCreated({
  document: "/documents/{docId}",
// Method 3
  // serviceAccount: "firestore-event-arc-test@***.iam.gserviceaccount.com",
}, (event) => { 
  logger.info(`Event received`);
 });
```

I am using the `master` branch of `firebase-tools` for clarity. Perhaps you should try the latest version (`12.7.0`) and let me know if you're still experiencing this issue? Thanks.

Having a look through the PRs, I noticed this one that has already been released might be what resolved your issue: https://github.com/firebase/firebase-tools/pull/6389

**Comment by sconix** [comment]
We have the same issue, unable to deploy v2 firestore trigger functions with custom service account. No matter if the service account is passed in the globaloptions or function options the deploy always fails with complaint about the default compute service account being missing (which it is). Using 12.7.0 version of firebase-tools and have granted exactly the same roles for the custom service account as stated above.

**Comment by russellwheatley** [comment]
@sconix - could you provide a reproduction, please. I was not able to reproduce. Thanks!

**Comment by sconix** [comment]
> @sconix - could you provide a reproduction, please. I was not able to reproduce. Thanks!

@russellwheatley sorry for not beeing fully clear, so for us the deploy works if the SA is disabled, but two of our projects its completely missing and we have no means to create it (we are waiting for Google to resolve this issue i.e. fix our projects, but thats a secondary matter, imho Firebase should work with custom service accounts since thats Googles recommendation anyway not to use default service accounts). So you wll definitely be able to replicate this by deleting the service account, why I think this SA completely missing is related to the original report in this issue is that I am sure there is some situation where also the disabling will cause an error since the default SA is hard coded in the code so it most likely use it for some situations otherwise dont see why the check is even made that the service account exists if it would not be used for something. Since that is not our issue I can not reproduce the situation where the disabled SA would cause the same error.

If you look at the firebase-tools code it checks for existence of the compute engine service account not if its enabled or disabled, everything works for us if the service account is disabled (in those project we have the service account), but if you delete (or its not created when the API is enabled) the default Compute Engine service account then its not possible to deploy gen2 cloud functions. Since the provided service account has no effect on what checks the firebase-tools code does since it uses hardcoded compute engine service account name. Even if I modify the firebase-tools code to use custom name in place of those hardcoded compute service accounts the deploy fails to error from cloud side that the default service account is missing so atm we can not even hack the code to deploy the functions.

**Comment by joehan** [comment]
Hey @jketcham - since you tried to change this on the firebase-tools side and still ran into errors, could you open up an issue  for this in the Cloud Functions public issue tracker? https://issuetracker.google.com/issues/new?component=187195&template=0

**Comment by zac-09** [comment]
I'm also facing the same issue - 2

Problem:
I'm encountering an error when deploying Firebase Cloud Functions:

Error: <number>-compute@developer.gserviceaccount.com not found

This error occurred after the default Compute Engine service account, <number>-compute@developer.gserviceaccount.com, was deleted more than 30 days ago.

I understand that after 30 days, service accounts are permanently deleted and cannot be recovered.

so trying it with OnRequestFunctions and OnCall functions, but fails with PubSub listeners like OnMessagePublished It fails with this error: `[warn] i  functions: Failed to verify the project has the correct IAM bindings for a successful deployment. 
[warn] i  functions: You can either re-run this command as a project owner or manually run the following set of `gcloud` commands: 
[warn] i  functions: `gcloud projects add-iam-policy-binding mtailor-production --member=serviceAccount:service-734865452258@gcp-sa-pubsub.iam.gserviceaccount.com --role=roles/iam.serviceAccountTokenCreator` 
[warn] i  functions: `gcloud projects add-iam-policy-binding mtailor-production --member=serviceAccount:734865452258-compute@developer.gserviceaccount.com --role=roles/run.invoker` 
[warn] i  functions: `gcloud projects add-iam-policy-binding mtailor-production --member=serviceAccount:734865452258-compute@developer.gserviceaccount.com --role=roles/eventarc.eventReceiver` 
[debug] [2025-04-23T22:16:00.883Z] FirebaseError: Request to https://cloudresourcemanager.googleapis.com/v1/projects/734865452258:setIamPolicy had HTTP Error: 400, Service account 734865452258-compute@developer.gserviceaccount.com does not exist.
    at responseToError (/Users/isaacmubiru/.nvm/versions/node/v18.18.0/lib/node_modules/firebase-tools/lib/responseToError.js:52:12)
    at RetryOperation._fn (/Users/isaacmubiru/.nvm/versions/node/v18.18.0/lib/node_modules/firebase-tools/lib/apiv2.js:312:77)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[error] 
[error] Error: We failed to modify the IAM policy for the project. The functions deployment requires specific roles to be granted to service agents, otherwise the deployment will fail.`

**Comment by samuel-pp** [comment]
I have the same issue.
Also, I would like to know how I can proceed if I want to deploy functions with a custom service account.
Please at least tell me how to reconfigure it, or how to restore and recreate the default service account (if the function has been deleted for more than 30 days).
