### ISSUE TITLE
`.env` values are not loaded on bootstrap

### ISSUE THREAD

**Issue by ElianCordoba** [firebase/firebase-tools#6208]
### [REQUIRED] Environment info

**firebase-tools:**: 12.4.6

macOS
**Platform:**

### [REQUIRED] Test case
Repro [here](https://github.com/ElianCordoba/firebase-env-bug-repro)

### [REQUIRED] Steps to reproduce

In the repro

### [REQUIRED] Expected behavior

`dev` Should be printed in both the code initialization and the endpoint call

### [REQUIRED] Actual behavior

`dev` is only printed on the endpoint call

This is broken at least on the emulator side, I haven't tested it on a deployment. I did debug all the way down and I have a fix coming, at least for the emulator side.

**Comment by blidd-google** [comment]
Hi @ElianCordoba, the environment variables in `.env` should be defined and available through `process.env` when the source code is loaded in the production environment. However, when the CLI deploy logic loads your source locally during discovery, the environment variables in `.env` won't be available through `process.env` because the discovery process occurs before the environment variables are resolved. The CLI then passes the resolved user-defined environment variables to the Google Cloud Functions API, which handles making them available to your functions code in production. In the emulators, we make this behavior consistent; the environment variables will be available when we start the functions runtime.

If this doesn't quite answer your question, can you explain a bit more about your use case?

**Comment by ElianCordoba** [comment]
Hi @blidd-google! Sorry for the slow response, my use case was that I was trying to perform some logic (mainly logging and configuring some values) on the root of the `index.ts` file. That cause some cryptic errors which led me to realizing that the problems was the one I described, values not being ready at that moment. 
I have now changed my code to work around this, by defering the execution of that code to be inside one of the http endpoints, but I do wonder if it would be possible and something that people (aside from) would want, to have the `env` values available right away. 
This caught me off guard, I guess my intuition said, "If this value is available inside the endpoint closure, it should be available in the root, right?" I feel it's a weird semantic, not `javascripty` if I might say it :)

Also, maybe unrelated question, why does the function emulator uses that discovery mechanism? I think it should be possible to find the functions using some dependency graph analysis.

Anyways, thanks for your response, feel free to close this issue and the associated PR.

Cheers.

**Comment by blidd-google** [comment]
Definitely understand your confusion - in one sense, it only seems natural that environment variables available within a closure would also be available outside of the closure. In another sense, however, a serverless function can be thought of in principle as an enclosed and isolated unit, which presents a very different programming paradigm from "traditional `javascript`" and generally should avoid relying on values outside its scope (with the exception of some idiomatic initialization patterns, e.g. `const app = admin.initializeApp()`). When the CLI loads your source during the discovery process, its only goal is to detect the functions you want to deploy and should not be considered valid runtime behavior. I hope this clears up some of the confusion, and thanks for sharing your feedback.
