### ISSUE TITLE
Firebase CLI installation with NPM: EACCES permission denied

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-tools#6231]
### [REQUIRED] Environment info

**firebase-tools:** latest

**Platform:** macOS

### [REQUIRED] Test case

New setup with macOS Ventura 13.4.1 (c) and install NodeJS v18.17.0 which is the current latest and stable version.
Then open a terminal to install Firebase CLI.

### [REQUIRED] Steps to reproduce

1. Install NodeJS v18.17.0
2. Open terminal and run `npm install -g firebase-tools`

### [REQUIRED] Expected behavior

No error and possibly no need for sudo?

### [REQUIRED] Actual behavior

```
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/firebase-tools
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/firebase-tools'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in: /Users/username/.npm/_logs/2023-08-07T17_15_38_028Z-debug-0.log
```

<img width="923" alt="image" src="https://github.com/firebase/firebase-tools/assets/38008900/6c88eb9b-8f98-4f32-afe9-21e7c507631f">

**Comment by aalej** [comment]
Hi @ArcherEmiya05, it looks like you’re encountering this issue because you do not have the proper permissions to access specific directories. 

Given that the issue does not seem to be caused by Firebase Tools, I don’t think there is much we can do on our end. I would recommend trying out the answer provided in this [Stack Overflow post](https://stackoverflow.com/a/27265264) to see if you can try to give the correct permission to access the directories.

You could also check out this npm [documentation](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) on how to resolve EACCES issues.
