### ISSUE TITLE
shutdown requested via /__/quitquitquit  !!  functions: Failed to load function definition from source: FirebaseError: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error

### ISSUE THREAD

**Issue by RanjithKumarSeekolu** [firebase/firebase-tools#6242]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by RanjithKumarSeekolu** [comment]
Environment info: 
firebase-tools: 12.4.7
platform: windows

Test Case: 
trying to run firebase emulators:start --only functions
description: I am trying to run firebase emulator --only functions in my local

Steps to reproduce:
firebase emulators:start --only functions

Expected Behaviour:
the emulator should run successfully in my local

Actual Behaviour:
i  emulators: Starting emulators: functions
!  ui: Emulator UI unable to start on port 4000, starting on 4001 instead.
!  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, firestore, database, hosting, pubsub, storage
!  functions: Unable to fetch project Admin SDK configuration, Admin SDK behavior in Cloud Functions emulator may be incorrect.
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "E:\SkillRazr\skillrazr\functions" for Cloud Functions...
+  functions: Using node@16 from host.
Serving at port 8527

Firebase pointing to development environment

shutdown requested via /__/quitquitquit

!!  functions: Failed to load function definition from source: FirebaseError: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error

┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://127.0.0.1:4001/               │
└─────────────────────────────────────────────────────────────┘

┌───────────┬────────────────┬─────────────────────────────────┐
│ Emulator  │ Host:Port      │ View in Emulator UI             │
├───────────┼────────────────┼─────────────────────────────────┤
│ Functions │ 127.0.0.1:5001 │ http://127.0.0.1:4001/functions │
└───────────┴────────────────┴─────────────────────────────────┘
  Emulator Hub running at 127.0.0.1:4400
  Other reserved ports: 4500

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.

**Comment by aalej** [comment]
Hi @RanjithKumarSeekolu, thanks for reaching out. I tried to reproduce the issue you’re encountering, but so far I haven’t encountered any errors with starting the emulators. The error message `Failed to load function definition from source: FirebaseError: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error` usually means that there is a programmatic error in the source code. 

Could you share with us your `firebase-debug.log` file so that we can have a better overview of what caused the error? By any chance, if you can create an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) please share it as well so that we can try to reproduce the issue on our end. Thanks!

**Comment by joehan** [comment]
Closing this becuase we cannot debug issues with loading functions code without seeing your functions code (or at least a minimum viable repro of the issue).
