### ISSUE TITLE
Error deploying functions. You may not have more than 32 total max instances in your project.

### ISSUE THREAD

**Issue by 3zzy** [firebase/firebase-tools#6298]
### [REQUIRED] Environment info

12.5.1

**firebase-tools:**

macOS

**Platform:**

### [REQUIRED] Test case

Deploying functions using `firebase deploy --only functions` causes error: 
You may not have more than 32 total max instances in your project.
and some or all functions fail:
Error: There was an error deploying functions:
...

### [REQUIRED] Steps to reproduce

firebase deploy --only functions

### [REQUIRED] Expected behavior

Deploy without errors

### [REQUIRED] Actual behavior

   },
    "codebase": "default",
    "targetedByOnly": false,
    "hash": "349a607edfb7e3c3de9743d7243a1aa8d4c54845"
  },
  "op": "create",
  "original": {
    "name": "FirebaseError",
    "children": [],
    "exit": 1,
    "message": "You may not have more than 32 total max instances in your project",
    "status": 3,
    "code": 3
  }
}
Error: There was an error deploying functions:
- Error Failed to create function auth-onWriteUser in region asia-east2
- Error Failed to create function fetchXero in region asia-east2
- Error Failed to create function services-onWriteClearanceRequest in region asia-east2
- Error Failed to create function auth-sendTOTPEmail in region asia-east2

**Comment by blidd-google** [comment]
Unfortunately it's difficult to say what's wrong from the limited information above. Can you give more details about your deployment and provide a reproducible example? Are you setting a limit on maximum instances?

**Comment by 3zzy** [comment]
Log contains env variables and lots more details which I'm not able to share publicly. 
It was working fine just a few days ago, this started happening suddenly. 
I'm not setting any max limit, in fact I'm happy to increase it and just fix this issue ASAP cause login functions aren't working.
1st Gen functions.

**Comment by jWyb** [comment]
I'm chiming in as I've encountered the exact same "You may not have more than 32 total max instances in your project." deployment error. 

A few key points:
**Error Details:** Like @3zzy, my deployment using firebase deploy --only functions yields the "You may not have more than 32 total max instances in your project" error. This results in all of my functions failing to deploy.
**Recent Changes:** It's worth noting that my functions were deploying without this error until recently (last deploy Aug. 22). I'm unaware of any changes on my end that might have prompted it.
**Function Generations:** I'm working with 1st Gen functions.

I've been troubleshooting this on my end and came across this section in the Troubleshoot App Engine Errors guide for this error message: https://cloud.google.com/appengine/docs/standard/troubleshooting#max-instances-limit.
I can't really see how this applies to the Firebase Cloud Functions, especially since a app.yaml file is not used and there where no changes on my side since the last successful deploy. That makes me believe that there might be an issue on Firebase side. 

Hope this gets resolved soon, since it's blocking any deployment to my production firebase cloud functions.

**Comment by devjoter** [comment]
I am facing same situation, suddenly deploying functions hits the wall with this message: You may not have more than 32 total max instances in your project. However deploying code in difrient project is completed with nos issues. Its 1`st gen functions where instances count is unlimited...right? Here is the basic code i use: `const functions = require("firebase-functions");
// const logger = require("firebase-functions/lib/logger");

exports.helloWorld = functions.region("europe-west3")
    .https.onRequest((request, response) => {
      // logger.info("Hello logs!", {structuredData: true});
      response.send("Hello from Firebase!");
    });
`

**Comment by iaineh** [comment]
Same issue here no real changes to functions but nothing can be deployed. The error message seems legit though, when I reduced the TOTAL max instances to <= 32. I could deploy, it sucks a bit because I had to delete all the functions / extensions to get the total count so low then redeploy with 1 instance per function.

<img width="381" alt="image" src="https://github.com/firebase/firebase-tools/assets/1019007/4d9e21c6-6245-424a-9147-750644ab84f6">

```
export const generate = functions
    .runWith({
      maxInstances: 1,
    })
```

This happens regardless of the functions code or the firebase-tools version. If I was going to guess, I could say something has happened in GCP Functions and they have implemented a 32 total max instance on all of our accounts behind the scenes. For whatever reason... This is prohibitively low for anyone tbh, especially with the defaults of 3000 per function for gen1 :)

So likely a fix required from the GCP team here. As a work around you can drop the maxInstances low enough for critical functions but you will need to delete before deploying to get the total count low enough.

**Comment by wcoder** [comment]
I'm facing the same situation, suddenly deploying functions hits the wall with this message: 
```
You may not have more than 32 total max instances in your project.
...
Error: There was an error deploying functions:
- Error Failed to update function XXX in region europe-central2
...
```

**Comment by tal952** [comment]
Same here. 
I tried to find the the quota in https://console.cloud.google.com/iam-admin/quotas
but no luck.

**Comment by aaguueeroo** [comment]
I have the same issue. I received an email a week ago saying that they would decrease the number of free functionalities of Firebase, and all the questions that I see online related to this are from yesterday. Is it probably related to this? Will it solve upgrading the plan?

**Comment by Daves-Ventures** [comment]
Joining in on this, as it bothers the hell out of me. For me, this error only occurs when installing an extension, but I was able to successfully deploy the functions I had written myself. The extension (Stripe payments)  uses 1st gen functions, of which none could successfully deploy, given the same error as seen by my predecessors. 

I've started a [thread on Stack Overflow ](https://stackoverflow.com/questions/76978052/firebase-extension-stripe-payments-keeps-failing-to-deploy-resources) on this topic, on which I was advised to access the "advanced settings" and reduce the "maxInstances" value to below 32, however, when doing so in an individual function the results are the same.

**Comment by Daves-Ventures** [comment]
Try deploying the functions to another region i.e. us-central-1 -- I had my issues resolved after changing the region, when attempting to deploy to eu-west-3, I received the 32 max instrances error, when deploying to us-central-1, the error did not occur.

**Comment by 3zzy** [comment]
Tried deploying to a different region.
Tried setting maxInstances to 1.
.... still the same error.

It amazes me that there is such a significant problem and no one from Google is even making an effort to notice it.

**Comment by tal952** [comment]
Please upvote:
https://issuetracker.google.com/issues/297544165

**Comment by evilandfox** [comment]
Got the same errors. Some functions are deploying without errors, excluding two functions. Tried to delete them before deploying and it worked. Anyway, it looks like a bug, so waiting for a fix from Google Team.

**Comment by SchoenigerFabian** [comment]
Same here. Function deployment worked till yesterday or so. Getting the max instance error on document trigger functions as well as on https. Regions is europe-west3. Upvote: https://issuetracker.google.com/issues/297544165

**Comment by devjoter** [comment]
I gave it a try today and  changed the region, finaly got my function deployed. I seems like something started to move forward...

**Comment by CarlTonsgard** [comment]
Same issue for me. Gen 1 functions cause this error when deployed to europe-west 3. Gen 2 functions work for me. Changing the deployment region for all gen-1 functions to europe-west-1 works in my case.

**Comment by evilandfox** [comment]
and no official answer yet...

**Comment by evilandfox** [comment]
I've learned how to fix it. This error depends on function region (`europe-central2` in my case).
1. Find problematic region and notice functions deployed there.
2. Update code of this functions changing maxInstances option. Sum of them must not be greater that 32.
3. Delete current functions.
4. Deploy them with updated code.

Example of function with updated option:
```typescript
export const hello = functions
  .region('europe-central2')
  .runWith({ maxInstances: 16 })
  .https.onCall(async (data, context) => {
    return {result: 'world'}
  })
```

**Comment by SchoenigerFabian** [comment]
Deployed my functions today on eu-west1 | west2 | west6 without trouble. No additional changes, only region. West3 still fails. It seems possible that the max instance issue is depending on your most used location (like in my case eu3) where I have round about 50 functions. On the other hand I don't get how it could lead to that error because I always understood instances as per function invocation instance and not the overall amount of functions on a location.

**Comment by Daves-Ventures** [comment]
Thanks everyone for their input, especially @evilandfox for the ".runWith({ maxInstances: 16 })" code-bit, which I didn't know about myself just yet.

However, after a little further debug, I noticed that (for me anyways) mainly is an issue with "updating" functions. Meaning MY error resolve, is changing the region multiple times whenever I update a function / test a function (which means it'll run the delete operation and then a create operation). 

Once the function is running "flawless" and/or as "intended" I change region variable of all functions to something I don't use i.e. europe-central2, and then BACK to the one I tend to use (europe-west3, which is the location of my database).

**Comment by tal952** [comment]
Hey @joehan and @blidd-google , any news about that? 
It's unbelievable that such a critical issue left unhandled for so long...
Our current situation is that we must delete all existing functions and re-upload them with very low max instance setting.
Is there a way to override this constraint? some sort of force update or something?

**Comment by Ceraz-CV** [comment]
@tal952 100% agree with you. I hope this will be fixed soon. 
It seems like a workaround is to use a different deployment location. In Europe `europe-west-1` seems to work without this issue.

**Comment by taeold** [comment]
Hi folks. We worked with the Google Cloud Functions team to rollback the aggressive quota enforcement that affected many of you who commented in this thread. Apologies for conveniences, and if you continue to have problem related to quota, please reach out to [Firebase Support](https://firebase.google.com/support)
