### ISSUE TITLE
Firebase firestore wont delete collection made from macos

### ISSUE THREAD

**Issue by jesussmile** [firebase/firebase-tools#6307]
This is an ongoing issue with macos, everytime i create a firebase collection i can't delete it. 

These are the issue:
Even though there are no documents in firestore, it will still show on my flutter app when i run it, looks like it is holding onto some cache or sth.

Then when i try to delete it from the firestore manually it will get stuck.
This is causing me to recreate a new project everytime because i just can't delete the firestore collection what is the issue here?

it is stuck on delete this collection..?

<img width="1680" alt="Screen Shot 2023-08-28 at 7 52 57 PM" src="https://github.com/firebase/firebase-tools/assets/11044978/632c0bf3-21a2-4b7c-9ea7-7b5231067e53">

**Comment by aalej** [comment]
Hi @jesussmile, based on the screenshot you provided, the error you’re encountering is with your Firebase project. Could you reach out to our [Firebase support team](https://firebase.google.com/support/troubleshooter/contact)? They will be able to assist you better since they’ll have visibility on your project. You may share your project details with them so that they can assist you further. 

That said, I’ll be closing this ticket. Thanks!
