### ISSUE TITLE
firebase login causing browser redirect to http://localhost:9005/

### ISSUE THREAD

**Issue by mikkimichaelis** [firebase/firebase-tools#6347]
### [REQUIRED] Environment info
12.5.3

**Platform:**
Ubuntu 22.04

I installed the firebase cli from here

```bash
curl -sL https://firebase.tools | bash
```

the logged in with 
```bash
firebae login
Visit this URL on this device to log in:
https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=955874520&redirect_uri=http%3A%2F%2Flocalhost%3A9005

Waiting for authentication...
```

Following the link I authenticated and my browser was redirected to 

**http://localhost:9005**/?state=955874520&code=4/0Adeu5BUcUt37oBkbz4cRFPwbdR6Yn5kWLxwkW-BvNW9h3RPADT0C6EsVhPMGdsFOaIffDg&scope=email%20https://www.googleapis.com/auth/userinfo.email%20openid%20https://www.googleapis.com/auth/cloudplatformprojects.readonly%20https://www.googleapis.com/auth/firebase%20https://www.googleapis.com/auth/cloud-platform&authuser=0&prompt=consent

This is clearly somebody's development redirect which slipped into production.  It happens.  Please fix.  Thank you.

**Comment by mikemoone** [comment]
@mikkimichaelis I also ran into this issue.  For me, Chrome was automatically redirecting any http localhost to https, and it wasn't finding an auth server running at https://localhost:9005 (because it was running at http://localhost:9005).  This is how I resolved it:

1. Enter chrome://net-internals/#hsts into the Chrome browser
2. Type "localhost" into the last box (Delete domain security policies)
3. Press the "Delete" button

Hope that helps
