### ISSUE TITLE
Require only necessary lodash methods

### ISSUE THREAD

**Issue by merlinnot** [firebase/firebase-tools#635]
Requiring whole library to use one or few of it’s methods unnecessarily slows down the app. See https://github.com/firebase/firebase-tools/pull/632#discussion_r163708223

**Comment by HunterSHeston** [comment]
@merlinnot @mbleigh If it's still something that is still necessary. I wouldn't mind giving this a shot!

**Comment by bkendall** [comment]
PRs are always welcome 😄

**Comment by joehan** [comment]
This was a very good idea at the time, and I spent a good amount of effort pushing toward this myself. However, the per method lodash  packages have since been depredated, and per https://www.blazemeter.com/blog/import-lodash-libraries, there is no particular benefit to `import {blah} from 'lodash'` over just `import * as _ from 'lodash'`

As such, closing this.
