### ISSUE TITLE
Deploying Extensions does not respect --force

### ISSUE THREAD

**Issue by abegehr** [firebase/firebase-tools#6350]
### [REQUIRED] Environment info

**firebase-tools:** 12.5.2

**Platform:** macOS

### [REQUIRED] Test case

Any project with an extension configured.

### [REQUIRED] Steps to reproduce

1. Setup an extension in a Firebase project and run `firebase init` to sync it to source code.
2. Change a setting on the extension in the Firebase project.
3. Deploy the Firebase project using `firebase deploy -f` (or `--force`). 

### [REQUIRED] Expected behavior

I would expect the force option to deploy with force and therefore not asking me to confirm any overrides.

### [REQUIRED] Actual behavior

The force deploy fails due to the extension edit in Firebase console: (example from a GH action)

```
i  extensions: ensuring required API firebaseextensions.googleapis.com is enabled...
✔  extensions: required API firebaseextensions.googleapis.com is enabled
The following instances may have been changed in the Firebase console or by another machine since the last deploy from this machine.
	firestore-send-email
If you proceed with this deployment, those changes will be overwritten. To avoid this, run `firebase ext:export` to sync these changes to your local extensions manifest.
? Do you wish to continue deploying these extension instances? (y/N) 
Error: Process completed with exit code 130.
```

**Comment by aalej** [comment]
Hi @abegehr, thanks for reaching out. It looks like the issue you’re experiencing is similar to [#6321](https://github.com/firebase/firebase-tools/issues/6321). Please update to the latest version of `firebase-tools`, which is currently [v12.5.3](https://github.com/firebase/firebase-tools/releases/tag/v12.5.3), since it contains a [fix](https://github.com/firebase/firebase-tools/pull/6337) for this.
