### ISSUE TITLE
MODULE_NOT_FOUND, TypeError: readable.getReader is not a function among other errors while running a next.js project locally.

### ISSUE THREAD

**Issue by aikooo7** [firebase/firebase-tools#6355]
### [REQUIRED] Environment info

**firebase-tools:** 12.5.3

**Platform:** Windows

### [REQUIRED] Test case

Doing a out of the box next.js project was enough to recreate the problem.

NOTE: I also tried using my own page file with a simple hello world h1 header and tried other with the same hello world but with firebase authentication.

### [REQUIRED] Steps to reproduce

1 - npx create-next-app your-firebase-next-app                    # Using typescript, eslint, src folder and app router.
2 - firebase init                                                                      # Firebase functions, realtime database and hosting
3 - Either firebase emulators:all or firebase serve --only hosting

### [REQUIRED] Expected behavior

Be able to see either the default next.js page or my own.

### [REQUIRED] Actual behavior

A bunch of errors about "TypeError: readable.getReader is not a function" and MODULE_NOT_FOUND wirth "Cannot find module './commands/config.js'".

[ui-debug.log](https://github.com/firebase/firebase-tools/files/12580941/ui-debug.log)
[database-debug.log](https://github.com/firebase/firebase-tools/files/12580942/database-debug.log)
[firebase-debug.log](https://github.com/firebase/firebase-tools/files/12580943/firebase-debug.log)
[firestore-debug.log](https://github.com/firebase/firebase-tools/files/12580944/firestore-debug.log)

**Comment by aikooo7** [comment]
Let me know if I did something please, I did edit to remove a ":" I added, if it wasn't that then let me know.

**Comment by aikooo7** [comment]
@aalej any updates?

**Comment by aalej** [comment]
Hey @aikooo7, apologies for the delay in updates. I tried to reproduce the issue you mentioned by following the provided steps, but I did not encounter any errors when starting the emulator and accessing the locally hosted Next.js app. 

Let me know in case I’m missing anything, from what I can gather your project structure would look similar to [this](https://github.com/aalej/issues-6355). By any chance, if you can provide a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example), please share it as well so that we can try to reproduce the issue on our end. 

Also, just to verify, does the error `TypeError: readable.getReader...` get raised on the web app after accessing it locally? I tried looking through the debug logs you provided and I could not find this error log.
