### ISSUE TITLE
Emulator doesn't work with demo projects + web frameworks

### ISSUE THREAD

**Issue by sqrrrl** [firebase/firebase-tools#6377]
### [REQUIRED] Environment info

**firebase-tools:**
12.5.4

**Platform:**
ChromeOS/linux

### [REQUIRED] Test case

1. Setup with  firebase init
- Select firestore, hosting, functions
- defaults for everything except hosting
  - Select use frameworks, vite, javascript

2. Run firebase emulators:start --project demo-x

So far things work OK.

3. Kill the emulator
4. cd hosting
5. npm i --save firebase
6. cd ..
7. run firebase emulators:start --project demo-x

Expected to run fine, but fails with error:

Error: could not find sites for project "demo-x"
 
### [REQUIRED] Steps to reproduce

See above

### [REQUIRED] Expected behavior

Adding firebase as a dependency to the web framework should still work with demo projects.

### [REQUIRED] Actual behavior

fails with error:
Error: could not find sites for project "demo-x"

**Comment by sqrrrl** [comment]
Appears to be here:

https://github.com/firebase/firebase-tools/blob/master/src/frameworks/index.ts#L207

Since everything that follows in that block seems optional (it's all skipped if no matching site) maybe just catch/log and continue?

**Comment by sqrrrl** [comment]
Not sure if related, but also noticed that the default config is not correctly configuring functions to talk to the emulator. I'm curious if this is because it's trying to configure based on a live project where functions haven't been deployed yet? Or is that a separate issue?

**Comment by DevJoghurt** [comment]
Found the same error. It can be solved by linking an active Firebase project. Of course it would be nice if it would work in emulator mode without an active project.

**Comment by phcoliveira** [comment]
This seems to be a regression. I use to have a `preview` script in which I simply used `NODE_ENV=production firebase emulators:start`. With that command, Firebase Hosting was smart enough to determine that the application should be built, instead of served. From there, Firebase Hosting itselt hosted the application.
Now I have to use `firebase emulators:exec --only=auth,database 'vite build && vite preview --port 5173'` for a similar effect. The main difference now is that vite is serving the application, not Firebase Hosting.

**Comment by DevJoghurt** [comment]
I have tried the latest version (13.1.0) but still get the following error: 

`Error: could not find sites for project "demo-x"`

**Comment by leoortizz** [comment]
My apologies, #6674 fixed an issue with Vite and emulators but not this issue.
