### ISSUE TITLE
Auth emulator pop up hangs in recent versions of chrome

### ISSUE THREAD

**Issue by nyonson** [firebase/firebase-tools#6395]
### [REQUIRED] Environment info

**firebase-tools: 12.5.4**

**Platform: Linux**

### [REQUIRED] Test case

Use any social auth provider with the `signInWithPopup` function.

### [REQUIRED] Steps to reproduce

Login or sign up using a social auth provider using the Chrome or Chromium browser.

### [REQUIRED] Expected behavior

Auth emulator displays it's social auth login/create account screen.

### [REQUIRED] Actual behavior

The pop up freezes and becomes unresponsive. It does not appear to be deterministic when it freezes exactly.

**Comment by joehan** [comment]
Hey @nyonson, thanks for reporting this. If possible, could you provide any of the following to help us debug?
- `--debug` logs from the running emulator
- Any errors thrown by the popup (you can check using Chrome dev tools - https://developer.chrome.com/docs/devtools/open/)
- A minimal viable repro

**Comment by nyonson** [comment]
Hi @joehan ,

No luck running with the `--debug` flag, nothing shows up in the logs. I have tried a bunch debugging with chrome dev tools, but also can't find any output. I noticed too that if I set the "Auto open DevTools for popups" setting to try in capture what is going on, both windows are blank...

**Comment by aalej** [comment]
Hi @nyonson, I’m trying to reproduce the behavior you mentioned, but so far I haven’t encountered any issues when trying to use the `signInWithPopup` method.

Can you please try to reproduce the issue using this [sample code](https://github.com/aalej/issues-6395)? If there's anything I'm missing or if I made a mistake, please let me know. Also, could you let us know which version of Node and Chrome you’re using? 

It would be difficult to investigate what’s causing the issue without logs. By any chance, if you’re unable to reproduce the issue using the sample code, it would be helpful if you could provide a [Minimal, Complete, and Verifiable Example](https://stackoverflow.com/help/minimal-reproducible-example) (MCVE). This is so that we can replicate the issue on our end.
