### ISSUE TITLE
`firebase emulators:start --inspect-functions` breaks the args passing into functions

### ISSUE THREAD

**Issue by VagishVela** [firebase/firebase-tools#6401]
When you run things `firebase emulators:start --inspect-functions` and then use req.args.get(xyz) it is empty, when you remove `--inspect-functions` the args then pass through.

We use folders for various functions are mostly node apart from python which is why we hit this issue as we use it to debug the node ones.

I'll see if I can add the logs I got, by recreating the issue later.

**Comment by aalej** [comment]
Hi @VagishVela, could you please provide additional details about the issue such as the debug logs when running `firebase emulators:start --inspect-functions --debug`. Additionally, could you provide more details about this such as, but not limited to:

- Detailed steps to reproduce the issue
- Code snippets from you Node.js and Python functions
- Expected behavior after following the steps to reproduce the issue
- Actual behavior after following the steps to reproduce the issue

This will help us have a better overview of the issue. Thanks!
