### ISSUE TITLE
Emulator functions with error when start

### ISSUE THREAD

**Issue by felipej26** [firebase/firebase-tools#6433]
### [REQUIRED] Environment info

**firebase-tools:** emulator

**Platform:** functions

### [REQUIRED] Steps to reproduce

```
import {onCall, HttpsError} from "firebase-functions/v2/https";
import {logger} from "firebase-functions";
import {getFirestore, Timestamp} from "firebase-admin/firestore";
import {getDatabase} from "firebase-admin/database";
import {initializeApp} from "firebase-admin/app";

const matchesApp = initializeApp({
  databaseURL: "https://guess-the-flag-c4195-matches.firebaseio.com/",
}, "matches");

const queuesApp = initializeApp({
  databaseURL: "https://guess-the-flag-c4195-queues.firebaseio.com/",
}, "queues");

const firestore = getFirestore();

exports.addMessage = onCall(async (request) => {
  const text = request?.data?.text;
  const playerName = request?.data?.playerName;
  const date = Timestamp.now();

  const roomId = "1234";

  try {
    await getDatabase(matchesApp).ref(`/matches/${roomId}/messages/`).push({
      playerName,
      text,
      date,
    });
    logger.info("New Message written");
    return {
      playerName,
      text,
    };
  } catch (error: any) {
    throw new HttpsError("unknown", error.message, error);
  }
});

exports.addUserToMatchQueue = onCall(async (request) => {
  const userId = request?.data?.userId;
  const date = Timestamp.now();

  if (!userId) return;

  const ref = firestore.collection("matches").doc("queues");

  await ref.set({
    userId,
    date,
  });

  return getDatabase(queuesApp).ref(`/users/${userId}`).push({
    date,
  })
    .catch((error: any) => {
      throw new HttpsError("unknown", error.message, error);
    });
});

```

### [REQUIRED] Expected behavior

I want to connect my functions with the realtime database and cloud firestore.

### [REQUIRED] Actual behavior

When I run the command `firebase emulators:start` I get the message:

`⬢  functions: Failed to load function definition from source: FirebaseError: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error`

firebase-debug.log:

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/12822141/firebase-debug.log)

**Comment by felipej26** [comment]
I've found the problem, I had more files under `src` folder, I removed them and it worked as expected.
I will close this issue ;)

**Comment by sanderschnydrig** [comment]
I suddenly get the same error message since yesterday

**Comment by aalej** [comment]
Hey @felipej26, thanks for providing code snippets and debug logs. It looks like the cause of the error is because you didn’t initialize a default app, since `matchesApp` is an instance of an app with the name of “matches” and `queuesApp` is an instance of an app with the name of “queues”. 

From what I can tell, you are accessing the Firestore service for the App `matchesApp` which has the name of “matches”. To do this, could you try changing:
```ts
const firestore = getFirestore();
```
To
```ts
const firestore = getFirestore(matchesApp);
```

**Comment by aalej** [comment]
Thanks @sanderschnydrig for sharing your debug logs. I’m thinking that the cause of the error in your case is that there is a runtime or syntax error with your code that is preventing the Firebase CLI from analyzing your functions.

Could you provide a sample code snippet where the issue is reproducible?
