### ISSUE TITLE
Could not create or update Cloud Run service, Container Healthcheck failed

### ISSUE THREAD

**Issue by remie** [firebase/firebase-tools#6465]
### [REQUIRED] Environment info

**firebase-tools:** 12.6.2

**Platform:** CircleCI (cimg/node:16.18-browsers)

### [REQUIRED] Test case

We use the following code to export the Cloud Tasks:

```
export const registerTaskHandlers = (container, options = {
    retryConfig: {
        maxAttempts: 3,
    },
    memory: '4GiB',
    timeoutSeconds: 1800
}) => {
    const appContainer = typeof container === 'function' ? container() : container;
    const taskHandlers = appContainer.isBound(TaskHandlers) ? appContainer.getAll(TaskHandlers) : [];
    taskHandlers.forEach(handler => {
        !isProduction() && logger.log(`[${handler.name}] Registering Task ${handler.name}`);
        module.exports[handler.name] = onTaskDispatched({ ...options, ...(handler.options || {}) }, ({ data }) => handler.process(data));
    });
};
```

The Cloud Task exports are picked up during `yarn run firebase deploy -f --only functions` in the CircleCI container:

> i  functions: updating Node.js 16 (2nd Gen) function VCSDeleteProjectConflictsTask(us-central1)...
i  functions: updating Node.js 16 (2nd Gen) function VCSDeleteProjectEntitiesTask(us-central1)...
i  functions: updating Node.js 16 (2nd Gen) function VCSDeleteScheduledJobTask(us-central1)...
i  functions: updating Node.js 16 (2nd Gen) function VCSLinkedProjectCreatedTask(us-central1)...
i  functions: updating Node.js 16 (2nd Gen) function VCSLinkedProjectDeletedTask(us-central1)...
i  functions: updating Node.js 16 (2nd Gen) function VCSLinkedProjectUpdatedTask(us-central1)...
i  functions: updating Node.js 16 (2nd Gen) function VCSPurgeConflictsTask(us-central1)...
i  functions: updating Node.js 16 (2nd Gen) function VCSPurgeOrphansTask(us-central1)...
i  functions: updating Node.js 16 (2nd Gen) function VCSPurgeTasksTask(us-central1)...
i  functions: updating Node.js 16 (2nd Gen) function VCSPurgeWebhooksTask(us-central1)...
i  functions: updating Node.js 16 (2nd Gen) function VCSSettingsUpdatedTask(us-central1)...
i  functions: updating Node.js 16 (2nd Gen) function VCSStateVerificationTask(us-central1)...
i  functions: updating Node.js 16 (2nd Gen) function VCSSynchroniseTask(us-central1)...

### [REQUIRED] Steps to reproduce

N/A

### [REQUIRED] Expected behavior

I would expect Firebase to register the Cloud Task and take care of all the plumbing in order to make `onTaskDispatch` work.

### [REQUIRED] Actual behavior

The firebase deploy fails with the following error:

> Could not create or update Cloud Run service [NAME], Container Healthcheck failed. Revision '[REVISION]' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.

I am more than happy to provide actual GCP project information and log files privately if necessary.

**Comment by remie** [comment]
Ok, after some digging around I've discovered that the issue was actually related to some 1st gen code still being executed, which caused the 2nd gen deployment to fail. After migrating the v1 code to v2, the deployment succeeded.

Unfortunately, the deployment message was unclear. Perhaps this issue can be adjusted to provide better logging of failed deployment because the health check failure itself was not the real problem, it was the consequence of a deployment failure.

**Comment by taeold** [comment]
@remie Thanks for following up and lettings us know about the issue.

To make sure I understand the issue - the healthcheck failure was real, and it was because code related to 1st Gen function was failing for 2nd Gen?

What message was actually helpful in debugging your issue? I would love to find a way to expose them in the cli if possible.

**Comment by mudigone** [comment]
Hey any update? I am facing this issue. I have a repo that uses alot of v1 cfs but have started to move the newer ones to v2, it has been working so far not sure what went wrong with this one.

**Comment by mudigone** [comment]
okay so I did something and it just worked fine, so I changed the structure of how my cloud functions were and introduced a new structure and in my index js I was importing index js of another root folder which exported all the cfs in the above folder. So one of the exports had a wrong case letter to the connected file and due to which gcp couldn't find the root target and I was getting the error, fixing that worked for me.

**Comment by cyberpwnn** [comment]
This is now happening for me all of the sudden.

**Comment by waqadArshad** [comment]
Same here. adding a new 2nd Gen onSchedule function while all others are v1 functions, causes:

```
Could not create or update Cloud Run service sendschedulednotifications, Container Healthcheck failed. Revision 'sendschedulednotifications-00001-gem' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.
```

**Comment by nickjuntilla** [comment]
I've spent 24 hours on this and still can't find the answer. We're being forced to upgrade to Gen 2 in september and i can't even deploy a test Gen 2 without failure. Even the most basic example of printing out the date from the docs doesn't work. It's always the same message.

"Could not create or update Cloud Run service test, Container Healthcheck failed. Revision 'test-00001-dah' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information."

Although it mentions a port I don't think it has anything to do with a port. Even responding to a simple http request fails. Even this fails:
exports.date = onRequest((req, res) => {
  const date = new Date();
  console.log(date)
});

**Comment by HosokawaHazuki** [comment]
おかしな場所でnpm installを行っていることが原因かもしれません。
npm installによって作成されたnode_modulesフォルダをすべて削除し、再度npm install→deployを行うとうまくいきました。

**Comment by nickjuntilla** [comment]
I found the answer to this for me in case anyone has the same issue. If you have Gen 1 and Gen 2 functions in the same file and you have a functions.config() ANYWHERE in your project your gen2 functions will not work. Unfortunately the error for this is that obscure port error and "unknown trigger" message. The fix is to convert your entire project to parameterized configuration: https://firebase.google.com/docs/functions/config-env?gen=2nd#params

Again even if you don't use functions.config() in your gen 2 functions, they will kill your deployment. Firebase makes it seem like you can mix and match gen1 and gen2, BUT YOU CANNOT. There might be a way if you use the new code division features, but with a regular project you cannot do it. Unfortunately this is not documented.

**Comment by AndyKgotatso** [comment]
I had to make this change 

- With Green lines being what I updated my index file to, for Gen2 functions to deploy/work
![image](https://github.com/user-attachments/assets/3bee1c3f-ab73-42cb-8795-826a8960919e)

**Comment by Soolan** [comment]
For anyone who is still suffering from this - misleading - error message:
For some reason, Firebase and Cloud Run keep bits and pieces of Gen 1 libs in unexpected ways.
The way that I finally overcame the issue was a deep clean up.
Yes that includes wipe out the entire functions/node_modules followed by npm i.

After that search your entire code and replace any reference to functions.config() with process.env
BELIEVE IT OR NOT, THAT INCLUDES COMMENTED CODES ALSO `initializeApp()`
  
 As silly it sounds, if you are deploying function a() and somehow in your function b() - which you are not deploying- there is `functions.config()` hidden somewhere, your deployment will fail.
 
 Do the clean up.

**Comment by petrvecera** [comment]
> I found the answer to this for me in case anyone has the same issue. If you have Gen 1 and Gen 2 functions in the same file and you have a functions.config() ANYWHERE in your project your gen2 functions will not work. 

This was the issue for me.   Btw extremely dissatisfied with Gen2, the documentation is awful. I can't find single example of proper full blown function configuration. Everywhere they have super simple functions. 😠

**Comment by taishi55** [comment]
> おかしな場所でnpm installを行っていることが原因かもしれません。 npm installによって作成されたnode_modulesフォルダをすべて削除し、再度npm install→deployを行うとうまくいきました。

He says you can resolve once you delete the node_module and reinstall by `npm install` under `/functions`. 

I tried this and it worked. Thanks!

**Comment by Yashasewi** [comment]
### **Error**
Firebase Cloud Functions v2 "Container Healthcheck failed" .

<details>
<summary>Complete Error </summary>

Could not create or update Cloud Run service FUNCTION_NAME, Container Healthcheck failed. Revision 'FUNCTION_NAME-00002-gom' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable within the allocated timeout. This can happen when the container port is misconfigured or if the timeout is too short. The health check timeout can be extended. Logs for this revision might contain more information.

Logs URL: https://console.cloud.google.com/logs/viewer?project=YOUR-PROJECT-NAME&resource=cloud_run_revision/service_name/FUNCTION_NAME/revision_name/FUNCTION_NAME-00002-gom&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22FUNCTION_NAME%22%0Aresource.labels.revision_name%3D%22FUNCTION_NAME-00002-gom%22 
For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start
Could not create or update Cloud Run service requestarticleexport, Container Healthcheck failed. Revision 'requestarticleexport-00002-xuc' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable within the allocated timeout. This can happen when the container port is misconfigured or if the timeout is too short. The health check timeout can be extended. Logs for this revision might contain more information.

</details>

### **Problem**

> After wasting my a hour in GCP and figuring out which port and cloud build images and artifacts (and what not ) ... I saw this code in my project .. 
```javascript
// This syntax doesn't work
if (dev_mode) {
  db = admin.firestore('database-name');
  storage = admin.storage('bucket-name');
}
```
Firebase Cloud Functions (2nd Gen) failing to deploy with "Container Healthcheck failed" errors, but only when a specific environment variable was enabled (e.g., `DEV_MODE=true`). and then i dig deeper and found that 

### **Root Cause**
Incorrect Firebase Admin SDK syntax when trying to use named databases and storage buckets conditionally. 

> The error mentioned in the logs is not helpfull at all .

**The Issue:**
```javascript
// This syntax doesn't work
if (dev_mode) {
  db = admin.firestore('database-name');
  storage = admin.storage('bucket-name');
}
```

### **Solution**
Use proper Firebase Admin SDK v12+ syntax:

```javascript
// Correct approach
const app = admin.initializeApp({
  credential: admin.credential.applicationDefault(),
  storageBucket: process.env.STORAGE_BUCKET, // put your bucket name
});

if (dev_mode) {
  db = admin.firestore(app, 'database-name');  // Pass app instance
} else {
  db = admin.firestore(app);
}
const storage = getStorage(app);
const auth = admin.auth(app);  // Pass app to all services
```

This fixed the deployment issues completely!

**Comment by capps096github** [comment]
I got the same issue and spent close to 4 hours figuring it out, and later found the solution was migrating some of my v1 Firebase functions to v2

Error

> Could not create or update Cloud Run service api, Container Healthcheck failed. Revision 'api-00001-rom' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable within the allocated timeout. This can happen when the container port is misconfigured or if the timeout is too short. The health check timeout can be extended. Logs for this revision might contain more information.

Fix
<img width="1261" height="265" alt="Image" src="https://github.com/user-attachments/assets/6d3719c3-f74c-49c7-aa35-aa77c7fa30c7" />
