### ISSUE TITLE
At the moment only one tenant, and GetContext() Throws following error

### ISSUE THREAD

**Issue by provider12** [firebase/firebase-tools#6512]
At the moment only one tenant, and GetContext() Throws following error
Federated service at URL returned error: Authentication Failure

AADSTS900561: The endpoint only accepts POST requests. Received a GET request.

_Originally posted by @Mastahh in https://github.com/pnp/pnpframework/issues/88#issuecomment-757860607_

**Comment by aalej** [comment]
Hey @provider12, taking a look into the issue you mentioned, it does not look like the issue you’re encountering is related to the Firebase CLI. That said, I'll be closing this for now. 

If you are experiencing an issue with the Firebase CLI, please file a new issue specifying the details using the provided template. This would give us a better overview of the issue you’re encountering so that we can start our investigation. Thanks!
