### ISSUE TITLE
Function fails to deploy

### ISSUE THREAD

**Issue by kr05** [firebase/firebase-tools#659]
### Version info

3.17.4

### Steps to reproduce

I'm having trouble deploying my cloud function. I checked the firebase status dashboard and everything seems to be ok. The deployment gets stuck at "updating function" and statys like for about 10 minutes until it simply stops. In the logs, it simply says "operation interrupted". Any idea on what the problem might be? 

### Expected behavior

Function deploys successfully.

### Actual behavior

Function doesn't deploy successfully.

**Comment by manucho007** [comment]
I'm having problems also deploying functions, but I get a different message:
![image](https://user-images.githubusercontent.com/17936451/35880612-cbb2e87c-0b54-11e8-8310-1bded5934e33.png)

**Comment by apwelsh** [comment]
I am still having this issue.   I did discover that if I tether off my cell phone, it works 100% of the time, but on my LAN it fails 100% of the time.  The best I can guess is that it may have to do with my LAN IP range, since both solutions use IPv6+v4 dual stack network, and my LAN is substantially faster at 100Mbps than my cell at 30Mbps max.

**Comment by laurenzlong** [comment]
@manucho007 Open up firebase.json, delete the fields "predeploy" and "postdeploy", which are under "functions"

**Comment by laurenzlong** [comment]
Let's consolidate comments on this to #822 (comment). Please follow my instructions on that comment for workarounds. This is a high priority bug for us to fix, unfortunately it's not straightforward.
