### ISSUE TITLE
Firebase emulators won't start

### ISSUE THREAD

**Issue by starleaf1** [firebase/firebase-tools#6597]
### [REQUIRED] Environment info

**firebase-tools:**
13.0.1

**Platform:**
Ubuntu

### [REQUIRED] Test case

Start a Firebase emulator by running `firebase emulators:start`

### [REQUIRED] Steps to reproduce

Same as above

### [REQUIRED] Expected behavior

Firebase emulator starts without any error.

### [REQUIRED] Actual behavior
Firebase emulator starts, displaying false warning about an emulator instance already running, and then crashed showing the message: `An unexpected error has occured.`

[firebase-debug.log](https://github.com/firebase/firebase-tools/files/13615799/firebase-debug.log)

**Comment by aalej** [comment]
Hey @starleaf1, thanks for reaching out and sharing your debug logs. I’m trying to reproduce the issue you mentioned, but I encountered no errors when starting the emulators on an existing project. 

Looking through your logs, it seems like the reason why the emulators wasn’t able to start was due to this error:
```
[debug] [2023-12-08T15:10:32.589Z] TypeError: (0 , strip_ansi_1.default) is not a function
   at Socket.<anonymous> (/home/starleaf1/.nvm/versions/node/v18.17.0/lib/node_modules/firebase-tools/lib/frameworks/vite/index.js:93:67)
   at Socket.emit (node:events:514:28)
   at Socket.emit (node:domain:489:12)
   at addChunk (node:internal/streams/readable:324:12)
   at readableAddChunk (node:internal/streams/readable:297:9)
   at Readable.push (node:internal/streams/readable:234:10)
   at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[error]
[error] Error: An unexpected error has occurred.
```

Could provide detailed steps to reproduce the issue or an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) where the issue is reproducible so that we can replicate it on our end? 

I’m using the following to try and reproduce the issue:
- firebase-tools: v13.0.1
- Node: v20.10.0

**Comment by jamesdaniels** [comment]
It seems to me that this is likely for our fix in Windows environments https://github.com/firebase/firebase-tools/pull/6588 I'm unable to reproduce however, so something definitely seems off

**Comment by jamesdaniels** [comment]
Ok after a rm -rf node_modules and a fresh install I'm able to repro, a fix will be out in the next release. In the meantime 13.0.0 will work (unless you're on Windows).
