### ISSUE TITLE
Incompatibility Issue with Firebase CLI v13.0.0 and Node.js v16.19.0

### ISSUE THREAD

**Issue by ewenmic** [firebase/firebase-tools#6603]
**Firebase CLI v13.0.1 is incompatible with Node.js v16.19.0 Please upgrade Node.js to version >=18.0.0 || >=20.0.0**

**Platform:**
Ubuntu 18.04.6 LTS (with Ubuntu Pro / Expanded Security Maintenance (ESM) until 2028) / WSL

### [REQUIRED] Test case
https://github.com/firebase/firebase-tools/releases/tag/v13.0.0 dropped support for running the CLI on Node.js v16 

According to the firebase documentation, versions 14, 16, 18, 20 (preview) are still supported:
https://firebase.google.com/docs/functions/manage-functions?gen=1st
https://firebase.google.com/docs/functions/manage-functions?gen=2nd

How are we to deploy updates to existing apps if the CLI forces up to upgrade to the latest version? 

Can you please share why v16 was dropped in v13.0.0 of the CLI? 
### [REQUIRED] Steps to reproduce

When I type any commands after updating to the latest CLI version (which I was forced to do when trying to deploy functions), I get returned the following:
Firebase CLI v13.0.1 is incompatible with Node.js v16.19.0 Please upgrade Node.js to version >=18.0.0 || >=20.0.0

### [REQUIRED] Expected behavior
Being able to type _firebase deploy --only functions --debug_ and have it deploy my functions

### [REQUIRED] Actual behavior
I get returned the following:
Firebase CLI v13.0.1 is incompatible with Node.js v16.19.0 Please upgrade Node.js to version >=18.0.0 || >=20.0.0

**Comment by joehan** [comment]
Hey @ewenmic, v13.0.0 dropped support for running `firebase-tools` on Node 16 because Node 16 has been EOL for some time now (https://nodejs.org/en/blog/announcements/nodejs16-eol).  However, you can still deploy functions that target a different Node version than the one you have installed locally. To do this, specify the version that you want your functions to run on in either in your `package.json` or in the `functions` section of `firebase.json` (https://firebase.google.com/docs/functions/manage-functions?gen=1st#set_nodejs_version_2).

To be explicit - you can still deploy Node 14/16 functions - the version of Node running on your machine _does_ _not_ need to be the same as the version used by the Functions you are deploying.

**Comment by nickjuntilla** [comment]
@joehan Thanks, but how can you test locally then? Can we install an earlier version of firebase tools?
