### ISSUE TITLE
Images missing from next.js since updated to 13.0.1

### ISSUE THREAD

**Issue by ian-sayles** [firebase/firebase-tools#6607]
### [REQUIRED] Environment info

**firebase-tools:**13.0.1

**Platform:** 
macOS
next: 14.0.4

### [REQUIRED] Actual behavior
Images are not being shown in next.js web app since updated to 13.0.1,  also the cloud function that used to be created during deploy is no longer being created.

Strangely 'svg' images are still being shown correctly.

**Comment by leoortizz** [comment]
Hey @ian-sayles, I’m unable to reproduce the issue you mentioned. I tried deploying a Next.js app using Image Optimization and I was able to see the image without any issues.

> Strangely 'svg' images are still being shown correctly.

By default SVG images doesn't use Next.js image optimization: https://nextjs.org/docs/pages/api-reference/components/image#dangerouslyallowsvg

It would be helpful if you could provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) or details on the steps you took to set up your Next.js project, so that we can try to replicate it on our end.

**Comment by ian-sayles** [comment]
Thanks @leoortizz for responding, but I will close this ticket, planning on moving the hosting over to Vercel, for there was no issues when uploaded same project, and surprisingly the website shows data faster.
Also fixed other issues I have been having, #6141 and some other odd things happening randomly on pages.
