### ISSUE TITLE
Getting 500 Internal Server Error for SSR pages when deploying nextjs 14 app to firebase hosting and functions

### ISSUE THREAD

**Issue by marcellintacite** [firebase/firebase-tools#6620]
Here's my firebase.json file :
```
{
  "hosting": {
    "source": ".",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
    "frameworksBackend": {
      "region": "europe-west1"
    },
    "appAssociation": "AUTO"
  }
}
```

app/courses/page.tsx and app/courses/[id]/page.tsx are SSR pages and these pages are working normally when using the firebase emulator but when deploying on the cloud, i am gettting this :
![Capture d'écran 2023-12-15 141156](https://github.com/firebase/firebase-tools/assets/71480535/54e16808-78e4-4961-b30d-c6595f72b3d0)

### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment]
Hey @marcellintacite, thanks for reaching out. I’m unable to reproduce the issue you mentioned. I tried deploying a Next.js app, and I was able to access the routes without any issues.

Could you let us know which version of `firebase-tools` you’re using? I’m currently using v13.0.2. Also, it would be helpful if you could provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) or details on the steps you took to set up your Next.js project so that we can try to replicate it on our end.

**Comment by leoortizz** [comment]
@marcellintacite You can check the server logs in the Google Cloud console: https://console.cloud.google.com/logs/query

Can you share the error you see in the GCP logs when you see the error page?

**Comment by marcellintacite** [comment]
Thank you, I appreciate your efforts in investigating the issue. After diving into the problem, I found a resolution in [discussion #58244](https://github.com/vercel/next.js/issues/58244). The bug appears to be related to the nextjs build error.

**Comment by JwillSDP** [comment]
I am having the same issue. All my dynamic routes are giving 500 errors.
