### ISSUE TITLE
Angular 17 - Server throws ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by misomarcell** [firebase/firebase-tools#6632]
### [REQUIRED] Environment info

**firebase-tools:** ^13.0.2

**Platform:** Windows 11

### [REQUIRED] Test case

Boilerplace angular 17 application with SSR, latest firebase-tools with webframeworks, then deployed.

### [REQUIRED] Steps to reproduce

Run `firebase deploy` command, then try to navigate in your application. The response will either be `Internal Server Error` or `Service Unavailable`

### [REQUIRED] Expected behavior

SSR enabled angular application works with routing.

### [REQUIRED] Actual behavior

SSR not working, instead the website content is being rendered by the client. In case I set the hosting rewrite in `firebase.json` like this:
```
"hosting": {
  "source": ".",
  "rewrites": [
    {
      "source": "**",
      "function": "ssrfunctionname"
    }
  ],
  "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
  "frameworksBackend": {
    "region": "europe-west1",
    "maxInstances": 1
  }
}
```

I'll get the following error in the function's logs:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/workspace/dist/server/server.mjs' imported from /workspace/bootstrap.js
```
![image](https://github.com/firebase/firebase-tools/assets/22910115/71a155d2-54e0-470d-9148-aaca527fbab4)

**Comment by misomarcell** [comment]
Trying to involve @angular/fire for the deploy, no luck there either. First it says `firebase-tools version 13.0.0+ is required, please upgrade and run again` but then I upgrade and then complains about peer dependencies:
```
npm ERR! Could not resolve dependency:
npm ERR! peerOptional firebase-tools@"^12.0.0" from @angular/fire@17.0.0
npm ERR! node_modules/@angular/fire
npm ERR!   @angular/fire@"^17.0.0" from the root project
```

Not sure if using `ng deploy` instead `firebase deploy` would make any difference, but seems like I won't find out.

**Comment by 9kubczas4** [comment]
Hi @misomarcell,

You found a really interesting issue. I’ve done the investigation and it looks like only the main route - ‘/‘ is not prerendered on Firebase. I've prepared a simple repository: https://github.com/9kubczas4/ng-firebase-deploy-test, it’s Angular v17 with defined routing and SSG/SSR.  App routes:
- / - main route
- /route-a
- /route-b

The problem is that for some reason on the Firebase `/` - main route is not prerendered, but SSG/SSR works for other routes. I will investigate more how to fix this issue. On the local `ng serve` all routes are prerendered.

But also I found a workaround, in angular.json you can update the “prerender” option to take into account `/` - main route during prerender like in this code change: https://github.com/9kubczas4/ng-firebase-deploy-test/pull/1/files. In the result after deployment to Firebase, all routes are prerendered.

I’ll continue the investigation of why the main route is not prerendered on Firebase.

**Comment by 9kubczas4** [comment]
I can't reproduce this issue using:
- Angular App with SSR (17.3.1)
- Firebase Tools (13.6.0)

@misomarcell Please let me if you still facing the issue. If yes, please provide sample repository.
