### ISSUE TITLE
Failed because of function quotas

### ISSUE THREAD

**Issue by bkingsleyc** [firebase/firebase-tools#6703]
### [REQUIRED] Environment info

**firebase-tools:**9.8.1

**Platform:**Windows

### [REQUIRED] Test case

![image](https://github.com/firebase/firebase-tools/assets/15825238/843afe58-fc4b-40ca-8dc7-839d9138fc52)

### [REQUIRED] Steps to reproduce

Create New Astro Project
Install Node
Firebase SSR Deployment Steps
During deploy function fails to deploy

### [REQUIRED] Expected behavior

Deployment

### [REQUIRED] Actual behavior

Failure

**Comment by bkingsleyc** [comment]
@leoortizz I just tried again now and I got the same results with a fresh build.

**Comment by aalej** [comment]
Hey @bkingsleyc, thanks for reaching out. A few thing I’d like to recommend here:

First, upgrading to the latest version of `firebase-tools`, which is currently v13.0.3. v9.8.1 is an old version and there have been many fixes released since then.

Second, in your `firebase.json` file, could you try lowering the `maxInstance` since it looks like you’re hitting a quota limit. The configuration would look something like:
```json
{
 ...
 "hosting": {
   "source": ".",
   "ignore": [
     "firebase.json",
     "**/.*",
     "**/node_modules/**"
   ],
   "frameworksBackend": {
     "region": "us-central1",
     "maxInstances": 10
   }
 }
 ...
}
```

Are there still any issues being raised after upgrading to the latest version and changing the config in `firebase.json`?

**Comment by bkingsleyc** [comment]
Works like a charm now! Thanks for working on this and helping me :)
