### ISSUE TITLE
Using CamelCaseKeys NodeJS dependency breaks container startup (The default Firebase app already exists)

### ISSUE THREAD

**Issue by Spitzbua** [firebase/firebase-tools#6720]
When adding the NodeJS dependency "openai": "^4.26.0" the startup with nodejs 18 fails with the error message "FirebaseAppError: The default Firebase app already exists.". 

When removing the dependency the startup is working again. Can I workaround this issue? It seems is has to do with the fetch function which collides with new one in Nodejs18.

Here is a smiliar issue mentioned:

https://github.com/firebase/firebase-tools/issues/4546

### [REQUIRED] Environment info

**firebase-tools:** 13.1.0

**Platform:** Windows

Dependencies

>   "dependencies": {
    "camelcase-keys": "^9.1.3",
    "firebase-admin": "^11.11.1",
    "firebase-functions": "^4.5.0",
    "openai": "^4.26.0"
  },

### [REQUIRED] Test case

Start Emulator or deploy functions

### [REQUIRED] Steps to reproduce

> import { initializeApp} from "firebase-admin/app";
import { setGlobalOptions } from "firebase-functions/v2";
initializeApp();

Same behaviour described on stackoverflow.
https://stackoverflow.com/questions/73580052/why-does-using-the-camelcase-keys-package-cause-a-firebase-initializeapp-e

The startup is working when initializing the following way:
if (!admin.apps.length) {
  admin.initializeApp();
}

### [REQUIRED] Expected behavior

The container startup is successfull. 

### [REQUIRED] Actual behavior

`FirebaseAppError: The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.
    at AppStore.initializeApp (D:\Development\Repos\ki-businessplan\functions\node_modules\firebase-admin\lib\app\lifecycle.js:41:23)
    at initializeApp (D:\Development\Repos\ki-businessplan\functions\node_modules\firebase-admin\lib\app\lifecycle.js:102:36)
    at Object.<anonymous> (D:\Development\Repos\ki-businessplan\functions\lib\index.js:10:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  errorInfo: {
    code: 'app/duplicate-app',
    message: 'The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.'
  },
  codePrefix: 'app'
}

!!  functions: Failed to load function definition from source: FirebaseError: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error`

**Comment by aalej** [comment]
Hey @Spitzbua, thanks for the detailed report and for providing a relevant Stack Overflow post. I’m currently trying to reproduce the error you mentioned, but so far I am unable to replicate this even after adding the `camelcase-keys` dependency(also tried adding `openai`).

Using the provided information I tried to create this [repo](https://github.com/aalej/issues-6720) to try and replicate the issue. Let me know in case I’m missing anything. By any chance, if you could provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), please share it as well so that we can reproduce the issue on our end.

**Comment by Spitzbua** [comment]
@aalej , thank you for the quick response! The only difference I can spot is that we use typescript. I can reproduce the issue consistently. 

> {
  "name": "functions",
  "scripts": {
    "lint": "eslint --ext .js,.ts .",
    "build": "npm run buildTypes && tsc",
    "buildTypes": "tsc --declaration src/types/common/main.ts",
    "build:watch": "tsc --watch",
    "serve": "npm run build && firebase emulators:start",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "18"
  },
  "main": "lib/index.js",
  "dependencies": {
    "camelcase-keys": "^9.1.3",
    "firebase-admin": "^11.11.1",
    "firebase-functions": "^4.6.0",
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.12.0",
    "@typescript-eslint/parser": "^5.12.0",
    "eslint": "^8.9.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.25.4",
    "firebase-functions-test": "^3.1.0",
    "typescript": "^4.9.0"
  },
  "private": true
}

**Comment by aalej** [comment]
Hey @Spitzbua, thanks for that clarification. I updated to using TypeScript and I was still unable to reproduce this. I think the issue might not be directly caused by `firebase-tools`. It’s most likely that there is an issue with the code(in this case `initializeApp()` gets called multiple times) that is preventing the Firebase CLI from analyzing it.

Unfortunately, I don’t think there is much we can do here to provide additional assistance. I’d recommend filing an issue to either [firebase-admin-node](https://github.com/firebase/firebase-admin-node/issues) or [camelcase-keys](https://github.com/sindresorhus/camelcase-keys/issues) as they might have a better overview on why this is occurring.
