### ISSUE TITLE
Running any firebase command opens firebase.js in Windows 11

### ISSUE THREAD

**Issue by amin5631** [firebase/firebase-tools#6782]
### [REQUIRED] Environment info
Firebase version: 13.3.0
Windows version: 11
Node version: v18.18.0
npm version: 9.8.1 

**firebase-tools:**

**Platform:**
Windows 11

### [REQUIRED] Test case
Running any firebase command opens firebase.js inside ...\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin

### [REQUIRED] Steps to reproduce
1. Install firebase in Powershell using `npm install -g firebase-tools`
2. Run a any firebase command for example: `firebase --version`  

### [REQUIRED] Expected behavior
Should display the firebase version installed.

### [REQUIRED] Actual behavior
Open firebase.js inside ...\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin

**Comment by aalej** [comment]
Hey @amin5631, thanks for reaching out. I’m currently unable to reproduce this issue. Just to note, I’m using a Windows 10 machine. 

To get a better understanding of what might be causing this, I’d like to ask a few questions:

1. Are you able to run `firebase` commands in cmd? 
1. Are there any error messages being raised when running the `firebase` commands on either PowerShell or cmd?
1. Could you elaborate what you mean by “Open firebase.js inside ...\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin”. The Firebase CLI shouldn’t open files, and should only execute the script in “firebase.js”.

As an alternative, you can download the [standalone binary](https://firebase.google.com/docs/cli#install-cli-windows) version of Firebase Tools.

**Comment by ortegoncarlos** [comment]
We had the same issue of opening a ourproject/functions/firebase.js.
When adding firebase on the package.json under any script, opens the js file instead of running firebase, this behavior happened doing npm run xxxxx, and that command having firebase at the beginning.

we are using power shell v5.1 on Windows 11,
the firebase command directly on the CLI successfully runs

**SOLUTION:**
rename your firebase.js to any other name.

**Comment by russildi** [comment]
this is still an issue.. if you're in a directory that has a file named firebase.js and you go in the console to that directory with cd.. then when you try to run firebase commands the file firebase.js which is in the same directory is opened! 

this happens to me with software CMDER

**Comment by wjingen** [comment]
Hi, was experiencing the same problem.

Actually quite a simple fix. The reason is that Windows is scanning through the paths as defined in your environmental variables. There's possibly a path that leads to your `firebase.js` file, and hence Windows is opening that file.

First open up your `firebase.js` and look at the filepath, then see which PATH environmental variable is causing Windows to open the file. Delete it and reopen your CMD. Then everything should work as normal.

How to edit PATH environmental variables: https://www.eukhost.com/kb/how-to-add-to-the-path-on-windows-10-and-windows-11/
