### ISSUE TITLE
Old firebase package in firebase-tools

### ISSUE THREAD

**Issue by janswist** [firebase/firebase-tools#681]
I just found that `firebase-tools`'s `firebase` package is version 2.4.2 - why is that if there is already version 3.x available? How can I update it? It's really odd that it's not taken care of (I stumbled upon it while having problems with Cloud Functions).

**Comment by laurenzlong** [comment]
This is actually to make the `firebase database` commands work. Code changes need to be made to update "firebase" to the latest version since we are using APIs that do not exist any more in the latest "firebase" version. We just haven't had time to do it, but you're welcome to if you feel up for it.
