### ISSUE TITLE
deploiement de mon dashboard

### ISSUE THREAD

**Issue by rg4amia** [firebase/firebase-tools#6934]
Please submit feature requests through our [support page](https://firebase.google.com/support/troubleshooter/report/features/).

**Comment by aalej** [comment]
Hey @rg4amia, there isn’t any information provided in this report, so I’ll go ahead and close this. If there’s a certain feature you would like to see implemented, or if you’re encountering an issue, please file a new report and specify the details so that we can have a better understanding. Thanks!
