### ISSUE TITLE
Firebase Storage Emulator - Terminates all emulators

### ISSUE THREAD

**Issue by modernlabrat** [firebase/firebase-tools#6972]
[REQUIRED] Developer Environment

platform - macOS 14.2.1
firebase tools - 13.7.1
firebase emulators - 13.7.1
node - v.21.0.0

[REQUIRED] Steps to reproduce

Testing while connected to the emulator

1. Have a frontend running locally
2. Get user input and collect photo
3. Use JavaScript (modular) sdk to upload the photo and get the download url

I have this in a try/catch

``const storageRef = ref(storage, `${user.uid}/photos/${sanitizedFileName}`);``

`await uploadBytes(storageRef, photo);`
`response.photoURL = await getDownloadURL(storageRef);`

[REQUIRED] Expected behavior

The photo should be uploaded and a downloadURL should be received

[REQUIRED] Actual behavior

The entire emulator breaks and all of my emulators are terminated.

**Comment by aalej** [comment]
Hey @modernlabrat, thanks for reaching out and providing code snippets. I’m trying to reproduce the error you mentioned, but so far I haven’t encountered any issues with uploading files to the Firebase Storage emulator.

From what I can gather, your project setup would look like [this](https://github.com/aalej/issues-6972). Let me know if I made a mistake in the setup. Also, any chance you could share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) example with us? This will help us to accurately reproduce the issue.

Lastly, could you provide the ff:

1. Contents of `firebase-debug.log` file. This should provide some information about what caused the emulators to terminate.
2. Error logs, if any, on the client side when trying to upload the file. 
3. Size of the file you’re trying to upload.

**Comment by dereekb** [comment]
I'm not sure if I've got the same issue, but I did just notice my firebase storage tests seem to be failing now with connection refused errors, which could be due to the firebase storage emulator crashing. This was just occured with firebase tools `13.6.0` and `13.7.1`. It was passing with `13.6.0` a few days ago though.

I cannot reproduce this locally at the moment though. My system seems to pass these tests fine.

```
FetchError: request to http://localhost:9906/upload/storage/v1/b/firebase-storage-server-test-1712721271833-23/o?uploadType=multipart&name=%2Ftest%2Ftwo%2Fexists.txt failed, reason: connect ECONNREFUSED ::1:9906
    at ClientRequest.<anonymous> (/home/circleci/code/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:529:35)
    at Socket.socketErrorListener (node:_http_client:501:9)
    at Socket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

https://app.circleci.com/pipelines/github/dereekb/dbx-components/4072/workflows/33fe6583-1634-4fac-9329-7583ca372c74/jobs/12672/tests

I'm currently running some of the more recent commits CI's again to see where the behavior started.
