### ISSUE TITLE
Emulator Functions do not watch source code path that has node_module in its path

### ISSUE THREAD

**Issue by marvin-kolja** [firebase/firebase-tools#7109]
### [REQUIRED] Environment info

**firebase-tools: 13.8.0**

**Platform: macOS**

### [REQUIRED] Test case

If we have a monorepo that uses pnpm workspaces and have our `api` code in some directory and all firebase tools and config in another:
- API
   - dir: `apps/api`
   - package name: `@app/api`
- Tools
   - dir: `tools/firebase`
   - package name: `@tools/firebase`

If we want to deploy the build api we cannot have the source set to `../../apps/api` as this would throw an error (`Error: ../../apps/api is outside of project directory`). However, with PNPM workspaces we can add the api package as a dependency to the firebase tools package; Thus, we can use the following config:

firebase.json
```json
{
  "functions": [
    {
      "source": "node_modules/@app/api"
    }
  ],
}
```

This does work for deploys but not for the emulator as it does not watch any paths that have `node_modules` in them (https://github.com/firebase/firebase-tools/blob/master/src/emulator/functionsEmulator.ts#L457-L465)

### [REQUIRED] Steps to reproduce

1. Create a PNPM workspace with two different packages.
   1. One has functions code
   1. The other contains firebase config (`firebase.json` as described above)
1. cd into the firebase config package and execute `firebase emulators:start --project demo-your-project-id --only functions`
1. in another session cd into the api and execute the `tsc --watch`

### [REQUIRED] Expected behavior

I would say there are two behaviours that could make sense:

1. Resolve function source path symlinks before watching it in the emulator
2. Listen to function source regardless if `node_modules` is in its original path, while still ignoring `node_modules` inside the source code.

### [REQUIRED] Actual behavior

There is nothing that happens as `chokidar` stops listening when the path contains something that is ignored by the provided ignored conditions.

**Comment by aalej** [comment]
Hey @marvin-kolja, thanks for filing a detailed report and sharing your observations. I agree with your use case here, when changes are made within the `node_modules` folder, it seems reasonable to also update the running functions.  

I think this could be similar to #2131, which is a feature request to only ignore files specified in `functions.ignore`. That being said, I think this issue could be marked as a duplicate. Let me know in case I misunderstood anything here and if the feature you’re looking for is different so that we can reopen the issue. Thanks!

**Comment by marvin-kolja** [comment]
Thanks @aalej. I agree, if the mentioned feature would become reality it would resolve this.
