### ISSUE TITLE
Migrate from rails, bcrypt to firebase auth:import -- error:  "Base64 decoding failed for" password

### ISSUE THREAD

**Issue by joemsak** [firebase/firebase-tools#714]
I'm trying to do an import from my rails users to firebase and hitting a snag and I cannot find anything on SO or Google searches or Issues searches to help me. I chatted with someone on codementor and they weren't sure either. Can someone help me understand what I'm doing wrong? All relevant code is linked below in steps to reproduce

### Version info
firebase --version
3.17.7

### Platform Information

OS X High Sierra 10.13.4

### Steps to reproduce

See my gist here 
https://gist.github.com/joemsak/f3632a72e9c0f76c468c3b7ffb26a2fc

1. Export a rails model to json with the specified format for auth:import
2. Run the import command:
firebase auth:import [PATH-TO-JSON-FILE] --hash-algo=BCRYPT --project <PROJECT-ID>

### Expected behavior

Users should import

### Actual behavior

No users import, error happens:

> Processing db/export/accounts.json (486 bytes)
> Starting importing 1 account(s).
> 
> Error: HTTP Error: 400, Invalid value at 'users[0].password' (TYPE_BYTES), Base64 decoding failed for "[BASE-64-ENCODED-PASSWORD-DIGEST]
> "

**Comment by joemsak** [comment]
# Update

I thought maybe the newlines in the encoded string might be an issue, so I added

`.gsub("\n", "")` to the end of the encoding of the password_digest

Well, it got farther but now I have this cryptic error:

> Starting importing 1 account(s).
> Encountered problems while importing accounts. Details:
>  account={
>   "localId": "9da9f7c3-325a-4242-9fbd-98b28a8bf588",
>   "email": "joe+s@joesak.com",
>   "emailVerified": true,
>   "passwordHash": "JDJhJDEwJE0zUkhTYW1HdW5GTVgublJONUdIbE9UV25pRVVjbDdYVWxPTUhTTU5QZFVBSlBEUExmRG1T",
>   "displayName": "TECHNOVATION STAFF TEST ACCOUNT",
>   "photoUrl": "https://my.technovationchallenge.org/assets/placeholders/avatars/23-885db7ab50d1d4041abbcef20c84e7800f5ddba80ba5764c31a34e806caf3195.svg",
>   "createdAt": 1476921600000,
>   "phoneNumber": "",
>   "providerUserInfo": [],
>   "lastLoginAt": 1521763200000
> }, reason=undefined

**Comment by joemsak** [comment]
## Next update:

firebase-debug.log

https://gist.github.com/joemsak/5c3168c6148156163b0eb7beb1e9661e

**Comment by joemsak** [comment]
## Final update

The problem seems to have been with the empty array provider_info field in my JSON

I was confused by the CSV format documentation which said to leave an empty value for any optional fields not being filled in

Also, one should be sure to use `Base64.strict_encode` on the password_digest, which avoids the need for the `gsub` of newlines

**Comment by malav1410** [comment]
@joemsak Hey I am trying to import my existing users to firebase database. Devise by default uses BCrypt. I followed your rake task to generate my users.json file and created object is something like this,
`{ "localId":"094c90ad-61dc-4d90-bf79-08f2aaaf1589","email":"malav@curativ.com","emailVerified":true,"passwordHash":"$2a$11$FAyMLYe4262N7ljN8c1iyOfajMQbRLMMYocHzKgk2knsifCMZOW82","displayName":"Curativ","photoUrl":"","createdAt":1507075200000,"lastSignedInAt":1507075200000,"phoneNumber":"","providerUserInfo":[] }`

where passwordHash is encrypted_password field from my Users table which is generated by Devise gem only. What should be the value for passwordHash because i am getting 
`Invalid value at 'users[0].password' (TYPE_BYTES), Base64 decoding failed for "$2a$11$FAyMLYe4262N7ljN8c1iyOfajMQbRLMMYocHzKgk2knsifCMZOW82"` 

Need your help if you have successfully imported your Users..

Thanks

**Comment by joemsak** [comment]
@malav1410 check my final update, don't send an empty array for `providerUserInfo` - just remove the key from your JSON and make sure you're using `Base64.strict_encode`
