### ISSUE TITLE
"Property 'flutter' is not allowed" warning

### ISSUE THREAD

**Issue by Pochii07** [firebase/firebase-tools#7253]
I followed the video of firebase set up by the google firebase which used git bash.

and now i have this error where it says "Property 'flutter' is not allowed" on the firebase.json file.
when i try to remove the error, it just makes the next property and error until i remove the entire thing which makes the firebase.json blank.

![image](https://github.com/firebase/firebase-tools/assets/166979573/dac350e1-1c21-4e2b-8864-b08f35054b97)

**Comment by aalej** [comment]
Hey @Pochii07, sorry to hear you encountered this issue. Currently, there is not enough information for us to start our initial investigation. 

For us to have a better understanding of what caused this, could you please file a new report and provide the details using the specified template? Also, please include a link to the video you mentioned so that we can check it out. That said, I’ll go ahead and close this.

**Comment by Heidelbergg** [comment]
I have the same error when configuring firebase.json in my project.
