### ISSUE TITLE
Retry failed function deployment on ETIMEDOUT

### ISSUE THREAD

**Issue by soumak77** [firebase/firebase-tools#728]
Every time I deploy functions, at least one function fails to deploy due to ETIMEDOUT.  My project has around 50 functions and I'm deploying from a slow internet connection.  I would like to request that the failed functions get redeployed when this error is encountered.  I do see that some errors are retried, but I'm not sure whether this applies to ETIMEDOUT

https://github.com/firebase/firebase-tools/blob/8f81d88caee57a16b44df868243572c071ec86d6/lib/deploy/functions/release.js#L167-L172

Another possible way to fix this might be to provide an argument to allow deploying functions in batches and waiting for each batch to complete before deploying the next batch of functions.  The reason I think this might work is because my functions always deploy successfully when I run a partial deployment of 5-10 functions.

**Comment by laurenzlong** [comment]
We do offer the ability to group your functions and deploy individual functions or groups instead of the whole project: https://firebase.google.com/docs/cli/#partial_deploys. At this time we are not going to support batching your functions, since you have the ability to do that yourself. 

I believe ETIMEDOUT would be error code 4, so that is retryed.

**Comment by soumak77** [comment]
@laurenzlong is there a way to increase the amount of times the CLI tries to redeploy a function?

**Comment by laurenzlong** [comment]
Technically it is possible, but it may not be a good idea since a lot of the deployment quotas are time range based (i.e. x number of deploys within x seconds). So we would not want to make that change in the CLI. 

If you have a business case for deploying a lot of functions at at time, you can request for a quota increase on the [Cloud Console](https://console.cloud.google.com/iam-admin/quotas?service=cloudfunctions.googleapis.com&usage=ALL&project=_&_ga=2.24117374.-514662388.1521657420), the quota you would want to increase is "Write requests per 100 seconds per user".

**Comment by rhodgkins** [comment]
@laurenzlong we get this quite a lot when deploying (its quite annoying!) - I've looked at increasing the quota you've mentioned but its not editable, any other ideas / work arounds?
