### ISSUE TITLE
Disable email sending for Firebase Distribution

### ISSUE THREAD

**Issue by MaYatKit** [firebase/firebase-tools#7305]
Please submit feature requests through our [support page](https://firebase.google.com/support/troubleshooter/report/features/).

**Comment by aalej** [comment]
Hey @MaYatKit, based on the title of the report, it looks like you want to disable the sending of email notifications whenever a new build is distributed using Firebase App Distribution. 

From what I can tell, this request seems to be related to project configuration. Could you submit a report to our [Firebase Support team](https://firebase.google.com/support/troubleshooter/contact)? They’ll be able to assist you further for issues related to project configurations. 

If I may have misunderstood this request, please file a new issue and provide additional details such as a use-case so that we can have a better overview of the request. Thanks!
