### ISSUE TITLE
firebase emulators start 

### ISSUE THREAD

**Issue by anuraag805** [firebase/firebase-tools#7329]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

### [REQUIRED] Actual behavior

while running emulators start my function API key is not generated and error is shown

**Comment by aalej** [comment]
Hey @anuraag805. I understand you’re having an issue with the Cloud Functions emulator, but for us to proceed with our investigation, we would need other information.

Could you please file a new issue and specify the details using the issue template? Please include code snippets, the version of firebase-tools you’re using, and debug logs so that we can get a better understanding of the error. Thanks!
