### ISSUE TITLE
URL rewrites not working on static assets with firebase deploy on firebase-tools@^13.9.0

### ISSUE THREAD

**Issue by wongchichong** [firebase/firebase-tools#7363]
**firebase-tools:**

Windows

firebase deploy --only hosting

with firebase-tools > v13.9.0

```json
      {
        "source": "**",
        "destination": "/index.html"
      }
```

not working on static assets.
all graphics not loading.

downgrading to firebase-tools@13.9.0

static assets works again.

**Comment by Fric56** [comment]
Same here.
firebase-tools@13.11.2) was the last version that worked for me.

**Comment by ClashOfStyles** [comment]
Same! 
Thanks, switching to 13.9.0 saves me a lot of time!

**Comment by pogorv12** [comment]
Same with me.

I spotted that the number of deployed files decreased after update. So for me it looks like files located in subfolders of public dir are not deployed.

**Comment by aalej** [comment]
Hey folks, sorry to hear you’re encountering this issue and thanks for reporting this. At the moment, I can’t seem to reproduce the issue on macOS machines. However, I was able to reproduce this on a Windows machine. 

I’ll raise this to our engineering so that we can investigate the cause of the issue. For those encountering this, could you let me know if you’re also using a Windows machine? 

As a workaround, please use v13.11.2. I was able to deploy to Firebase Hosting without any issues using this version.

**Comment by pureimpro** [comment]
Same issue for me, on Windows, workaround by  downgrading to 13.11.2, after numerous hours of headache

**Comment by Robula** [comment]
@aalej You closed/commented on my issue: https://github.com/firebase/firebase-tools/issues/7381, however this issue (7363) is completely unrelated...

**Comment by Robula** [comment]
Likely related https://github.com/firebase/firebase-tools/issues/7378

**Comment by Wrakie** [comment]
I spent the whole day trying to figure out what I did wrong 😭😭😭

**Comment by seborys40** [comment]
wtf?
