### ISSUE TITLE
firebase_storage eternal await in useStorageEmulator Flutter

### ISSUE THREAD

**Issue by geovaniprodata** [firebase/firebase-tools#7404]
### [REQUIRED] Environment info

**firebase-tools:**
13.12.0

**Platform:**
Windows

### [REQUIRED] Test case

```
void main() async {
  var app = await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await FirebaseAuth.instance.useAuthEmulator('localhost', 9099);
  await FirebaseStorage.instance.useStorageEmulator('localhost', 9199);
  FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
}

```

### Plugins/Packages needed and their currently version in my project

- firebase_core@3.1.1
- firebase_storage@12.1.0
- firebase_auth@5.1.1
- cloud_firestore@5.0.2

### [REQUIRED] Steps to reproduce

1. Get plugins, set your firebase config in your project, download the emulators.
2. Start the emulators by `firebase emulators:start`
3. Write the code above
4. Run in Windows
5. Wait for async complete

### [REQUIRED] Expected behavior

All Emulators complete the async.

### [REQUIRED] Actual behavior

Except Storage Emulator, the others complete just fine.

Storage Emulator get stuck, can't debug either.

### Observations

1. **My firebase.json is already setted right.**
2. **Already tried use storage emulator without async, he uses the production instead, so not working**
3. **Already tried change port, change host, update firebase-tools, searched in stackoverflow, git and reddit, none specified my problem**

**Comment by aalej** [comment]
Hey @geovaniprodata, thanks for reaching out. Looking through the report it seems like this might be more related to the `firebase_storage` package. I tried running the application on a different device, like Chrome, and I was able to connect to the Storage emulator. So I’m guessing the issue might be with how `useStorageEmulator` configures the SDK.

Could you try filing an issue to the [Flutter GitHub repository](https://github.com/firebase/flutterfire/issues), as they might be able to look into this. However, if you think that the issue is caused by firebase-tools, feel free to ask this to be re-opened.
