### ISSUE TITLE
Cant deploy important update because of this ERROR!! -- Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.

### ISSUE THREAD

**Issue by rendomnet** [firebase/firebase-tools#7428]
Hi! We cant deploy important update because of this ERROR!! 
`Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.`

It is draining our money every second and we cant even contact support!! becuase your support system is a mess without any person!! Slack is dead!!

We cant get any support from firebase because IT REQURES Google organization account. Which you CAN'T create with GMAIL account! and you support cant even migrate projects from gmail account to google organization account!

**Comment by aalej** [comment]
Hey @rendomnet, sorry to hear you’re encountering this issue. I understand that this situation is frustrating since you’re unable to deploy updates to your functions. At the moment, I can’t reproduce this, could you try re-deploying to see if the issue would still persist. 

I’m not sure about requiring a Google organization account, but since this seems to be a backend issue I would recommend reaching out to our dedicated [Firebase Support](https://firebase.google.com/support) channel to get assistance. This should not require a Google organization account.
