### ISSUE TITLE
Firestore function emulation does not behave the same as actual deployed function

### ISSUE THREAD

**Issue by adamduren** [firebase/firebase-tools#743]
### Version info

3.18.2

### Platform Information

OS X 10.13.4

### Steps to reproduce

1. Write a firestore `onCreate` function that `update`s or `set`s (with `{ merge: true }`) new data on the created document.
1. Start the emulator.
1. Trigger the function
1. Observe the original document is overwritten vs updated

### Expected behavior

That the document is merged.

### Actual behavior

The document is overwritten with data that should have been merged.

**Comment by adamduren** [comment]
In the case of using `update` you get the error `5 NOT_FOUND: No document to update: projects/(project)/databases/(default)/documents/collection_name/path`.

**Comment by laurenzlong** [comment]
Hey @adamduren thanks for filing. This is actually expected behavior. When you run the emulator, the data that you pass to the emulator doesn't actually exist in your Firestore database yet. That's why an update to that non-existent document will fail, and `merge: true` will only write in the new data. To make your tests work, you have to actually create the document in your database via either the Firebase Console or the firebase-admin SDK. Then you can run the emulator with a fake data at that exact path that you just created the real document in, and merging and updating will work as expected.

**Comment by SamikshyaAd** [comment]
No document to update: projects/socialapp-a3af2/databases/(default)/documents/users/HMfNS0J4EPejIDtzwJBTZXPDI1x1

I am having problem with updating docs. I created the documents using firebase admin sdk. The problem still persist. Any help will be appreciated

**Comment by bkendall** [comment]
@SamikshyaAd please open a new issue (if you haven't already), rather than commenting on an old bug - makes it easier to track. Thanks!
