### ISSUE TITLE
[HOSTING] Deployment using firebase-tools 13.14.2 still broken on macos

### ISSUE THREAD

**Issue by tspoke** [firebase/firebase-tools#7500]
### [REQUIRED] Environment info

**nodejs v20.9.0**
**firebase-tools: 13.14.2**
**Platform: Macbook pro M1, 14" - Sonoma 14.2.1**

### [REQUIRED] Test case

- With a valid firebase.json rewrites object
- Deploying using firebase-tools **13.14.2** success but there is a **blank page 404** (index.html not found) on firebase hosting.
- Deploying using firebase tools **13.11.2** success and the website is online !

### [REQUIRED] Steps to reproduce

Deploy using CLI.

### [REQUIRED] Expected behavior

I expect my website to be online.

### [REQUIRED] Actual behavior

I got an empty 404 page.

Linked to #7387 #7363

**Comment by aalej** [comment]
Hey @tspoke, sorry to hear you encountered this issue, and thanks for reporting this. Just to note, from what I can recall, issues #7387 and #7363 happened on Windows machines because of how file paths are being separated(instead of using `/`, it uses `\\`). 

At the moment, I’m unable to reproduce the issue you described. I created this [minimal repo](https://github.com/aalej/issues-7500) that has rewrites to try and reproduce the issue, let me know in case I’m missing anything or if I may have made a mistake. By any chance, could you share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? This will help us investigate what could’ve caused the issue.

Also, just to verify, are you getting the 404 response when visiting the root of your website, or does it occur when opening certain paths like “https://SITE_ID.web.app/path/sub-path/”?

**Comment by tspoke** [comment]
Hi @aalej ,

Thanks for taking this issue. 
Yes, it's when I visit the root of my website. I can share a minimal repo tomorrow I think, depending on my time but I will do it asap :)

- I don't have a 404.html file
- Here my command to deploy : 

```
    "build-only": "vite build",
    "deploy-prod": "npm run build-only && firebase deploy -P production",
```

- Below my firebase.json as-is :

```json
{
  "hosting": {
    "public": "./dist",
    "target": "the-admin",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**",
      "*.sh",
      "./*"
    ],
    "headers": [
      {
        "source": "**",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "public, max-age=86000, s-maxage=86000"
          }
        ]
      }
    ],
    "rewrites": [
      { "source": "/image/**", "function": "api" },
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}

```

- And my structure after build :

<img width="377" alt="Capture d’écran 2024-07-29 à 21 08 40" src="https://github.com/user-attachments/assets/2f8e36ce-3e62-4248-a883-923bc1a6facb">

Thanks

**Comment by tspoke** [comment]
@aalej Hereafter the repository with my vue setup (simplified) : https://github.com/tspoke/firebase-tools-issues-7500/tree/vue-sample

I just tried the two versions of firebase-tools with another firebase project and I can confirm the bug :
- Using `npm i -g firebase-tools@13.11.2` : website is well deployed and working
- Using `npm i -g firebase-tools@13.14.2` : website is well deployed BUT is not working (index.html not found) !

**Comment by aalej** [comment]
Thanks for all the additional information @tspoke, I appreciate the effort you went through to gather this! I was able to reproduce the issue you mentioned. From what I can tell, the issue occurs when the `hosting.ignore` property has a `"./*"`. I think this is causing the files in root to be ignored, which causes your site to return a 404 response.

If you remove `"./*"` from `hosting.ignore`, are you able to see your deployed site? The modified `firebase.json` would look something like:
```json
{
 "hosting": {
   "public": "./dist",
   "ignore": [
     "firebase.json",
     "**/.*",
     "**/node_modules/**",
     "*.sh"
   ],
   "headers": [
     {
       "source": "**",
       "headers": [
         {
           "key": "Cache-Control",
           "value": "public, max-age=86000, s-maxage=86000"
         }
       ]
     }
   ],
   "rewrites": [
     { "source": "/image/**", "function": "api" },
     {
       "source": "**",
       "destination": "/index.html"
     }
   ]
 }
}
```

However, given that the behavior did change after v13.11.2, let me discuss this with our engineering team to get more context about this.

**Comment by akongara-goog** [comment]
I'm unable to reproduce this with a firebase.json like below

```
{
  "functions": [
    {
      "source": "functions",
      "codebase": "default",
      "ignore": [
        "node_modules",
        ".git",
        "firebase-debug.log",
        "firebase-debug.*.log"
      ]
    }
  ],
  "hosting": {
    "public": "public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "/helloworld",
        "function": {
          "functionId": "helloWorld"
         }
      },
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```
```
firebase-tools@13.14.2 | MIT | deps: 66 | versions: 404
```

**Comment by tspoke** [comment]
@akongara-goog, I tried with another workspace/firebase project too, and the bug is still present. Your `firebase.json` does not contain the buggy `./*` in the ignore array, this is why you are not reproducing this issue. If you add it you won't be able to deploy with success. 

@aalej I removed `./*` like you suggested and I deployed with success using 13.14.2. 

I have no problem removing this entry but IMO it's a breaking change which is undocumented.

**Comment by akongara-goog** [comment]
Ok, I had misunderstood that critical piece of info. I can indeed reproduce this.

I'm looking into this bug. Thanks for reporting.

**Comment by blidd-google** [comment]
Hi @tspoke, from my understanding, v13.14.2 is now working as intended - it seems that between v13.11.2 -> v13.14.2, we patched the bug that wasn't correctly respecting the `./*` pattern for ignoring files. So I would classify this behavior change as a bug fix rather than a breaking change.

Can you explain your use case so that we can better understand what behavior you are trying to achieve? It seems to me that  adding `./*` to the `ignore` array will cause all files to be ignored by the CLI, leading to nothing being uploaded and deployed to Firebase Hosting.

**Comment by tspoke** [comment]
The ./* Was historical in our codebase. There is no specific usage I can remember, it probably came from an initial template repository we used in the past.

I agree, this is more a bugfix as the pattern works as intended now !
