### ISSUE TITLE
IOS simulator take very long to load after using firebase packages

### ISSUE THREAD

**Issue by danielkuaUBC** [firebase/firebase-tools#7512]
### [REQUIRED] Environment info

**firebase-tools:**

**Platform:**

**Comment by aalej** [comment]
Hey @danielkuaUBC, based on the title of the report, I’m guessing you’re having an issue with the Firebase Apple SDK.  I would recommend filing an issue to the [firebase-ios-sdk](https://github.com/firebase/firebase-ios-sdk/issues) repository.

However, if that is not the case, please file a new report and specify the details using the provided template so that we can have a better understanding of the issue. Thanks!
