### ISSUE TITLE
Using Firebase Emulator offline results in error when making firestore requests

### ISSUE THREAD

**Issue by johnnyoshika** [firebase/firebase-tools#7553]
### [REQUIRED] Environment info

**firebase-tools:**

13.9.0

**Platform:**

macOS

### [REQUIRED] Test case

1) Turn off device WiFi
2) Run local emulator:

```
firebase emulators:start --project demo-project --only auth,functions,firestore,storage --import exports/seed
```

3) Make a callable function request from client. Set the callable function to make a request to local emulator firestore:

```
await db.collection('widgets').get()
```

4) Observe the exception:

```
request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com
```

### [REQUIRED] Steps to reproduce

See above

### [REQUIRED] Expected behavior

Firebase development using firebase-tools, firebase-admin, and Firebase's Emulator works offline without internet connection.

### [REQUIRED] Actual behavior

Using firebase-tools, firebase-admin, and Firebase's Emulator while offline results in `request to https://oauth2.googleapis.com/token failed, reason: getaddrinfo ENOTFOUND oauth2.googleapis.com` error.

**Comment by aalej** [comment]
Hey @johnnyoshika, thanks for reaching out. I’m currently unable to reproduce the behavior you mentioned. When invoking the function that makes a request to the Firestore emulator, no errors are being raised.

Based on the information provided, I created this [repo](https://github.com/aalej/issues-7553) to try and replicate this. In case I may have missed anything or made a mistake with the setup, just let me know. Alternatively, any chance you could provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that we can replicate this on our end?

**Comment by johnnyoshika** [comment]
@aalej Thanks for creating that repo. I ran it and it indeed worked fine offline. I'll try to reconcile the differences between my project and your repo to see what's preventing my project from working offline. Once I figure that out, I'll create a minimum reproducible example.
