### ISSUE TITLE
Permissions required for service account deploy

### ISSUE THREAD

**Issue by ottob** [firebase/firebase-tools#7754]
Many people seems to have the same issue. See for example https://github.com/firebase/firebase-tools/issues/6593, https://github.com/firebase/firebase-tools/issues/6060 and https://github.com/firebase/firebase-tools/issues/5340#issuecomment-1870359149

I found some semi official advice here: https://groups.google.com/g/firebase-talk/c/gc1Me4WCRok/m/QEoVHBlYAwAJ
The recommended role was `Firebase Develop Admin`. But even that will not work. That role is missing the `firebaseextensions.instances.list` permission. Only the Firebase Admin roles has that atm, and that seems like overkill.

I even tried to create a custom IAM role with only the `firebaseextensions.instances.list` permission, but this permission can not be found.

<img width="590" alt="Screenshot 2024-09-26 at 23 17 58" src="https://github.com/user-attachments/assets/4bb93eb1-2b0e-4a83-af07-fbec4dfef8e5">

Can you please add the `firebaseextensions.instances.list` permission to the `Firebase Develop Admin` IAM role?

### [REQUIRED] Environment info

**firebase-tools:** 13.20.0

**Platform:** Ubuntu

### [REQUIRED] Test case

`firebase deploy` using a google service account (GADC), for example from a GitHub action.

### [REQUIRED] Steps to reproduce

run `firebase deploy`

### [REQUIRED] Expected behavior
successful deploy

### [REQUIRED] Actual behavior
lots of permission errors in debug log

**Comment by ottob** [comment]
`cloudscheduler.jobs.update` was also required when I tried to deploy. That was also not part of `Firebase Develop Admin`

**Comment by aalej** [comment]
Hey @ottob, thanks for reporting this. The `firebaseextensions.instance.list` permission will be required for any deployments that includes Firebase Cloud Functions. Here's a [comment](https://github.com/firebase/firebase-tools/issues/7582#issuecomment-2374921875) from someone from our engineering team explaining this in detail. Could you try adding the `Firebase Extensions Viewer` role to see if this would resolve the permission issue?

Regarding the `cloudscheduler.jobs.update`, I think this permission is required to be able to deploy scheduled functions since these functions uses Cloud Scheduler to invoke your function.

**Comment by ottob** [comment]
Thanks for you reply. Unfortunately I cannot test this right now, but I'll reply when I have done so.

But according to 
https://cloud.google.com/iam/docs/understanding-roles#firebaseextensions.viewer that roles does not seem to have the `firebaseextensions.instances.list` permission.

**Comment by staticshock** [comment]
I just ran into this as well, and adding the `Firebase Extensions Viewer` role to the service account (as recommended above) resolved it 👍

**Comment by aalej** [comment]
Thanks for confirming @staticshock. @ottob, looking at the doc you shared, it does seem like the role does not contain the `firebaseextensions.instance.list` permission. Although, when I tried to reproduce this, adding the `Firebase Extensions Viewer` role resolves the permission issue.

I'll raise this to our engineering team to get additional context on whether this is a documentation issue or something else entirely.

**Comment by Sam-Spencer** [comment]
> I just ran into this as well, and adding the `Firebase Extensions Viewer` role to the service account (as recommended above) resolved it 👍

Chiming in to say that this resolved the issue for me too -- although that role doesn't appear when searching for the necessary permission. Looking forward to more guidance on this. Thank you ❤️.

**Comment by zenhorace** [comment]
Had this issue, and the workaround worked for me. It's unfortunate that this issue remains unresolved.

**Comment by carchrae** [comment]
this was super annoying, and after finding a very convoluted set of roles that worked, i then found my scheduled jobs still did not work!  :/   

the tldr fix:  give your service account "Editor" permissions.  

while this is certainly far too many permissions, but if you are coming here because `FIREBASE_TOKEN`  no longer works and you are trying to use `GOOGLE_APPLICATION_CREDENTIALS` then setting the credentials to "Editor" will save you some hair pulling and a ton of wasted time deploying 

@aalej - it is a bit of a crying shame there aren't some decent permissions defined that work for firebase, but i can imagine the meetings involved and people arguing over what should be called what and have what roles.
