### ISSUE TITLE
Deploying v2 functions with uppercase letters and '- fails

### ISSUE THREAD

**Issue by amit20897** [firebase/firebase-tools#7759]
### [REQUIRED] Environment info

**firebase-tools:** 13.20.0  
**Platform:** macOS Sequoia

### [REQUIRED] Test case

A Firebase function with the following name fails to deploy:

under a file called analytics.js create:
```javascript
exports.reportGtmEvent = onRequest((req, res) => {
  res.send("Analytics GTM Event Function");
});
```

The function name contains an uppercase letter and a hyphen: `"analytics-reportGtmEvent"`.

### [REQUIRED] Steps to reproduce

1. Define a second-generation Firebase function with a name containing both an uppercase letter and a hyphen, e.g., `analytics-reportGtmEvent`.
2. Attempt to deploy the function using Firebase CLI (`firebase deploy --only functions`).

### [REQUIRED] Expected behavior

The function should be deployed successfully, and the instance should start and receive requests.

### [REQUIRED] Actual behavior

While the function appears to be created, the deployment fails with the following error, preventing the instance from starting and receiving requests:

```bash
i  functions: updating Node.js 20 (2nd Gen) function functions:analytics-reportGtmEvent(us-central1)...
Could not create or update Cloud Run service analytics-reportgtmevent, Container Healthcheck failed. Revision 'analytics-reportgtmevent-00002-doh' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.

Logs URL: https://console.cloud.google.com/logs/viewer?project=cyder-ai&resource=cloud_run_revision/service_name/analytics-reportgtmevent/revision_name/analytics-reportgtmevent-00002-doh&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22analytics-reportgtmevent%22%0Aresource.labels.revision_name%3D%22analytics-reportgtmevent-00002-doh%22
For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start
```

The error points to an issue with Cloud Run, where the container fails to start and listen on the specified port (`PORT=8080`).

**Error message in summary:**
```
Revision 'analytics-reportgtmevent-00002-doh' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined by the PORT=8080 environment variable.
```

### Additional Information

I suspect this issue may be related to the function name containing both uppercase letters and hyphens. The lowercase conversion in the deployment logs (`analytics-reportgtmevent`) might be causing issues with the Cloud Run service startup. Could you confirm whether there are restrictions on function names with uppercase characters or hyphens in Firebase functions (specifically for second-gen functions)?

Thank you for looking into this issue!

**Comment by aalej** [comment]
Hey @amit20897, thanks for reaching out and for creating a detailed report. I’m trying to reproduce the error you encountered, but so far, I’m able to deploy functions successfully. It looks like you’re using [grouped functions](https://firebase.google.com/docs/functions/organize-functions?gen=2nd#group_functions) which generates a function name that looks like `<group_name>-<function_name>`. 

I created this [repo](https://github.com/aalej/issues-7759) to try and reproduce the error, let me know in case I’m missing anything or if I may have made a mistake. Also, from what I can gather, the “Container Healthcheck failed” error usually means that the code you’re trying to deploy is crashing on load. At the moment, it’s difficult to determine why it’s crashing. Any chance you could share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) with us so that we can replicate the issue?
