### ISSUE TITLE
Inconsistent behavior with TIME datatype in constant vs variable input

### ISSUE THREAD

**Issue by 1amageek** [firebase/firebase-tools#7834]
### [REQUIRED] Environment info

**firebase-tools:** 13.22.0

**Platform:** macOS

### [REQUIRED] Test case

Schema:
```graphql
type Sample @table {
  startTime: String! @col(name: "start_time", dataType: "TIME")
}
```

Mutations:
```graphql
mutation insertConst @auth(level: PUBLIC) {
	sample_insert(data: {
		startTime: "10:00:00"
	})
}

mutation insertVal($startTime: String) @auth(level: PUBLIC) {
	sample_insert(data: {
		startTime: $startTime
	})
}
```

### [REQUIRED] Steps to reproduce

1. Set up a Firebase project with the above schema.
2. Execute the `insertConst` mutation - this should succeed.
3. Execute the `insertVal` mutation with the following arguments:
   ```json
   {
     "startTime": "10:00:00"
   }
   ```
4. Observe that the `insertVal` mutation fails while `insertConst` succeeds.

### [REQUIRED] Expected behavior

Both `insertConst` and `insertVal` mutations should successfully insert a record with the startTime "10:00:00".

### [REQUIRED] Actual behavior

The `insertConst` mutation succeeds, but the `insertVal` mutation fails with the following error:

```
Error: Request failed with status 400
    at HB.handleInvalidResponse (/Users/1amageek/.cursor/extensions/firebase.firebase-vscode-0.9.1/dist/extension.js:14:3451947)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at p (/Users/1amageek/.cursor/extensions/firebase.firebase-vscode-0.9.1/dist/extension.js:14:3424160)
```

This error occurs when trying to execute the following mutation with the provided arguments:

```graphql
mutation insertVal($startTime: String) @auth(level: PUBLIC) {
  sample_insert(data: {startTime: $startTime})
}
```

Arguments:
```json
{
  "startTime": "10:00:00"
}
```

It appears that there is an inconsistency in how the Firebase tools handle constant values versus variable inputs for TIME data types.

**Comment by fredzqm** [comment]
Thanks for the bug report!

[`@col(dataTyle)`](https://firebase.google.com/docs/reference/data-connect/gql/directive#col) is a raw SQL escape hatch that allows you customize the underlying Postgres data type.

Data Connect doesn't perform validations on whether the Postgres data type would match the GraphQL data type. When `dataType` isn't compatible, the behavior may be undefined.

In your example:
```
type Sample @table {
  startTime: String! @col(name: "start_time", dataType: "TIME")
}
```
Since you declared the field as `String` type, data connect processes it as a string type. The generated SQL expects a `String` type and cast the variable into `$1::text`. If the SQL column type is compatible with `text`, then it would work. Though `time` isn't compatible with `text`.

```
WITH  "sample_insert_temp"  AS (INSERT INTO  "public"."sample"  ( "start_time" , "id" ) VALUES ( $1 ::text,uuid_generate_v4()) RETURNING jsonb_build_object('id', REPLACE(CAST(( "id" ) AS text), '-', '')) AS j) SELECT * FROM  "sample_insert_temp" 
```

To work with timestamp, I'd recommend change your schema to:
```
type Sample @table {
  startTime: Timestamp! @col(name: "start_time", dataType: "TIME")
}
```

The reference doc specifies the expected format.
- Timestamp: https://firebase.google.com/docs/reference/data-connect/gql/scalar#Timestamp
- Date: https://firebase.google.com/docs/reference/data-connect/gql/scalar#Date
-

**Comment by 1amageek** [comment]
Thank you for your response.
Is it not possible to support other types, such as PostGIS?
Wouldn't it be challenging to migrate to DataConnect without being able to define those types?

**Comment by 1amageek** [comment]
@joehan @fredzqm 
Is there a possibility that other types will be supported in the future?
If support is added, I would like to migrate development to Data Connect, but if not, transitioning to Data Connect will be challenging.

**Comment by fredzqm** [comment]
Could you help elaborate what is blocking your use cases?
We will do our best to accommodate.

@col(dataType) can be used to customize Postgres column data type. However, it must be compatible with the GraphQL scalar type.

Can you help me understand the desired behavior in your mind?
In the `startTime: String @col(dataType: "TIME")` case.

What if you try to populate it with an invalid Postgres TIME string as GraphQL literal, would you expect the insert GQL to compile, but fails at runtime? If an invalid string value is given as GQL literal, it would pass the variables parsing phase, but fails in the Postgres layer.


Thank you! Appreciated the feedback!
