### ISSUE TITLE
Won't connect to (or recognize)  emulator that is already running

### ISSUE THREAD

**Issue by segevsh** [firebase/firebase-tools#7899]
### [REQUIRED] 

**firebase-tools:**13.23.1

**Platform:**macOS

### [REQUIRED] Test case

We have the emulator already running, after it's loaded config, pre-existing data, storage buckets, etc... The Firebase Data Connect extension for vsCode won't recognize it, but rather force us to launch new emulator in order for us to work with our local DB. Doing that will mean running a new and empty environment, which will be counter productive.

### [REQUIRED] Steps to reproduce

Run emulators, start vs code and attempt to connect to your `data connect` (pgsql) db.

### [REQUIRED] Expected behavior

It should either recognize the environment (using firebase.json, and the ports already defined within), and connect to it. Or for the very least, allow us to only launch dataconnect emulator and not the rest of them. 

### [REQUIRED] Actual behavior

There are no logs to submit. There is no bug, but an issue in how it is setup and configured .

**Comment by aalej** [comment]
Hey @segevsh, thanks for reaching out. Let me know if I may be wrong here, but from what I can understand the issue is that the Firebase Data Connect VS Code extension is not detecting the already running emulator instance.

I'm working on reproducing this, but so far after starting the emulators, opening VS Code and checking the Firebase Data Connect VS Code extension shows that the emulators is running:

1. Run `firebase emulators:start` in a terminal
2. Open the project in VS Code 
3. Open the Firebase Data Connect VS Code extension
    - Outputs:
![image](https://github.com/user-attachments/assets/8550a46a-484b-4c0f-a2db-e2bf92ef2e50)

If I misunderstood or missed anything here, please let me know. Also, which version of the Firebase Data Connect VS Code extension are you using?

I'm using the ff to reproduce this:
- firebase-tools: v13.24.0
- Firebase Data Connect VS Code extension: v0.10.6
- platform: macOS Sonoma 14.7

And my `firebase.json` config for the emulators is:
```json
{
  ...
  "emulators": {
    "firestore": {
      "port": 8080
    },
    "storage": {
      "port": 9199
    },
    "dataconnect": {
      "port": 9399
    },
    "ui": {
      "enabled": true
    },
    "singleProjectMode": true
  }
}
```
