### ISSUE TITLE
Error: Cloud resource location is not set for this project

### ISSUE THREAD

**Issue by dpschramm** [firebase/firebase-tools#7901]
### [REQUIRED] Environment info

**firebase-tools:** 13.23.1

**Platform:** macOS 14.5 (23F79)

### [REQUIRED] Test case

Initialise firebase project with Auth, Hosting, Firestore, and Storage.

### [REQUIRED] Steps to reproduce

1. Create new Firebase project on Firebase Console.
2. Enable Auth and Hosting via the Firebase Console.
3. Create a Firestore database with location `australia-southeast1` in the Firebase Console.
4. Enable Blaze Billing tier.
5. Create a Storage bucket in the `US-WEST1` location in the Firebase Console.
6. Run `firebase init` in the local project folder.
7. Choose to setup Hosting, Firestore, and Storage services.
8. Choose to setup an existing project; select existing project from the list.

### [REQUIRED] Expected behavior

Command line tool successfully sets up local firebase configuration.

### [REQUIRED] Actual behavior

Command line tool fails once it reaches:

```
=== Storage Setup

Error: Cloud resource location is not set for this project but the operation you are attempting to perform in Cloud Storage requires it. Please see this documentation for more details: https://firebase.google.com/docs/projects/locations
```

### Other info

- `firebase init` completes successfully if the Storage service is not selected.
- The support documentation that the error suggests does not seem to have relevant troubleshooting information: https://firebase.google.com/docs/projects/locations
- Gemini suggested setting _Default GCP resource location_, however I could not find this setting in the Firebase project settings.
- This Stack Exchange question appears to be running into the same issue: https://stackoverflow.com/questions/79152768/firebase-cloud-resource-location-is-not-set-for-this-project
- This issue report seems similar: https://github.com/firebase/firebase-tools/issues/4917

**Comment by lucas181088** [comment]
Hello friend, did you manage to get the answer?

**Comment by aalej** [comment]
Hey @dpschramm, apologies for the delay and thanks for the detailed report. I'm able to reproduce the error you mentioned, I'll raise this to our engineering team so they can take a look.

**Comment by tonyjhuang** [comment]
We're working on cutting a new release with the fix by EOD, thanks for the report!

**Comment by nguyentrungtu** [comment]
@tonyjhuang is this fixed? I'm still running into this error.

**Comment by albertjo** [comment]
+1 also running into this error.

**Comment by blagoySimandov** [comment]
Same here..

**Comment by aalej** [comment]
Hey folks, sorry to hear you're still encountering this issue. The fix for this was released in firebase-tools [v13.24.1](https://github.com/firebase/firebase-tools/releases/tag/v13.24.1). I'm trying to reproduce this using v13.24.2(current latest), but so far no errors are being raised. 

Could you try updating to firebase-tools >= v13.24.1 to see if this would resolve the issue?

**Comment by blagoySimandov** [comment]
Yeah, it got fixed after updating

**Comment by alexander-rod** [comment]
Still running into this problem when trying to create a new account. Have checked everything twice and even wiped my project to try again.

**Comment by aalej** [comment]
Hey @alexander-rod, I can't seem to reproduce the issue using the latest version of firebase-tools, which is currently v13.29.1. I tried creating a new project, and no errors were raised after running `firebase init` and choosing Storage. 

I don't think this error could be raised in the latest version of firebase-tools since the API call that causes this was removed in #7905. Could you let me know which version of firebase-tools you're using? Also, any chance you could share the contents of your firebase-debug.log so that we can get a better idea on what caused the error?

**Comment by mjlocke0529** [comment]
Can we get support on this this looks to be an active issue again.

**Comment by FlepTheFlabbergasted** [comment]
Happening for me as well

```
$ npx firebase-tools --version
13.35.1
```

**Comment by filutfi** [comment]
Happening for me too with v13.35.1,
have you solve this problem @FlepTheFlabbergasted ?

**Comment by filutfi** [comment]
finally, it solved after updated v14.2.1

**Comment by isiahw1** [comment]
I'm seeing this problem again in 14.4.0. 
Please advise.

**Comment by aalej** [comment]
Hey @isiahw1. The API call that causes this error was removed in #7905, so it's odd that you're still encountering this issue. Could you share the contents of you `firebase-debug.log` so that we can have a better idea of what could be causing this?  Please remove any PIIs before sharing the contents

**Comment by blujedis** [comment]
Still seeing this with any new project. If I run `firebase projects:list` any new project shows **[Not Specified]** under Resource Location ID.

Any time I run `firebase init` (I have only firestore enabled) I get the error "Cloud resource location is not set for this project but the operation you are attempting to perform in Cloud Firestore requires it. Please see this documentation for more details: https://firebase.google.com/docs/projects/locations"

I don't use Firebase a ton but enough to know how it works. The global resource location used to be in settings I see that is no longer available in the console. 

**UPDATE:**

So it turns out that somehow the path to the executable was pointed to the wrong location. When I manually specify the path to the firebase-tools the error goes away. 

In my case I ran `pnpm -g bin` to verify where the global directory was. Then viewed the firebase exec file in the bin directory, found the path to the executing script then ran it directly. 

So it appears there's an issue with how the firebase CLI, firebase-tools, were bound on my system. No clue how that might have happened but that was the resolution.
