### ISSUE TITLE
Firebase App Distribution: “Permission Denied” Error on Upload Despite Successful Build Upload

### ISSUE THREAD

**Issue by romankulykov** [firebase/firebase-tools#7918]
I'm experiencing an issue with Firebase App Distribution where enabling automated test devices in the build configuration results in a `403 PERMISSION_DENIED` error. Despite this error, the build successfully uploads to Firebase. The error details are as follows:

```
{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```

Steps to Reproduce

	1.	Configure Firebase App Distribution in the project and include automated test devices by adding the following settings in the Gradle configuration:

testDevicesFile = "$rootDir/test_devices.txt"
testNonBlocking = true

	2.	Attempt to upload the build using Firebase App Distribution.
	3.	Note that while the build uploads successfully, the response contains a 403 PERMISSION_DENIED error message.

Expected Behavior

The build should upload without any errors if the permissions are configured correctly.

Actual Behavior

The build is uploaded to Firebase; however, the following error response is returned:

```
{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```

This error seems misleading as it implies a permissions issue that does not actually prevent the build upload. It may impact workflows that rely on automated tests and error monitoring.

Additional Context

	•	Verified all required permissions and roles.
	•	Attempted regenerating service account credentials and checking roles, but the issue persists.
	•	The error only occurs when enabling the automated test devices configuration in the build.

I also tried this solution:
https://stackoverflow.com/a/62388910
But even given all permission didn't solve my problem

**Comment by aalej** [comment]
Hey @romankulykov, thanks for the detailed report. This may not be the best place to address this issue since this repo is for the Firebase CLI, and it looks like you're using Gradle to distribute your app.

I understand that you've verified that the required permissions are granted, but at the moment, it seems like there are still permission issues. I'd recommend reaching out to our [Firebase Support team](https://firebase.google.com/support/troubleshooter/contact) as they’re better equipped to handle issues that occur due to permissions or project configurations.
