### ISSUE TITLE
Nextjs firebase tutorial: can't load the page

### ISSUE THREAD

**Issue by koroman17** [firebase/firebase-tools#8050]
### [REQUIRED] Environment info

**firebase-tools: 13.28.0**

**Platform: Windows**

### [REQUIRED] Steps to reproduce

I followed this tutorial until step 6 https://firebase.google.com/codelabs/firebase-nextjs#5
After click on the Sign in button, I can no longer access the page "This site can’t be reached".

In the project, Auth section, it says "Cross origin redirect sign-in is no longer supported in many browsers. Update your app to ensure your users can continue to sign into your app."

There is a conflict. The auth domain in the project settings is firebaseapp.com, while the domain in the App hosting is hosted.app.

In the browser console, it logs: "The FetchEvent for "****.hosted.app/" resulted in a network error response: the promise was rejected."
Uncaught (in promise) FirebaseError: Firebase: Need to provide options, when not being deployed to hosting via source. (app/no-options).
    at initializeApp (auth-service-worker.js?firebaseConfig=****)
    at fetchWithFirebaseHeaders (auth-service-worker.js?firebaseConfig=****)
    at auth-service-worker.js?firebaseConfig=****

Please help me solve this issue.

**Comment by aalej** [comment]
Hey @koroman17, this repository is for the Firebase CLI so this isn't the best place to track this. I'd recommend filing e report to https://github.com/firebase/friendlyeats-web since the source of the Codelabs if from there. Also, looking through the issues, I think you may be encountering a similar error to https://github.com/firebase/friendlyeats-web/issues/295.
