### ISSUE TITLE
The term 'firebase' is not recognized in PowerShell. 

### ISSUE THREAD

**Issue by carpben** [firebase/firebase-tools#846]
### Version info
Bash on Ubuntu on Windows (WSL) - 4.0.1

Powershell - The term 'firebase' is not recognized ....
### Platform Information

Windows 10
### Steps to reproduce
1. On both Powershell and Bash on Ubuntu (16) on Windows (WSL) - run "npm install -g firebase-tools". 
2. On both Powershell and Bash run "firebase login".  

### Expected behavior
Firebase login running on both Powershell and Bash. 

### Actual behavior
Though the installation is succesfull, when running "firebase login" on Powershell there is an error: "The term firebase is not recognized ..."

**Comment by mbleigh** [comment]
This is an issue with the `PATH` environment variable in WSL, I imagine, and will have to do with how you have Node.js and NPM installed. I don't have specific guidance for how to fix it, but make sure that the `PATH` variable includes your global `node_modules/.bin` for both PowerShell and WSL.

I'm not actually sure if you can use the same Node.js installation for both. Unless you have a strong reason to, I'd suggest installing Node.js in WSL and using it instead of PowerShell.

**Comment by carpben** [comment]
@mbleigh 
I'm not sure you understood me. The problem occurs when I run "firebase login" from Powershell. From WSL it works fine. 
I did not use the same node.js installation for PowerShell and WSL. For Bash on ubuntu on Windows I use the Debian installation. The reason I use mostly powerShell is that it is faster then Bash on Ubuntu on Windows.

**Comment by kreendurron** [comment]
I have same issue, I can run firebase login just find from node.js command prompt but not from powershell inside of Visual Studio Code.

**Comment by jeroenVerdonschot** [comment]
Issue still exits.

**Comment by digimbyte** [comment]
this is not an issue, this is a 'security feature' within the console itself, you need to authorize the console inside VS code to have full permission
I personally use: `Set-ExecutionPolicy -Scope CurrentUser Unrestricted`

**Comment by VaAndCob** [comment]
> Set-ExecutionPolicy -Scope CurrentUser Unrestricted

though it's from 2021, but this short command solve my mystery .
