### ISSUE TITLE
Hosting deploy fails with multiple sites in the project

### ISSUE THREAD

**Issue by arsen** [firebase/firebase-tools#902]
firebase --version : 4.2.1
os: Mac OS High Sierra (10.13.5)

After I have added a second site to the same project the deploy is failing. 
In the debug it is giving the following message when I run a deploy command:
cmd: firebase deploy --only hosting:dealer

`[info] Project Console: https://console.firebase.google.com/project/[project]-dev/overview
[debug] [2018-08-31T18:22:18.699Z] TypeError: Cannot read property 'deploys' of undefined
    at /Users/[user]/.npm-global/lib/node_modules/firebase-tools/lib/deploy/index.js:105:32
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[error] 
[error] Error: An unexpected error has occurred.`

And this is my .firebaserc file:

```json
{
  "projects": {
    "default": "[name]-dev",
    "prod": "[name]-prod"
  },
  "targets": {
    "[name]-dev": {
      "hosting": {
        "dealer": [
          "[name]-dealer-dev"
        ],
        "consumer": [
          "[name]-dev"
        ]
      }
    }
  }
}
```

**Comment by jaonoctus** [comment]
Same here, on Ubuntu 18.04

**Comment by danielx** [comment]
I also got this error but i fixed it by changing my `firebase.json` config to use an array with a hosting configuration for each site.

old `firebase.json`
```JSON
{
  "hosting": {
    "public": "dist",
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```

updated `firebase.json`
```JSON
{
  "hosting": [
    {
      "target": "production",
      "public": "dist",
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ]
    },
    {
      "target": "staging",
      "public": "dist",
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ]
    }
  ]
}
```

My `.firebaserc`
```JSON
{
  "projects": {
    "default": "[project-id]"
  },
  "targets": {
    "[project-id]": {
      "hosting": {
        "production": [
          "[project-id]"
        ],
        "staging": [
          "[project-id]-staging"
        ]
      }
    }
  }
}
```

**Comment by gammafilho** [comment]
Same problem and put an array didn't work.

**Comment by vnoitkumar** [comment]
Can this be done in Spark Plan? Or Need an Upgrade!

**Comment by sikloidz** [comment]
I was facing the same problem, I try @danielx suggestion and it works. So, this error occurred because the firebase.json file didn't get update when I run the `firebase target:apply hosting target-name resource-name` command.

**Comment by bkendall** [comment]
@sikloidz `firebase target:apply` doesn't change `firebase.json` - it only effects `.firebaserc`.

**Comment by bkendall** [comment]
@arsen Thanks for bringing this to our attention. It seems as though that happens when a hosting deploy target name that doesn't exist in `firebase.json`. I've brought this to the attention of the appropriate people. 😄 

When using multiple Hosting sites, it's important to follow all the directions in [the documentation](https://firebase.google.com/docs/hosting/multisites) in order for deployments to work. The cliff notes version going from one to two sites (where the project name is `my-web-app`:
- create a new site in the Firebase Console under Hosting (e.g. `new-site`)
- run `firebase target:apply [some-target-name] my-web-app` to give a name to to the original site
- run `firebase target:apply [new-target-name] new-site` in the terminal in your project
- update `firebase.json` to make the `hosting` object an array, being sure to specify in each element the `target` value
  - be sure to add `"target": "[some-target-name]",` to the original object so that the default site can continue to be deployed
  - a sample configuration may look like this (w/o comments, 'cause JSON):
```js
{
  "hosting": [
    {
      "target": "some-target-name",
      "public": "dist", // this was the original deployed folder, now with `target` above
    },
    {
      "target": "new-target-name", // this is a new `target` and object
      "public": "new-dist",
    }
  ]
}
```
- now `firebase deploy --only hosting` should deploy both `some-target-name` and `new-target-name`, and `firebase deploy --only hosting:some-target-name` will only deploy `some-target-name`.

Hope this helps!

**Comment by anaganisk** [comment]
This happened to my when I got confused when I added multiple resources check your .firebaserc and in the array of the target name only the activated site-names must be present.

**Comment by fkajouii** [comment]
I came here because I got the same deploy error when adding a second site to firebase hosting. I was able to resolve it using @danielx comment by updating the .firebaserc file.

Original:
`"targets": {
    ["project-name"]: {
      "hosting": {
        ["target:apply-name"]: [
          ["project-name"], ["deployment-folder"]
        ],
        ["target-apply-name2"]: [
          ["project-name2"], ["deployment-folder2"]
        ]
      }
    }
  }`

Updated:
`"targets": {
    ["project-name"]: {
      "hosting": {
        ["target:apply-name"]: [
          ["project-name"]
        ],
        ["target-apply-name2"]: [
          ["project-name2"]
        ]
      }
    }
  }`

**Comment by emilsall** [comment]
@bkendall For my use case, I want the exact same hosting settings for two deploy targets: stage and live. I just want to push different build to these two targets, so do I really need to duplicate the settings in firebase.json? I would prefer if it defaulted to using the non-array settings for both. Thanks!

**Comment by bkendall** [comment]
@emilsall As I recall, yes, the settings have to be duplicated.

**Comment by emilsall** [comment]
@bkendall Alright, thanks for the reply!

**Comment by zinxor** [comment]
I was able to resolve this by updating the main `firebase.json` configration. The issue was in the hosting reference syntax, which needs to be updated using an `array` formate instead of the `brackets` formate.

**Initial file – generated by firebase:**

```
{
  "database": {
    "rules": "database.rules.json"
  },
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint"
    ]
  },
  "hosting": {
    "public": "public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  },
  "storage": {
    "rules": "storage.rules"
  }
}

```

**Updated file, with revising hosting section:**

```
{
  "database": {
    "rules": "database.rules.json"
  },
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint"
    ]
  },
  "storage": {
    "rules": "storage.rules"
  },
  "hosting": [
    {
        "public": "public"
    },
    {
      "target": "staging",
      "public": "public"
    },
    {
      "target": "production",
      "public": "public"
    }
  ]
}

```

I'm only using 2 enviornments in this case. I did not have to make any updates to the `.firebaserc` file.

**Comment by bkendall** [comment]
Nice update. I'm going to chat with the folks responsible about this code path and behavior to see if we want to change our initial templates (specifically for `hosting`) to be arrays rather than objects. That way, when someone wants to do multi-site or use multiple targets, that user doesn't have to try to parse out object vs. array in `firebase.json` or in the documentation.

For the time being, I'm going to close this. If there's any more feedback, please feel free to leave it here!

**Comment by YohanWadia** [comment]
> @vnoitkumar you must be on the Blaze plan to create multiple Hosting sites. See the note here: https://firebase.google.com/docs/hosting/multisites

??? it doesnt say anything
Infact pricing says Mulitple sites can be deployed to Spark plan too!

**Comment by herberlin** [comment]
To deploy also to the default context the following firebase.json worked for me using "site" with the project id:
```
{
  "hosting": [
    {
      "site": "my-firebase-id",
      "public": "public",
       [...]
    },
    {
      "target": "first-target-name",
      "public": "first-target-folder",
            [...]
    },
    {
      "target": "second-target-name",
      "public": "second-target-folder",
      [...]
    },
  ]
}
```
The firebase target:apply command was only neccessay for the target-sites, not for the main site.

**Comment by DisgruntledTech** [comment]
This is what worked for me and was the easiest solution was to run the command below and select the same options I did when I first started the project.

firebase init
