### ISSUE TITLE
--quiet option when deploying cloud functions is needed

### ISSUE THREAD

**Issue by g-viet** [firebase/firebase-tools#908]
### Version info

Firebase SDK version: 4.1.2

### Platform Information

Operating System version: OS X

### Expected behavior

Should deploy functions with `--quiet` mode like in `gcloud`

### Actual behavior

Currently, It is unable to build and deploy automatically in CI.
It always requires an answer yes/no for function that need to delete.

**Comment by laurenzlong** [comment]
Hi, this is intentional to ensure that you don't accidentally delete functions you don't intend to. If you'd like a non-interactive way to delete functions you can run `firebase functions:delete <functionName> --force`

**Comment by g-viet** [comment]
Thanks for your prompt reply.
I think people always aware that thing when use `--force` or `--quiet`. There are many environment when running a project. We just should not use `--force` in production by the way.
Currently, we are handling that problem by deleting all functions then deploy all again.
But instead of that, I suppose to use `--force` when deploying functions is better. It reduces many cost time for testing.

**Comment by ahaverty** [comment]
@g-viet I think this issue is similar to: https://github.com/firebase/firebase-tools/issues/877

Deleting all functions, wouldn't that cause large downtime for users?

**Comment by g-viet** [comment]
@ahaverty It is exactly what I need.
Because now firebase CLI has no option like `--allow-deletes` as you said.
So we implemented by this way:
1. Collect all cloud functions by using gcloud
2. Delete every functions
3. Deploy

Because it will take more time when running on CI, so I think `--allow-deletes` is best.

**Comment by g-viet** [comment]
#877

**Comment by g-viet** [comment]
#877

**Comment by mbleigh** [comment]
If there are functions deployed outside those by your CI system, you should
scope the CI deploy command only to the functions it covers. For example if
I have a,b,c functions but CI is only supposed to deploy a,b:

    firebase deploy --only functions:a,functions:b

Then I won't get an error if c is a function that isn't in the source code
available to CI.

If you need to delete functions (which should be reasonably rare) you can
use the command to do so as listed in the email message.

On Sep 11, 2018 12:47 AM, "Viet Nguyen" <notifications@github.com> wrote:

#877 <https://github.com/firebase/firebase-tools/issues/877>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/firebase/firebase-tools/issues/908#issuecomment-420180293>,
or mute the thread

**Comment by ahaverty** [comment]
@mbleigh thanks for the suggestions, that's kind of what we're doing right now, but as I detailed in https://github.com/firebase/firebase-tools/issues/877#issuecomment-414474037 we actually delete functions regularly enough for it to be an annoyance, mostly due to the headache of production access needed, and manual bottlenecks in our CI deploys.

**Comment by run00** [comment]
Totally agreed!

I can't stress how seriously this is making me reconsider adopting Firebase.  CI should be completely automated, if it isn't, you invalidate the meaning of "continuous".  Not all functions are part of an API (like triggers for starters) and SHOULD be deleted as application architecture changes over time.  

Yes, its a small percentage of deployments - but in a multi-stage environment - deployment its a real headache when you have to go to each environment and manually delete and then deploy.  Sequencing becomes a real problem, increasing human error, and completely invalidating the point of having a good CI process in place.

Furthermore, I contend that users who are afraid of a deletion behavior (referenced in #877)  have problems further upstream with automated testing, code review, source control, etc.  If you are doing deployments to a production environment and suddenly find that things are deleted there ... you're doing it wrong.  If your a hobbyist, then this is understandable, but your application probably isn't important enough that the deletion is a big deal.  If you are "professional" with a large scale application, then you have much bigger issues in your deployment process than deleting functions.   Deployment is NOT the place to address this problem.

PLEASE!  Don't let development teams, who lack a proper grounding in the fundamentals, ruin the use of your product for the rest of us.

**Comment by mbleigh** [comment]
We're still thinking about this given the feedback, thanks.

**Comment by danielmhair** [comment]
Any update on this?

**Comment by g-viet** [comment]
@danielmhair This issue was released in v5.1.0
https://github.com/firebase/firebase-tools/releases/tag/v5.1.0

**Comment by darrelfrancis** [comment]
Awesome, thank you!
