### ISSUE TITLE
Typescript issue with private typescript repo dependancy.

### ISSUE THREAD

**Issue by jk89** [firebase/firebase-tools#930]
### Version info

See repo i'm using the latest firebase-tools w/e @latest is

### Platform Information

Linux

### Steps to reproduce

Stackoverflow question include MVCE: https://stackoverflow.com/questions/52594613/firebase-deploy-error-with-typescript-project-with-several-typescript-dependance

### Expected behavior

firebase deploy should work when using typescript dependancies from a private repo so long as the credentials are provided (not ssh) or if it is a public repo like in my SO example.

### Actual behavior

Function load error: Code in file ./lib/index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'dep-repo-1'

**Comment by laurenzlong** [comment]
@jk89 The error message is actually coming from Google Cloud Functions servers. So even if Firebase CLI has the correct credentials to access the private repo, the server-side build step will fail since it only has access to either local files or to public modules. Google Cloud Functions has a public issues tracker if you would like to file this as a feature request: https://cloud.google.com/support/docs/issue-trackers
