### ISSUE TITLE
error while installing on windows

### ISSUE THREAD

**Issue by jahtalab** [firebase/firebase-tools#98]
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR!

npm ERR! ^
npm ERR! File: C:\Users\~\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by drtriumph** [comment]
This specific error is referencing the module `inherits` which is not specifically required by `firebase-tools`. I suspect if a release of that module caused it, it's probably been fixed by now. Try running `npm install -g firebase-tools` again to see if it works, and if not you might need to clear your npm cache again (`npm cache clean`) before trying again.

If you still can't get it to work, feel free to re-open the issue with some more information about your environment such as node version (`node --version`) and npm version (`npm --version`)
