### ISSUE TITLE
ENOENT Error on serving functions

### ISSUE THREAD

**Issue by jaksmid** [firebase/firebase-tools#987]
Firebase returns `error:  Error: spawn /usr/local/Cellar/node@6/6.14.4/bin/node ENOENT` on accepting a request without further detail.

### Version info

[2018-11-01T15:12:25.470Z] Command:       /usr/local/Cellar/node@6/6.14.4/bin/node /usr/local/bin/firebase serve --debug --only functions
[2018-11-01T15:12:25.471Z] CLI Version:   6.0.0
[2018-11-01T15:12:25.471Z] Platform:      darwin
[2018-11-01T15:12:25.471Z] Node Version:  v6.14.4

### Steps to reproduce

Running the `firebase serve --debug --only functions`, connecting via `ngrok` to `DialogFlowSampleAgent`. Send a request from `DialogFlow`.

### Expected behavior

Returns an answer.

### Actual behavior
Throws error:
```
✔  functions: dialogflowFirebaseFulfillment: http://localhost:5000/dialogflow-democopy/us-central1/dialogflowFirebaseFulfillment
error: ERROR: projects/dialogflowdemo-220313/locations/us-central1/functions/dialogflowFirebaseFulfillment
error:  Error: spawn /usr/local/Cellar/node@6/6.14.4/bin/node ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by bkendall** [comment]
This sounds more like a problem with your function's implementation than the serving logic of `firebase-tools`.

Options to try:
- Isolate the code path that is running the `ngroc`, `DialogFlowSampleAgent`, etc... stuff into its own script and test it
- Look through `firebase-debug.log` to see if there's any issue reported there regarding the CLI itself

It looks like something is trying to start a new node process with a node binary that doesn't exist. Does `/usr/local/Cellar/node@6/6.14.4/bin/node` exist on your machine?

**Comment by jaksmid** [comment]
Hello @bkendall, thanks for the response.

The function works for my colleague, so the implementation should be fine. 

The error is not even logged into `firebase-debug.log`

`/usr/local/Cellar/node@6/6.14.4/bin/node` goes directly to the node prompt.

**Comment by bkendall** [comment]
Without knowing much more about your development environment and the code you're executing, I don't think there's much I can do to help. If it's working for your colleague, I'd imagine that there's something different between your two workstations that's causing this error. If you can create a gist/snippet of code that I can copy to try and replicate your behavior, I'd be happy to do so, but I'm not seeing any flags that tie this directly to `firebase-tools` off-hand.

If you can provide more information to help me debug and replicate this issue, please feel free to re-open this issue and I can take a look. Sorry I can't be much use otherwise...
